### ISSUE TITLE
DataTables Refresh performance improvements

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWriteHTML#101]
DataTables, when Tabs or Collapsed Sections are used, require refresh when switching tabs or expanding collapsed section to make sure they are displayed properly. 

Unfortunately, my poor JavaScript skills provided a fix in two places to resolve that but the fix is so performance-intensive that it's driving me crazy. It's because every time section is expanded or tab is switched each and every table in HTML is recalculated when the only subset of tables should be. 

https://github.com/EvotecIT/PSWriteHTML/blob/d2c3d163b1686594770e368d7a1bea48980ef306/Resources/JS/HideSection.js#L5-L9

https://github.com/EvotecIT/PSWriteHTML/blob/d2c3d163b1686594770e368d7a1bea48980ef306/Resources/JS/tabbisAdditional.js#L13-L17

Need to find another way to do it:
1. On JS level find out how to do it properly
2. Use PowerShell and put those recalcs in proper places only targetting particular data tables. 
3. Wait for DataTables to fix it.

**Comment by opustecnica** [comment]
Przemyslaw,

I am starting to look into this because, like you, it is driving me insane.  I tried to comment it out to see what problem it is attempting to solve.  At a very superficial analysis it looks like, when commented out, everything keeps working as expected.  Again, very superficial analysis.  Could you please spend a few lines describing the original issue? 

THX!

**Comment by PrzemyslawKlys** [comment]
If you remove that code and switch between tabs some of the tables will not have some features shown. They will also not expand properly. 

It's even more visible if you use sections with a switch to keep it collapsed on start. 

You can see this issue in example I've attached.

https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Examples/Example22-Tabs/Example-Tabs01.html#L1116-L1120

**Comment by PrzemyslawKlys** [comment]
In this example expanding the table with blue plus doesn't work because it's "gone".

**Comment by opustecnica** [comment]
I see.  Is the goal to have the table refreshed only when displayed either via tab or "collapsed" section?

**Comment by PrzemyslawKlys** [comment]
For section it needs to be aware what tables are below it. So if there is a switch that allows collapse and it starts hidden aka collapsed it needs to recalculate table or tables within that section... unless there are multiple sections collapsed within that section. For tab its similar. When you click on a tab it needs to be aware which tab you clicked and find all tables that are now supposed to be visible and recalculate them...

**Comment by PrzemyslawKlys** [comment]
With nested tabs it geta a bit more complicated.

**Comment by opustecnica** [comment]
Przemyslaw,

I believe I have found a solution to our problem.  Depending on table-size and whether or not multiple tables are present, in order to achieve max performance, HTMLSections  might be advisable.
We should also introduce switches to allow users to decide about any recalc operation.

Case 1: Multiple TABs with 1 table per TAB.  On tab switch the recalc is executed only on the table shown in the TAB.  
Case 2: Multiple TABs with multiple tables per TAB.  If the tables are large, I would suggest turning off the recalc on TAB selection and encapsulating tables in HTMLSections.  On show, the DataTables recalc is executed only on the table/s within the affected HTMLSection.  If the table are small, the penalty might be negligible and we can just recalc the entire content of the tab.

I  am running into an issue with the TABs portion.  The code assigns the same id (e.g. Tab-8i2ku3os) to two different DIV tags.  One for the TABs menu, and one for the tab content.  The latter needs to be modified to be unique (e.g. Tab-8i2ku3os-CNT).  This uniqueness allows us to extract the datatable ids specific to that tab.  Do you happen to remember where this is is assigned?

**Comment by PrzemyslawKlys** [comment]
The code for tabs is pretty messy. We need to treat both cases (section/tabs) separately. 

1. We can't demand from users to use Sections - as it's up to them
2. We should disable recalc in a way it's currently done. THere's no question about it. The way it works now is unacceptable. It basically finds all data tables and recalcs which doesn't make any sense. 
3. The fix for this is to recalc as you said only tables that are within the tab. Regardless if it's 5 tables, 50 tables you need to recalc all visible tables. 

--- 
1. You have 2 Tabs
2. You load HTML with 1st tab open
3. You only load those tables on tab 1. Tab 2 isn't loading content. 
4. When you switch tab - you basically need a code which either knows which tables are on that tab and simply forces recalc (that's pretty easy to do with PowerShell as you can track it and create JS code for that with hardcoded information). Things get complicated if you want to actually detect currently visible tables only (consider having collapsed sections on that tab).
5. Nested tabs complicate it a bit because when you press on the top tab you now have 2 or more nested tabs and you need to know which one is currently open and get that information. 

---
As for your idea - I am not sure if that's a fix/solution. My understanding was/is that I'm using same ID tag because it needs to know which ID I'm pressing. But maybe that was the wrong assumption on my end. 

Feel free to explore :-) I'm even considering to pay a bounty to some magician of JS code to fix it globally for this project. 


Below are all places where it's actually used in one way or another. 

https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Public/New-HTMLTab.ps1#L143-L173

https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Public/New-HTMLTab.ps1#L114-L121


https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Public/New-HTMLTab.ps1#L172-L173


https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Public/New-HTML.ps1#L49-L55


https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Public/New-HTML.ps1#L86-L90


https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Public/New-HTML.ps1#L20-L21


https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Public/New-HTML.ps1#L160-L166


https://github.com/EvotecIT/PSWriteHTML/blob/5bdb41bae9e3e0bf7a00bcf71d337e5f8dec9558/Private/New-HTMLTabHead.ps1#L1-L59

**Comment by PrzemyslawKlys** [comment]
So to fix it the way you want you would need to add to $Tab.AnotherID ...and then in New-HTMLTabHead simply use that AnotherID.

**Comment by opustecnica** [comment]
I am definitely no JS Jedi, but I believe this should be fixed in JS (vs PowerShell).  Once the code is created by PowerShell, any UI related work should be done in JS for user experience sake.  Yes, if we could get a JS guru it would be awesome and likely produce nice results. :-)

**Comment by PrzemyslawKlys** [comment]
Well, you can play with it if you want. The way I see it is that when you create new table (in PowerShell) you can check which tab you're currently on and simply create reference to that table in the $Script:HTMLSchema. Once you're building New-HTMLTabHead you simply would need to add JS code that would have hardcoded recalc of those tables linked to particular tab. THis should be fairly easy to to do if no nested tabs are there. 

I am also thinking - Lazy Loading... I see this on websites and maybe it's something that would improve performance.

**Comment by opustecnica** [comment]
PR 105

**Comment by PrzemyslawKlys** [comment]
I'm not closing this one until we're sure we've done all we could in this matter. Tnx for #105

**Comment by PrzemyslawKlys** [comment]
It seems your change did something:

![image](https://user-images.githubusercontent.com/15063294/73098544-eba54380-3ee9-11ea-9749-ee613cd24cab.png)


```
        try {
            if (localStorage.getItem('tabbis') === null) return;
            if (localStorage.getItem('tabbis').length == 0) return;

            memory = Object.values(JSON.parse(localStorage.getItem('tabbis')));
        } catch (e) {
            console.log('Tabs local storage failed. Most likely IE in use.')
        }
```

This is coming from this. Not sure why would it complain tho

**Comment by PrzemyslawKlys** [comment]
Never mind. I think it's coming from Edge Chromium and my local storage. Can't reproduce it in Chrome which I don't use.

**Comment by PrzemyslawKlys** [comment]
I think we can close this one. Perf seems to be ok. Thank you again.
