### ISSUE TITLE
RGBColors Hash Scope

### ISSUE THREAD

**Issue by opustecnica** [EvotecIT/PSWriteHTML#104]
The module uses an ordered hash (```$RGBColors```) to store colors' name/value pairs.  This is, properly, script/module scoped.  At times, it is useful to access the list of colors from a script in order to populate the ```-color``` parameters of functions like ```New-ChartLegend``` (e.g. pull 10 random colors to populate a legend).
This can be achieved by either adding the```$RGBColors``` variable to the ```Export-ModuleMember``` OR creating a purposeful public function to export the hash.  The latter has the added advantage of avoiding potential variable collisions.  How should we proceed?

**Comment by PrzemyslawKlys** [comment]
In PSSharedGoods there is a function `Get-Colors`. It has the same ordered hash. Not sure what to do really. I understand your point. In theory, we could expose variables as global and make sure the name is pretty unique to PSWriteHTML.

**Comment by PrzemyslawKlys** [comment]
Do you still need it?

**Comment by opustecnica** [comment]
Przemyslaw,

I do use it and have come up with a minor mod I do to my local copy of the module.  Not sure if this is something useful to the community.  I'll share and if useful we can add it to the module.

As far as I am concerned, at least this is my use of it, this is only useful when generating graphs with an unknown/variable number of elements AND a desire to "randomize" the color selection.

PS A while ago, while mentioning your module, I attempted to to pronounce your name in presence of a native Polish speaker.  I believe she is still laughing :-(.

**Comment by PrzemyslawKlys** [comment]
I'm more than happy to accept anything that helps users build their HTML content. There are many things that have very small use cases, yet they are there ;-) 

As for my name - I don't mind my name when it's spelled wrong. I usually tell people to call me "shemek", "schemek" and it makes things a bit easier for them to talk to me. Przemyslaw is my official name but I use Przemek on a daily basis and "shemek" is the way to tell it without much effort ;) Worst case scenario I tell them to call me Adam which is my 2nd name. I probably can't spell your name either, nor can I spell most names that are not Polish so I really don't take any offense.
