### ISSUE TITLE
how can i save to html ?!

### ISSUE THREAD

**Issue by fene18** [EvotecIT/PSWriteHTML#110]
Save-HTML -FilePath "$PSScriptRoot\DailySummary" -Encoding Ascii 

cmdlet Save-HTML at command pipeline position 2
Supply values for the following parameters:
HTML[0]: 

What`s wrong here ? :)) I can`t seem to find any example for the Save command

**Comment by PrzemyslawKlys** [comment]
Can you show example on what you’re doing? There is most likely no reason to use Save-html.

**Comment by PrzemyslawKlys** [comment]
Closing as no reason provided. Feel free to provide one and I'll reopen.

**Comment by fene18** [comment]
Aim would be to save it to HTML in order to be able to send it via mail. If i`m being honest i did not have the patience to study how the mail part works :)

**Comment by PrzemyslawKlys** [comment]
1. https://evotec.xyz/meet-emailimo-new-way-to-send-pretty-emails-with-powershell/
2. https://evotec.xyz/sending-html-emails-with-powershell-and-zero-html-knowledge-required/

There is no need to save anything if you're using only PSWriteHTML and it's Emailimo part (it's now integrated so no need for the separate module). 

```powershell
$Disks = Get-WmiObject win32_logicaldisk -filter "DriveType='3'"
$FormattedDisk = foreach ($disk in $disks) {
    [PSCustomObject] @{
        'Volume' = $disk.DeviceID
        'Total Space'      = "$($disk.Size / 1GB -as [int]) GB"
        'Free Space' = "$($disk.FreeSpace / 1GB -as [int]) GB"
        'Percent Full' = "$([math]::Round((1 - ($freeSpaceGB / $sizeGB)) * 100))%"
    }
}
Email {
    EmailFrom -Address 'reminder@domain.pl'
    EmailTo -Addresses "przemyslaw.klys@domain.pl"
    EmailCC -Addresses "przemyslaw.klys@domain.pl"
    EmailBCC -Addresses "kontakt@domain.pl"
    EmailServer -Server 'mail.domain.pl' -UserName 'UserName' -Password 'C:\Support\Important\Password-Evotec-Reminder.txt' -PasswordAsSecure -PasswordFromFile
    EmailOptions -Priority Low
    EmailSubject -Subject 'This is a test email'
    
    EmailBody -FontFamily 'Calibri' -Size 15 {
        EmailText -Text 'Server Space Report' -FontWeight bold -Color Grey -LineBreak
        EmailTable -DataTable $FormattedDisk -HideFooter
        EmailText -LineBreak
        EmailTable -DataTable $Disks -HideFooter
    }
}
```

That's it. THere's no save necessary. You can also use -FilePath for the Email if you want to save the HTML to disk. The same principle applies to New-HTML -FilePath { YourContent } and it will save that HTML to disk. 

The `save-HTML` is built-in into `New-HTML` and `Email` commands. You can use `Save-HTML` only if you skip -FilePath for New-HTML

```powershell
$HTML = New-HTML {

}
Save-HTML -HTML $HTML -FilePath ...
```

But it's not really necessary or makes sense. You should read articles for PSWriteHTML to understand concepts: https://evotec.xyz/?s=pswritehtml

**Comment by fene18** [comment]
sooner or later i`ll have to go trough them :) Thanks for the details i`ll give it a try.
