### ISSUE TITLE
Disable Search in Tables

### ISSUE THREAD

**Issue by whoot** [EvotecIT/PSWriteHTML#112]
Hey,

is it possible to disable the search field in tables, too? I just found something about disabling th buttons, but the search field stays.

Thanks

**Comment by PrzemyslawKlys** [comment]
Kind of obvious `-DisableSearch` :-) 

```
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter { #-ImmediatelyShowHiddenDetails
            New-TableRowGrouping -Name 'PriorityClass' -Color Red -BackgroundColor GreenYellow
        } -DisableSearch
```

**Comment by whoot** [comment]
lol.. thanks a lot!
I tried stuff like "-Search @()", "-Search $False" and "-HideSearch" -.-

**Comment by PrzemyslawKlys** [comment]
https://github.com/EvotecIT/PSWriteHTML/blob/master/Docs/New-HTMLTable.md - all options (i think it's up to date).
