### ISSUE TITLE
HTMLDiagram keeps expanding without height

### ISSUE THREAD

**Issue by whoot** [EvotecIT/PSWriteHTML#113]
I just found a funny bug. Instead of using the maximum height of a Section for the diagram, the diagram keeps expanding when not specifying the height.

Example:
```bash
Dashboard -Name 'Test' -UseCssLinks:$true -UseJavaScriptLinks:$true -FilePath $PSScriptRoot\test.html -Show {
	Tab -Name 'Test' {
		Section -Name "Test" {
			New-HTMLDiagram {
				New-DiagramOptionsPhysics -Enabled $false
				New-DiagramOptionsInteraction -Hover $true
				
				New-DiagramNode -Label "test1" -ColorBackground Black -FontColor White -Shape box
				New-DiagramNode -Label "test2" -ColorBackground Black -FontColor White -Shape box

				New-DiagramLink -From "test1" -To "test2" -ArrowsFromEnabled $true -ArrowsToEnabled $true
			}
		}
	}
}
```

**Comment by PrzemyslawKlys** [comment]
What does it mean to keep expanding? I don't see anything wrong with that HTML?

**Comment by PrzemyslawKlys** [comment]
https://github.com/EvotecIT/PSWriteHTML/blob/master/Docs/New-HTMLTable.md - all options (i think it's up to date).

**Comment by whoot** [comment]
> 
> 
> What does it mean to keep expanding? I don't see anything wrong with that HTML?

Try it yourself. The Diagram (its not a table) keep getting bigger and bigger

**Comment by PrzemyslawKlys** [comment]
![I did try](https://user-images.githubusercontent.com/15063294/74557027-92b45280-4f5f-11ea-92ad-763721969063.gif)

I did try it - that's why I said nothing wrong with it.

**Comment by whoot** [comment]
weird.. what browser did you use? Im on the current firefox (73.0)

**Comment by PrzemyslawKlys** [comment]
Chrome / Edge. But just tested in firefox 70, closed it, updated to 72, closed it updated to 73 and it still works.

**Comment by PrzemyslawKlys** [comment]
Ok, i see what you mean now.

**Comment by PrzemyslawKlys** [comment]
But i would say something changed in 73.

Here's what it's like in 70.

![Firefox](https://user-images.githubusercontent.com/15063294/74557469-7fee4d80-4f60-11ea-8f75-a6c78bdb85b1.gif)

**Comment by PrzemyslawKlys** [comment]
I'll play with it when I get some time. Not a priority tho

**Comment by whoot** [comment]
Nah, as you can see 70 is also affected. The section box itself keeps expanding.
You can even see it in the gif

**Comment by PrzemyslawKlys** [comment]
It expands because I press F5. In Firefox 73 and IE iit autoexpands by just waiting.

**Comment by PrzemyslawKlys** [comment]
Anyways, it's a bug. Thanks for reporting. Probably need to update Vis.js to new version and test.

**Comment by whoot** [comment]
> 
> 
> It expands because I press F5. In Firefox 73 and IE it auto expands by just waiting.

Exactly. Thats what i meant.

**Comment by PrzemyslawKlys** [comment]
Feel free to try and tackle it ;) It's just a matter of playing a lot with new Visjs and seeing if it fixes this issue or not :)
