### ISSUE TITLE
Font size of Content Header Text and -DataTable

### ISSUE THREAD

**Issue by varunaggar** [EvotecIT/PSWriteHTML#116]
Hi all,

Is it possible to change the font size of the HeaderText in New-HTMLContent and similarly the font size of input object of -DataTable parameter ?

any thoughts would be of great help.

Varun

**Comment by PrzemyslawKlys** [comment]
I would say we need to expand New-HTMLSection (New-HTMLContent is alias). Work is needed to build it up.

**Comment by xlrod** [comment]
Added a parameter for `$HeaderTextSize` and was also playing around with the text shadow, not sure if you'd like to add it.

![image](https://user-images.githubusercontent.com/48139416/78468045-7e7c0e80-76e1-11ea-980e-80eb30adf33f.png)
![image](https://user-images.githubusercontent.com/48139416/78468057-8cca2a80-76e1-11ea-935d-363ea2315e9b.png)
![image](https://user-images.githubusercontent.com/48139416/78468092-03672800-76e2-11ea-9d5b-ee4c4b24fc87.png)


    New-HTMLSection -HeaderText "Title goes here" -HeaderTextSize 12 -HeaderTextShadowOffsetX -2 -HeaderTextShadowOffsetY 1 -HeaderTextShadowBlur 20 -Content {...}

![image](https://user-images.githubusercontent.com/48139416/78468083-e2063c00-76e1-11ea-99fd-6aa98be82fef.png)

**Comment by PrzemyslawKlys** [comment]
Sure, more features and options the better ;-) We could also play with text-transform and add validateset different options. I believe this could be useful. Also if there is font size, there should be option for font name.

**Comment by PrzemyslawKlys** [comment]
Text-Transform possible options:

- lowercase: makes all of the letters in the selected text lowercase.
- uppercase: makes all of the letters in the selected text uppercase or ALL CAPS.
- capitalize: capitalizes the first letter of each word in the selected text.
- none: leaves the text's case and capitalization exactly as it was entered.
- inherit: gives the text the case and capitalization of its parent.
- full-width: Is a keyword forcing the writing of a character (mainly ideograms and latin scripts) inside a square, allowing them to be aligned in the usual East Asian scripts.

**Comment by PrzemyslawKlys** [comment]
@xlrod did you ever submit your changes?

**Comment by xlrod** [comment]
@PrzemyslawKlys No, I didn't submit the changes as they were still not fully functional. I'll get the latest version and start working from there again.

**Comment by tomerikko** [comment]
would love to see that implemented.

BTW, new user to your module @PrzemyslawKlys - its awesome!!!! thanks for all the hard work you put into this.

**Comment by PrzemyslawKlys** [comment]
@tomerikko HeaderTextSize is implemented in 0.0.133

- 0.0.133
  - [x] Library
    - [x] Updated DataTables ColReorder 1.5.2 -> 1.5.3
    - [x] Updated DataTables FixedColumns 3.3.1 -> 3.3.2
    - [x] Updated DataTables FixedHeader 3.1.7 -> 3.1.8
    - [x] Updated DataTables 1.10.22 -> 1.10.23
    - [x] Updated DataTables KeyTable 2.5.3 -> 2.6.0
    - [x] Updated DataTables Responsive 2.2.6 -> 2.2.7
    - [x] Added `DataTables SearchBuilder` 1.0.1
    - [x] Updated DataTables SearchPanes 1.2.1 -> 1.2.2
    - [x] Updated FancyTree `2.33` -> `2.38`
    - [x] Updated JustGage `1.4.0` -> `1.4.1`
    - [x] Updated FullCalendar `5.1.0 -> 5.5.1`
    - [x] Added DataTables Search Alphabet `1.0.0 with personal PR`
    - [x] Updated `OrgChart` from `2.2.0` to `3.1.0`, `3.1.1`
    - [x] Updated `VisData` from `7.1.1` to `7.1.2`
    - [x] Updated `VisNetwork` from `8.5.5` to `9.0.2`
    - [x] Updated `VisTimeline` from `7.4.2` to `7.4.6`
    - [x] Updated `EasyQrCode` from `4.3.0` to `4.3.2`
    - [x] Added `DataTables Select` -> `1.3.1`
  - [x] Added ability `OverwriteDOM` in `New-HTMLTable` to provide granular option how options are visually positioned
  - [x] Added ability `SearchBuilder` in `New-HTMLTable` for multi-condition search
  - [x] Added ability `SearchHighlight` in `New-HTMLTable`
  - [x] Added ability `AlphabetSearch` in `New-HTMLTable`
  - [x] Fixes `New-ChartLegend` hex colors but most likely all other cmdlets where more than one HEX based color was used
  - [x] Added `HeaderTextSize` to `New-HTMLSection`
  - [x] Added `New-TablePercentageBar` for `New-HTMLTable`
  - [x] Added `New-ChartEvent`
  - [x] Fixed `New-HTMLTable -DataStore JavaScript` when dollar ($) is used within column name or content
  - [x] Improved `New-HTMLTableOption` added `ArrayJoin`,`ArrayJoinString`

The rest of the  settings are not, but I was thinking on totally rebuilding section with support for icons and better customization options. It's too bad @xlrod  didn't submit it back then :-)

**Comment by tomerikko** [comment]
sweet, i am on 0.0.132, so will push an upgrade and check again.
Thanks!

**Comment by PrzemyslawKlys** [comment]
Its not yet out as i am fixing outstanding issues.
