### ISSUE TITLE
EmailTable size isn't set to contents

### ISSUE THREAD

**Issue by Gnardar** [EvotecIT/PSWriteHTML#117]
When using EmailTable the html table is expanding to the full size of the window, not autosizing to the content. Happens in -AttachSelf file, Outlook, and GMail

Example Code:

```powershell
$processes = get-process | Select Name, Id -first 5
Email -AttachSelf {
    EmailHeader {
         EMAILSETTINGS
    }
    EmailBody {
        EmailTextBox {
            STRING CONTENT
        }
        EmailText -LineBreak
        EmailText -LineBreak
        EmailTextBox {
            MORE CONTENT
            ""
        }
        EmailTable -Table $processes -HideFooter
    }

}
```

![image](https://user-images.githubusercontent.com/12664843/77452591-04e54600-6dee-11ea-9715-deaecbf66770.png)

**Comment by PrzemyslawKlys** [comment]
Added -AutoSize to New-HTMLTable/EmailTable. This makes it fit the content rather than using 100% width for the table.
