### ISSUE TITLE
New-HTMLTable.ps1 parameter for export file name

### ISSUE THREAD

**Issue by simosuu** [EvotecIT/PSWriteHTML#121]
Add title attribute here so we can have file name for excel, csv and pdf exports. Default migh be something like "Data_Export" if not specified.

`  if ($button -ne 'pdfHtml5') {
                        @{
                            extend = $button
			    title 		= $filename
                        }
                    } else {
                        @{
                            extend      = 'pdfHtml5'
                            pageSize    = 'A3'
                            orientation = 'landscape'
			    title 		= $filename
                        }`

**Comment by PrzemyslawKlys** [comment]
`Out-HtmlView` has Title. Probably we should add one as well for `New-HTMLTable`

**Comment by PrzemyslawKlys** [comment]
`TitleText` is already there on New-HTML and that's what taken for the title of the exported file.

**Comment by simosuu** [comment]
Excellent, thank you. That worked just lack of documentation maybe.

**Comment by PrzemyslawKlys** [comment]
I think we should keep this open and fix it for table. Once you have multiple tables on a page it would be beneficial to have different title and therefore different file name per table (if possible). 

As for lack of documentation... I'm open for PR's :-) Or blog posts about PSWriteHTML. Unfortunately I have limited resources to fix all by myself.

**Comment by PrzemyslawKlys** [comment]
The published new version which makes -Title available per New-HTMLTable or even per button.
