### ISSUE TITLE
Sorting by clicking html table output header is not working for date formated values/rows

### ISSUE THREAD

**Issue by wpiotrw** [EvotecIT/PSWriteHTML#124]
Hello

After creating html output via dashimo/ pswritehtml there are a lot of tabs visible . (For instance for M365 service health dashboard)

Data can be sorted by clicking column headers. Unfortunately for rows containing Dates - sorting is not properly working. Descending/Ascending does not lead to the correct order.

Piotr

**Comment by PrzemyslawKlys** [comment]
You need to use New-HTMLTable with DateTimeSortingFormat. Take a look here: https://github.com/EvotecIT/PSWriteHTML/issues/18

**Comment by wpiotrw** [comment]
Thanks

I used the code from
https://www.google.co.uk/amp/s/evotec.xyz/powershell-way-to-get-all-information-about-office-365-service-health/amp/

So for example

Dashboard -FilePath $PSScriptRoot\Health.html {
    Tab -Name 'Services' {
        Section -Invisible {
            Section -Name 'Service List' {
                Table -DataTable $O365.Services
            }
            Section -Name 'Service & Feature List' {
                Table -DataTable $O365.ServicesExtended

U mean changing “Table “ to New-HTMLTable with DateTimeSortingFormat???

Thanks

**Comment by PrzemyslawKlys** [comment]
I mean Table -DateTimeSortingFormat. Table is alias for New-HTMLTable but you need to give DateTimeSortingFormat parameter and provide proper parameter.

**Comment by wpiotrw** [comment]
Thank you for your prompt answer. 
I will give it a try

Btw: great stuff!!!

**Comment by PrzemyslawKlys** [comment]
Closing, assuming it's closed.
