### ISSUE TITLE
How to limit tabs per row? 

### ISSUE THREAD

**Issue by wpiotrw** [EvotecIT/PSWriteHTML#130]
Hello

How to limit tabs per row when using TABLE -DATATABLE xxx?

As per below screenshot, I would like to put Xnumber of column headers in 1s row and Ynumber of colums headers in row below

![obraz](https://user-images.githubusercontent.com/37083541/83629537-90234a80-a59a-11ea-94f1-41a710befa12.png)

It is someting to be implemented or there is a possibility by utilising current code?

Piotr

**Comment by PrzemyslawKlys** [comment]
You can do nested tabs. You can't control how many tabs will appear in 1st row as it will scale for display purposes. But if you put 5 tabs at first row you can assign another 5 tabs under some tab in 1st row.

**Comment by PrzemyslawKlys** [comment]
Here's article about it: https://evotec.xyz/nested-tabs-diagram-updates-diagram-events-calendar-object-and-more-in-pswritehtml/

**Comment by PrzemyslawKlys** [comment]
Does this answer your question or you still need some help?

**Comment by wpiotrw** [comment]
Yep. Thanks
