### ISSUE TITLE
Missing Get-TemporaryDirectory function

### ISSUE THREAD

**Issue by FiRem00** [EvotecIT/PSWriteHTML#132]
Get-TemporaryDirectory : The term 'Get-TemporaryDirectory' is not recognized as the name of a cmdlet, function, script
file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct
and try again.
At C:\Program Files\WindowsPowerShell\Modules\PSWriteHTML\0.0.85\PSWriteHTML.psm1:6582 char:32
+             $TempFilePath = "$(Get-TemporaryDirectory)\$($AttachSelfN ...
+                                ~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Get-TemporaryDirectory:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by PrzemyslawKlys** [comment]
Thank you for reporting this. It seems my merge function for some weird reason is skipping this function. Will fix it today. Need to check why merging process doesn't work correctly. 

You can do Install-Module PSSharedGoods in the meantime if you want to have it working now.

**Comment by PrzemyslawKlys** [comment]
Update-Module PSWriteHTML should fix it.
