### ISSUE TITLE
Tabs switching with multiple tables on each tab fails

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWriteHTML#134]
Hi @opustecnica,

I think we didn't fix it - your query selector only finds first value and uses that, but it doesn't work for all data tables that are visible, so it fails on all other tables. 

https://github.com/EvotecIT/PSWriteHTML/blob/cf40b03e2e2e7cec563e614c0c33bb3a53736415/Resources/JS/tabbisAdditional.js#L13-L20

It's easy to reproduce:

https://github.com/EvotecIT/PSWriteHTML/blob/dd63ea471cf291c86c83449c6183072b58875506/Examples/Example-DashimoStyle/Run-EasyDashboard.ps1#L1-L36

**Comment by PrzemyslawKlys** [comment]
I think I fixed it.

https://github.com/EvotecIT/PSWriteHTML/blob/d87dbd1afae132799ca29ce463def972fa9541d6/Resources/JS/tabbisAdditional.js#L1-L34

This should do the trick

**Comment by opustecnica** [comment]
Just saw this.  I have a few work related items that need addressing immediately and I will check on the solution.

**Comment by smasterson** [comment]
Excellent work! Seems to be loading correctly now :-)
Is it possible to add timeGridWeek to the InitialView options?

On the downside it appears tooltips (description) is no longer working :-(

Can't thank you enough for the effort you put in on this entire project!

**Comment by PrzemyslawKlys** [comment]
I'm pretty confident I fixed it :-) But do verify ;-)
