### ISSUE TITLE
How to limit tabs per row - continuation? 

### ISSUE THREAD

**Issue by wpiotrw** [EvotecIT/PSWriteHTML#136]
I have just reviewd the given url. It is not exactly what i would like to have.
Proposed solution shows NESTED tabs. So for example one tab is to be cliked to show tabes below (nested)

And i would like to have have NON-NESTED tabs, for instance
- 5 tabs in 1st row
- 6 tabs in 2nd row

all visible at once. 

Something like

![obraz](https://user-images.githubusercontent.com/37083541/88147660-d3468500-cbfd-11ea-8984-478d1d51d04a.png)

Then i could code nested for them.
 
-

_Originally posted by @wpiotrw in https://github.com/EvotecIT/PSWriteHTML/issues/130#issuecomment-661745077_

**Comment by PrzemyslawKlys** [comment]
Currently, it's not possible to control this. It should be possible to get it automatically resize based on screen size (not a user decision), but having it directly "counted" tabs is a bit of my knowledge scope. 

We could ask @jenstornell as the tab solution is his MIT project https://github.com/jenstornell/

We're using a bit older version that supports IE  so we cant' even use his newest version - and I guess if he would be willing to add it as a feature he would like it to be in V3 only.

**Comment by jenstornell** [comment]
@PrzemyslawKlys No, I will not continue the old version of the script. Sorry.

**Comment by PrzemyslawKlys** [comment]
This is all you will get:

![image](https://user-images.githubusercontent.com/15063294/90504265-1d654c80-e151-11ea-8c41-74e376dae1d4.png)

By default it will now wrap things up and it will try to do whatever it thinks is best. You can also use New-HTMLTabOption -RowElements <int> to force it to display less/more but it won't work per row and if it can't fit things it won't. 

I've also added a bunch of options such as Wrap/Direction and other stuff to New-HTMLTabOption. Feel free to work with it.

```powershell
Import-Module $PSScriptRoot\..\..\PSWriteHTML.psd1 -Force

New-HTML -TitleText 'My title' -Online -FilePath $PSScriptRoot\Example-Tabs07.html -Show {
    #New-HTMLTabOption -SlimTabs         -BorderBottomStyleActive solid -BorderBottomColorActive LightSkyBlue -BackgroundColorActive none         -TextColorActive Black -Align left -BorderRadius 0px -RemoveShadow -TextColor Grey -TextTransform capitalize
    #New-HTMLTabOption -Wrap wrap-reverse -Direction row-reverse
    New-HTMLTabOption -RowElements 4
    New-HTMLTab -Name 'First Level Tab - Test 1' -IconBrands acquisitions-incorporated {
        New-HTMLTab -Name '2nd Level Tab - Test 4/1' -IconBrands app-store {
            New-HTMLSection {

            }
            #New-HTMLTable -DataTable $Test1 -HideFooter {
            #    New-HTMLTableHeader -Names 'ID', 'HandleCount'
            #}
        }
        New-HTMLTab -Name '2nd Level Tab - Test 4/2' {
            #New-HTMLTable -DataTable $Test1 -HideFooter {
            #    New-HTMLTableHeader -Names 'ID', 'HandleCount' -Title 'Test'
            #}
            New-HTMLSection {

            }
        }
    }
    New-HTMLTab -Name 'First Level Tab - Test 4' -IconSolid bezier-curve {

    }
    New-HTMLTab -Name 'First Level Tab - Test 4' -IconSolid bezier-curve {

    }
    New-HTMLTab {

    }
    New-HTMLTab {

    }
    New-HTMLTab {

    }
    New-HTMLTab {

    }
    New-HTMLTab {

    }
    New-HTMLTab {

    }
    New-HTMLTab {

    }
    New-HTMLTab {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
    New-HTMLTab -Name 'ThisIsVeryLongTitleButWithoutSpacesWhichMayBeProblematic' {

    }
}
```
