### ISSUE TITLE
Separate HTML files per TAB

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWriteHTML#139]
I think it would be a good idea to offer this as an option where a separate file is linked to a new Tab or potentially to other areas (but not yet sure where). While it makes sense to keep everything in one HTML file for portability for some cases it gets really performance intensive when a lot of things are stored. 

I once had Active Directory export of 500MB HTML file. It was killing my browser.

**Comment by DonDom86** [comment]
Hi,

sorry for the question.
In what example can I look at the use of this improvement?

Best regards

**Comment by PrzemyslawKlys** [comment]
There are new features added. One of those is shown here:
- https://github.com/EvotecIT/PSWriteHTML/blob/master/Examples/Example41-Navigation02/Example41-Navigation02.ps1

There are 3 others in examples. While it's not about tabs it's about pages attached to menus.

**Comment by DonDom86** [comment]
Thank you.
Have to improve the testimo result report.
a lot of DCs al lot of tests :-)
Or do you have a advanced report with better performance :-)

Thank you

**Comment by PrzemyslawKlys** [comment]
I use another project that solves that. The idea is that you run Testimo reports, report by report and the "TheDashboard" bundles it all up. Each HTML separately.

![image](https://user-images.githubusercontent.com/15063294/188234218-81c7ed12-0cee-438f-b833-2ab97fe8cfd5.png)

**Comment by DonDom86** [comment]
Is this Project public too?

**Comment by PrzemyslawKlys** [comment]
Not yet. I have some trouble on making it easy to use and configurable at the same time

**Comment by DonDom86** [comment]
Thanks. Have done my one top menu site.
If you click on an menu item and the page is changing the menu and is flickering.
Is that "normal"?

**Comment by DonDom86** [comment]
> Not yet. I have some trouble on making it easy to use and configurable at the same time

Insperierd from your screenshot I wrote a few functions. They create on the basis of an existing folder/filestrutkur independently the appropriate navigation menu. It certainly doesn't cover all configuration possibilities PSWritehtml offers - but hey zero config is needed. Are you interested? Should I send them via mail to you?

**Comment by PrzemyslawKlys** [comment]
That's already what the dashboard does 

```powershell
$Configuration = @{
    HTMLPath       = "$PSScriptRoot\Reports\Index.html"
    ExcelPath      = "$PSScriptRoot\ReportExcel.xlsx"
    StatisticsPath = "$PSScriptRoot\Dashboard.xml"
    Logo           = 'https://evotec.xyz/wp-content/uploads/2021/04/Logo-evotec-bb.png'
    Limits         = [ordered] @{
        Users         = 200
        Computers     = 200
        Groups        = 200
        GroupPolicies = 100
    }
    Folders        = [ordered] @{
        GPOZaurr           = @{
            Path               = "$PSScriptRoot\Reports\GPOZaurr"
            Url                = "GPOzaurr"
            IconType           = 'IconBrands'
            Icon               = 'gofore'
            ReplacementsGlobal = $true
        }
        Testimo            = @{
            Path               = "$PSScriptRoot\Reports\Testimo"
            Url                = "Testimo"
            IconType           = 'IconBrands'
            Icon               = 'adversal'
            ReplacementsGlobal = $true
        }
        'Group Membership' = @{
            Path               = "$PSScriptRoot\Reports\GroupMembership"
            Url                = "GroupMembership"
            IconType           = 'IconSolid'
            Icon               = 'chalkboard-teacher'
            ReplacementsGlobal = $true
        }
        'Custom Reports'   = @{
            Path               = "$PSScriptRoot\Reports\CustomReports"
            Url                = "CustomReports"
            IconType           = 'IconSolid'
            Icon               = 'chalkboard-teacher'
            ReplacementsGlobal = $true
        }
        'PingCastle'       = @{
            Path               = "$PSScriptRoot\Reports\PingCastle"
            Url                = "PingCastle"
            IconType           = 'IconSolid'
            Icon               = 'podcast'
            ReplacementsGlobal = $false
            Replacements       = [ordered] @{
                SplitOn        = '_'
                BeforeSplit    = [ordered] @{
                    '-Domain-' = ' '
                }
                AfterSplit     = [ordered] @{

                }
                AddSpaceToName = $false
            }
        }
    }
    Replacements   = [ordered] @{
        SplitOn        = '_'
        BeforeSplit    = [ordered] @{
            'Testimo'          = ''
            'GPOZaurr'         = ''
            'GroupMembership-' = ''
            '_Regional'        = ' Regional'
            'PingCastle-'      = ''
        }
        AfterSplit     = [ordered] @{
            'G P O'     = 'GPO'
            'L D A P'   = 'LDAP'
            'L A P S'   = 'LAPS'
            'K R B G T' = 'KRBGT'
            'A D'       = 'AD'
            'I T R X X' = 'ITRXX'
            'I N S'     = 'INS'
        }
        AddSpaceToName = $true
    }
}
```

This is what the configuration looks like. The problems I'm struggling with are more dependent on the dashboard itself and mainly about the graphs, that I want to be dynamic. So some command that creates either chart or some other stuff. I 've some vision on how it's supposed to look, just not yet fully crystalized.

**Comment by DonDom86** [comment]
Ok also nice... my idea is: run different reports, copy the html to a directory/filestructure, run my module "report-master" gibe it "input directory" and have one dashboard :-) at the moment I have done some changes on your testimo module... now I can execute it once and get a nice and "mostly" smooth running webpage which shows all 7100 tests of my environment  :-)

thanks to your modules i actually don't need html knowledge :-)

I am looking forward to seeing your report generator.
Until then I will have to use mine.

**Comment by PrzemyslawKlys** [comment]
That is how the dashboard works. The dashboard just takes existing HTML reports from GPOZaurr/Testimo and other HTML reports and exposes them via the dashboard, including history reports based on filenames or dates and exposes them in calendar and in the GUI and also does some tricks to display them nicely. 

The tools that generate reports run on schedule on different days and are completely independent. I will release TheDashboard soon enough, as I have to finish writing docs for setting it up on IIS.

**Comment by DonDom86** [comment]
that's exactly how i do it at the moment :-)
do you know or have a good dashboard for an exchange environment?

**Comment by PrzemyslawKlys** [comment]
https://microsoft.github.io/CSS-Exchange/Diagnostics/HealthChecker/ but i've not tested it myself, haven't played with Exchange for a while

**Comment by DonDom86** [comment]
i´m still very interested in your solution :-)

My own solution is now also a bit advanced. 

Some features:
- Scanning and copying source directories
- Determine whether new files have been created in the source directories -> if so, the Top-Menu-Sites must be created again.

The menu is created based on the Directory/FileStructure - no flat structure, every directory creates a new sub-menu.

I have already created Wrapper / Executer for you Modules:
- GPOZaurr (One page per Type)
- PSWinReporting (SubFolders for CurrentDay, PastWeek, PastMonth, PastQuarter,....)
- Testimo (Export your tabs to separated sites and create some own reports based of your provided informations)
- some Custom reports (LAPS, Policy-Based-DNS-Reports, Domain-Controller-Infos)

At the moment most of the reports are running too slow for a real realtime dashboard...
GPOZaurr: 1-2 hours
PSWinReporting: Events are collected on WEC: CurrentDay some minutes, PastWeek maybe 10 minutes, PastMonth 1 hour, PastQuarter no idea
Testimo: without SysVol-Verification about 4-8 hours, big environment bad connections
 Custom reports: mostly only some minutes... 

**Big open point:** How do you get all the information from the individual reports nicely and clearly presented on one overview page :-)

Apart from creating the top menu, my solution is just a best-of your examples. But its mostly working :-)
maybe we should do a little exchange of our betas :-P

Regards
Dominik

**Comment by PrzemyslawKlys** [comment]
Give me 1-2 weeks to finish my current stuff and so I can cleanit up and finalize my concepts. I run all reports from separately and dashboard can be rebuilt every 10 minutes if needed as it just reads "ready" data.

**Comment by DonDom86** [comment]
you get 4 weeks - I´m on holiday now :-)
don't worry! no hurry! my code is working but I need some quality loops :-)
