### ISSUE TITLE
Remove-EmptyValues function missing 

### ISSUE THREAD

**Issue by SumeshP** [EvotecIT/PSWriteHTML#142]
Remove-EmptyValues missing from module but is being used by many functions

Remove-EmptyValues : The term 'Remove-EmptyValues' is not recognized as the name of a cmdlet, function, script file,
or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and
try again.
At C:\GitHub\PSWriteHTML\Public\New-DiagramLink.ps1:87 char:5
+     Remove-EmptyValues -Hashtable $Object.Settings -Recursive
+     ~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Remove-EmptyValues:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException

**Comment by PrzemyslawKlys** [comment]
Install-Module PSSharedGoods

If you're developing you need to have multiple other modules of mine. If you're using PSGallery you just need PSWriteHTML as I'm merging everything in.
