### ISSUE TITLE
If ScrollY is selected the pdf button is doubled then

### ISSUE THREAD

**Issue by Jekastr** [EvotecIT/PSWriteHTML#154]
If ScrollY is selected the pdf button is doubled then.
Another thing I would like to point to is there is no paging button if ScrollY is selected. Yes I know this feature was removed intentionally but actually it was a good option even if you use it along with ScrollY.  I am missing it.

**Comment by PrzemyslawKlys** [comment]
Can you provide some sample code + screenshot for sake of having it? 

Do you mean this change?
- Improved New-HTMLTable - removed page button if DisablePaging or ScrollY is selected

What's the use case? How was it working? Maybe I made a mistake with my assumption on how it's working or not working in that case.

**Comment by Jekastr** [comment]
This is the piece of code that generated two PDF buttons
New-HTMLTable -DataTable $allAppsRep -Filtering -FilteringLocation bottom -DefaultSortIndex 0 -DefaultSortOrder Ascending -ScrollX -ScrollY -ScrollSizeY 300
![Capture](https://user-images.githubusercontent.com/68720978/95132397-b36b2b80-072d-11eb-83a8-426f94dc5285.PNG)

As for page button I figured out, there are New-TableButton... commands that can be used for button panel customizations 

BTW, thank you for your amazing module, I like it so much!

**Comment by PrzemyslawKlys** [comment]
To be honest, I don't understand the use case for paging - if I leave it on - nothing changes... when I switch the output. Can you elaborate what's your use case for ScrollY and Paging at the same time? 

I'm also considering implementing Scroller -> https://datatables.net/extensions/scroller/  -> https://datatables.net/extensions/scroller/examples/initialisation/simple.html - it could be useful for performance reasons. 

Problem with PDF x2 is fixed.
