### ISSUE TITLE
Email "UseDefaultCredentials"

### ISSUE THREAD

**Issue by nkronberg** [EvotecIT/PSWriteHTML#156]
Maybe this is just my lack of understanding, but when using Send-MailMessage it allows me to send through our authenticated mail relay, passing the credentials of the logged on user transparently.  Consequently, if I give permissions to a computer account in Active Directory to allow it to send emails, I can run a scheduled task as SYSTEM on that machine and it will send through the email relay just fine without having to enter the machine's password or encode it into a file or the script. (it's not an open relay).  I'm trying to replicate this behavior with PSWriteHTML's Email function.  I see a reference to "$Email.UseDefaultCredentials" in the module's code, but I'm not sure if this is what that is referring to.  Looking at the parameters available, I just don't see any way to use integrated authentication with this function.  Could you please clarify whether this is possible?  I prefer to send via 587/TLS.  Thank you!

**Comment by PrzemyslawKlys** [comment]
The property [UseDefaultCrededentials](https://docs.microsoft.com/en-us/dotnet/api/system.net.mail.smtpclient.usedefaultcredentials?view=netcore-3.1) is most likely what you want. This property is not available as part of Send-MailMessage, nor a few other things such as ReplyTo I believe. At least [StackOverflow](https://stackoverflow.com/questions/58067008/is-it-possible-to-use-send-mailmessage-with-default-credentials) has no answers. I am not sure if you really go thru the process of automatic authentication or it's just IP-based authentication. 

I'm curious what server is it and how is that set up? 

I'm considering enabling people to send emails via [Mailozaurr](https://github.com/EvotecIT/Mailozaurr) which is a replacement for **Send-MailMessage** since it's deprecated, along with **SMTP** that I use in **PSWriteHTML**. 

Having said that you don't have to rely on **PSWriteHTML** to send emails. Here's [an example](https://github.com/EvotecIT/Mailozaurr/blob/master/Examples/Example-SendEmail-02.ps1) way for you to utilize the power of **PSWriteHTML** and use **Mailozaurr** or any other SMTP client. 

Basically, you can utilize EmailBody outside of Email and get HTML out which you can pass to Send-MailMessage.

```powershell
$UserNotify = 'Przemyslaw'

$Body = EmailBody -FontFamily 'Calibri' -Size 15 {
    EmailText -Text 'Hello ', $UserNotify, ',' -Color None, Blue, None -Verbose -LineBreak
    EmailText -Text 'Your password is due to expire in ', $PasswordExpiryDays, 'days.' -Color None, Green, None
    EmailText -LineBreak
    EmailText -Text 'To change your password: '
    EmailText -Text '- press ', 'CTRL+ALT+DEL', ' -> ', 'Change a password...' -Color None, BlueViolet, None, Red
    EmailText -LineBreak
    EmailTextBox {
        'If you have forgotten your password and need to reset it, you can do this by clicking here. '
        'In case of problems please contact the HelpDesk by visiting [Evotec Website](https://evotec.xyz) or by sending an email to Help Desk.'
    }
    EmailText -LineBreak
    EmailText -Text 'Alternatively you can always call ', 'Help Desk', ' at ', '+48 22 00 00 00' `
        -Color None, LightSkyBlue, None, LightSkyBlue -TextDecoration none, underline, none, underline -FontWeight normal, bold, normal, bold
    EmailText -LineBreak
    EmailTextBox {
        'Kind regards,'
        'Evotec IT'
    }
}

if (-not $MailCredentials) {
    $MailCredentials = Get-Credential
}

Send-EmailMessage -From @{ Name = 'Przemysław Kłys'; Email = 'przemyslaw.klys@test.pl' } -To 'przemyslaw.klys@test.pl' `
    -Server 'smtp.office365.com' -SecureSocketOptions Auto -Credential $MailCredentials -HTML $Body -DeliveryNotificationOption OnSuccess -Priority High `
    -Subject 'This is another test email'

Send-MailMessage -To 'przemyslaw.klys@test.pl' -Subject 'Test' -Body 'test me' -SmtpServer 'smtp.office365.com' -From 'przemyslaw.klys@test.pl' `
    -Attachments "$PSScriptRoot\..\Mailozaurr.psd1" -Cc 'przemyslaw.klys@test.pl' -DeliveryNotificationOption OnSuccess -Priority High -Credential $MailCredentials -UseSsl -Port 587 -Verbose # -Encoding UTF8

```

Hope it helps.

**Comment by nkronberg** [comment]
This is great!  I will attempt the workaround to see if it suits my purposes for now.  Thanks for bringing it to my attention that Send-MailMessage is deprecated, I can't believe I didn't know that by now.  it figures they wouldn't have a suitable replacement for it by now, but it _is_ Microsoft.  I need to check with a colleague who's already out for the day to confirm, but I can tell you a couple things about the environment which I believe is allowing it to work as I've described:

We are using Exchange, and Active Directory for authentication.  In order to protect our mail relay, we utilize an AD group that a (user or computer) account must be a member of in order to send through this particular relay.  After looking at the group more closely, what I believe is happening is the group is bestowing  _anonymous_ relay permissions on its members.  It adds the following permissions:

- ms-Exch-SMTP-Submit
- ms-Exch-SMTP-Accept-Any-Sender
- ms-Exch-Accept-Headers-Routing

https://docs.microsoft.com/en-us/Exchange/mail-flow/connectors/allow-anonymous-relay?view=exchserver-2016

So, I think I answered my own question on this.  I'm still not sure why Send-MailMessage works and the PSWriteHTML email function doesn't work the same way with regard to asking for credentials, but it's entirely possible PSWriteHTML is more compliant with current standards than Send-MailMessage is at this point.  It's definitely not an issue with your module, at least as far as I can tell.  You helped push me in the right direction though, and gave an answer that should work for my purposes.  I very much appreciate it.

**Comment by PrzemyslawKlys** [comment]
Well, what I do is expose `$Email.UseDefaultCredentials` out in EmailServer setting as I believe this will do what you want. Would you be up for testing this?

**Comment by nkronberg** [comment]
> Well, what I do is expose `$Email.UseDefaultCredentials` out in EmailServer setting as I believe this will do what you want. Would you be up for testing this?

I'm absolutely open to testing it.

**Comment by PrzemyslawKlys** [comment]
You can try it now. Just add -UseDefaultCredential for EmailServer and lets see what happens

**Comment by PrzemyslawKlys** [comment]
@nkronberg were you able to test this?
