### ISSUE TITLE
Import breaks powershell GUI

### ISSUE THREAD

**Issue by paddy75** [EvotecIT/PSWriteHTML#157]
I have a multi form project built in PowerShell Studio. Everything runs fine. I import PSWriteHTML and Mailozaurr. After the import the GUI is not working anymore and the script is finish after few seconds. After "remove-module pswritehtml" the GUI is working again without any kind of problem.

**Comment by PrzemyslawKlys** [comment]
I have never used PowerShell Studio. I work with ISE and VSCode and neither have any problems. I believe you need to contact Sapien for support.

**Comment by paddy75** [comment]
I contacted them. We see what will happen. Hope they have any kind of idea

**Comment by paddy75** [comment]
I got an answer from Sapien

> Export your project to a PowerShell Script.
Run it only, without fail from a console with the different scenarios. Forget how it runs from PowerShell Studio or the ISE.
While both the ISE and PowerShell Studio use the same PowerShell engine as the console, they both actually do not have a console.
Some modules rely on there being an actual console and if only for the fancy progress indicator. I do not know if that is the case here of course, but
for testing this you need to create an environment where you keep everything consistent and only change one thing at a time.
So, run it from the console, repeatedly. Do not close the console in between. How does that behave?

After this answer I tested again. Here are the steps I did:
1. exported my project into *.export.ps1
2. opened a powershell console and run this scipt-->no working
3. in the project i commend it out to import this module, export again and run it in the console-->not working
4. in the console i entered to remove the module and run the export again-->working
5. import the module again in the console, try to run my export--> not working again.

**Comment by PrzemyslawKlys** [comment]
Ye, none of the modules require Console. PSWriteHTML uses standard Verbose/Warning streams only. I dislike progress indicators so I don't use them. Same for Mailozaurr. There's nothing being output to screen other than the mentioned data.

**Comment by PrzemyslawKlys** [comment]
Any luck with this?
