### ISSUE TITLE
BUG: Issue with DiagramNode not populating

### ISSUE THREAD

**Issue by high101bro** [EvotecIT/PSWriteHTML#158]
# BLUF: Below are two blocks of code:
Block 1: DiagramNode does Not Work
Block 2: Works - Same code, but different order
    
# CODE BLOCK 1: 
The New-DiagramNode does NOT populate data
But if you change the order of the code it'll work... comment out this section and run Code Block 2
Note: That if you also remove either or both HTMLTable or HTMLChart in Block 1, the DiagramNode will also populate
```
$Processes = Get-Process | Select -First 5 | sort workingset
New-HTML -Online -FilePath $PSScriptRoot\BUG_Diagram_Not_Showing.html -Show {
    New-HTMLTable -DataTable $Processes
    New-HTMLChart {
        foreach ($Process in $Processes) {
            New-ChartBar -Name $Process.name -Value $Process.Workingset
        }
    }
    New-HTMLDiagram {
        New-DiagramNode -Label '1' -To '2'
        New-DiagramNode -Label '2' -To '3'
        New-DiagramNode -Label '3' -To '4'
        New-DiagramNode -Label '4'
    }
}
```

# CODE BLOCK 2: 
Everything works when ran in this order
Note that other tests of mine broke the code when other HTMLTable or HTMLCharts were added afterwards
```
$Processes = Get-Process | Select -First 5 | sort workingset
New-HTML -Online -FilePath $PSScriptRoot\BUG_Diagram_Not_Showing.html -Show {
    New-HTMLDiagram {
        New-DiagramNode -Label '1' -To '2'
        New-DiagramNode -Label '2' -To '3'
        New-DiagramNode -Label '3' -To '4'
        New-DiagramNode -Label '4'
    }
    New-HTMLTable -DataTable $Processes
    New-HTMLChart {
        foreach ($Process in $Processes) {
            New-ChartBar -Name $Process.name -Value $Process.Workingset
        }
    }
}
```

**Comment by PrzemyslawKlys** [comment]
It's fixed in new release that will be out soon.

**Comment by PrzemyslawKlys** [comment]
Fixed, please Update-Module PSWriteHTML, test and let me know.

**Comment by high101bro** [comment]
Just updated and tested. It works now as expected. Thank you.
