### ISSUE TITLE
How to customize tabs?

### ISSUE THREAD

**Issue by c3rberus** [EvotecIT/PSWriteHTML#16]
I am testing PSWriteHTML and there isn't a whole lot of documentation, I checked the blogs and searched the code as well; is there a way to customize the tabs css/js?

I don't want the on-click effect or the fa-bomb icon but wasn't able to see any way to change it through parameters?

Here is my example..

```powershell
Install-Module PSWriteHTML -Force
Import-Module PSWriteHTML -Force

$CSV = Import-Csv -Path C:\IT\process.csv

New-HTML -TitleText "Infrastructure Report" -UseCssLinks:$false -UseJavaScriptLinks:$false -Author "test" -FilePath C:\IT\infra.html -ShowHTML {
    New-HTMLTab -TabName 'TESTING' -TabHeading "testing"  {
        New-HTMLContent -HeaderText 'Content Text' -CanCollapse {
            New-HTMLTable -DataTable $CSV -Buttons @('excelHtml5','csvHtml5') -HideFooter
        }
    }
    New-HTMLTab -TabName 'TESTING' -TabHeading "testing" {
        New-HTMLContent -HeaderText 'Content Text' -CanCollapse {
            New-HTMLTable -DataTable $CSV -Buttons @('excelHtml5','csvHtml5') -HideFooter
        }
    }
}
```

**Comment by PrzemyslawKlys** [comment]
I would like to give you good news but I can't. There's like 0 configuration for Tabs. The bomb is there kind of by accident as I wanted to load/allow all icons from Fonts Awesome to be available but failed with providing a guide. So I stuck with a bomb for a starter. The idea is that you should be able to pick None or one of 5xxx icons per each tab. 

The idea of on-click effect - well that isn't configurable either. But you right, it should be. 

Seeing as other person requested Tabs within Tabs, Tabs require a rewrite. I just need to find good looking, So I need to find "free" CSS/js code with nice looking tabs within tabs that can be easily adapted and change things around. 

As for custom CSS/js, it's a bit tricky. There are lots of moving parts in PSWriteHTML and touching one thing may break other stuff. I would prefer people doing some research over PSWriteHTML and help out with some choices/configuration. The only thing I need is for it to be useful and good looking (to an extent).

**Comment by PrzemyslawKlys** [comment]
I'm working a bit on the tabs:

![image](https://user-images.githubusercontent.com/15063294/59214906-53578a00-8bb8-11e9-84e1-f96491185304.png)

You'll be able to choose one of 1000+ icons. 

```powershell
Import-Module .\PSWriteHTML.psd1 -Force

$Test = Get-Process | Select-Object -First 5

#$Test | Out-HtmlView

New-HTML -TitleText 'My title' -UseCssLinks:$true -UseJavaScriptLinks:$true -FilePath $PSScriptRoot\Example22.html -Show {
    New-HTMLTab -IconBrands aws -Name 'Test 1' -IconColor DarkGoldenrod {
        New-HTMLTable -DataTable $Test -PagingOptions @(50, 100, 150, 200) {
            New-HTMLTableButtonPDF -PageSize TABLOID -Orientation portrait
            New-HTMLTableButtonExcel
            New-HTMLTableCondition -Name 'HandleCount' -Type number -Operator gt -Value 300 -BackgroundColor Yellow
            New-HTMLTableCondition -Name 'ID' -Type number -Operator gt -Value 16000 -BackgroundColor Green
            New-HTMLTableCondition -Name 'Name' -Type string -Operator eq -Value 'browser_broker' -BackgroundColor Gold -Row
        }
    }
    New-HTMLTab -Name 'Test 2' -IconSolid address-card {

    }
    New-HTMLTab -Name 'Test 3' -IconSolid camera {

    }
    New-HTMLTab -Name 'Test 4' -IconBrands microsoft {

    }
    New-HTMLTab -Name 'Test 5' -IconRegular calendar {

    }
    New-HTMLTab -Name 'Test 6' -IconSolid yin-yang {

    }
}
```

You will be able to define a different color for icon and different for text. Same for size. Also, no icon is a possibility.
