### ISSUE TITLE
Tabs + New-HTMLTable -FixedFooter

### ISSUE THREAD

**Issue by smasterson** [EvotecIT/PSWriteHTML#166]
I've noticed an issue when switching tabs using tables with -FixedFooter
If the footer is 'floating' when you switch tabs, the footer stays in view.

```
$data = Get-Process | select -First 50

New-HTML -Online -FilePath $env:TEMP\test.html -ShowHTML {

  New-HTMLTab -Name 'Tab1' {  

  }  
  New-HTMLTab -Name 'Tab2' {  

    New-HTMLSection -HeaderText 'Test Table' {    
  
      New-HTMLTable -DataTable $data -DisablePaging -FixedFooter      

    }  

  }

}
```
Switch to Tab2, you should have a floating footer (else select more processes), then switch back to Tab1, you'll find the table footer from Tab2 still visible.

I also noticed that -FixedFooter auto enables -FixedHeader - is this intentional?

**Comment by PrzemyslawKlys** [comment]
Hi, I see the issue. I will have to ask DataTables support if this can be prevented. Fixed Footer/Fixed Header is probably a bug. 

But having it visible only on one tab, that may be as designed as a table is not expecting to have boundaries. I'll open an issue on their end.

**Comment by PrzemyslawKlys** [comment]
2nd issue is fixed. 
1st issue requires implementation of: https://datatables.net/extensions/fixedheader/examples/options/show-hide.html as per help from DataTables developers: https://datatables.net/forums/discussion/comment/182051#Comment_182051
