### ISSUE TITLE
Link Pie and Bar Charts to Table for Autosearch

### ISSUE THREAD

**Issue by high101bro** [EvotecIT/PSWriteHTML#169]
Request to add linking Pie and Bar charts to an HTML Table, similar to how Diagrams can be linked to HTML Tables with the -ID and -ColumnID parameters...

The intent is to be able to click on a chart and quickly narrow down the HTML Table to the desired data. 
Example 1: If one pie showed process data memory utilization for a single computer, when you clicked on the slice with the largest section, it would show you the process in the HTML Table.
Example 2: If a bar chart show X number of computers that had process names running, clicking on each bar would filter the HTML Table to show just the computers that were represented within that bar/process name.

This would be an amazing and useful feature. Thank you for all your efforts!

Source Example:
    New-HTMLTable -DataTable $DataTable -DataTableID $TableID
    New-DiagramEvent -ID $TableID -ColumnID 1

Request Example:
    New-HTMLTable -DataTable $DataTable -DataTableID $TableID
    New-ChartPieEvent -ID $TableID -ColumnID 1
    New-ChartBarEvent -ID $TableID -ColumnID 1
    New-ChartBarEvent -ID $TableID -ColumnID 2

Best Regards,
     high101bro

**Comment by PrzemyslawKlys** [comment]
This will be available in next version

```powershell
# Define data
$DataTable = @(
    [PSCustomObject] @{
        Name  = 'My Object 1'
        Time  = 1
        Money = 5
        Taxes = 20
    }
    [PSCustomObject] @{
        Name  = 'My Object 2'
        Time  = 3
        Money = 1
        Taxes = 5
    }
    [PSCustomObject] @{
        Name  = 'My Object 3'
        Time  = 12
        Money = 5
        Taxes = 1
    }
)

# Define HTML
New-HTML {
    New-HTMLTable -DataTable $DataTable -DataTableID 'NewIDtoSearchInChart'
    New-HTMLChart {
        New-ChartToolbar -Download
        foreach ($Object in $DataTable) {
            New-ChartPie -Name $Object.Name -Value $Object.Time
        }
        # Define event
        New-ChartEvent -DataTableID 'NewIDtoSearchInChart' -ColumnID 0
    }
} -ShowHTML -FilePath $PSScriptRoot\Example-ChartsWithTablesPie.html -Online #-Format
```

Seems to mostly work.
