### ISSUE TITLE
Datatable color

### ISSUE THREAD

**Issue by amolsp777** [EvotecIT/PSWriteHTML#17]
Hello, 

First, Thanks for the great work. Really helpful and still learning your module one by one. 
1. How can I change the Table header color from light blue to gray or something else?
2. Any example to use HTMLChartbar?
3. Can I use HTMLContent with one for Datatable and another one for Chart? 

Just ask these question as still trying to figure it out, also not examples found :) 

Thanks a lot.

**Comment by PrzemyslawKlys** [comment]
Well,

There's the examples section:
https://github.com/EvotecIT/PSWriteHTML/tree/master/Examples/Example15-Charts-2

I've added your Gray color into example in 3 different ways. I guess you mean Section colors and not table colors as Table doesn't have colors support. 

Sorry for lack of documentation but I just don't have time, I use examples as documentation. Also if you can wait for charts that would be best. I'm working on a new different way to build charts. The old one most likely will work but I want to make it easier. 

```
New-HTLMLChart -Type 'Bar' {
    New-ChartLegend -Name 'Time'
    New-ChartBar -Name 'Test' -Value 1
    New-ChartBar -Name 'Test1' -Value 2
    New-ChartBar -Name 'Test2' -Value 3
}
```

But that is just a concept that I am not sure I want to go with.

**Comment by amolsp777** [comment]
Thank you so much for the response.
I am loving this :)
