### ISSUE TITLE
Sorting Order for Datetime is broken

### ISSUE THREAD

**Issue by ferwe** [EvotecIT/PSWriteHTML#18]
Hi :)

During my work with Dashimo i figured out, that the sorting with datetime is not always working like expected. 
![image](https://user-images.githubusercontent.com/36640422/58249180-77187480-7d5e-11e9-95f5-70720ecb8a95.png)

To ensure, that the format of the values is correct, I did check the type in powershell before the data was transfered to Dashimo.

After some investigation I found a possible solution.

If I understand the code correctly this part has to be added to https://github.com/EvotecIT/PSWriteHTML/blob/master/Public/New-HTMLTable.ps1
and the momemt.js needs to be included.

Example Code
```javascript
$(document).ready(function() {
    $.fn.dataTable.moment( 'HH:mm MMM D, YY' );
    $.fn.dataTable.moment( 'dddd, MMMM Do, YYYY' );
```
[https://datatables.net/blog/2014-12-18](https://datatables.net/blog/2014-12-18)

The format could be a paramter for the New-HTMLTable Function.

**Comment by PrzemyslawKlys** [comment]
The sorting by date is not only not working but not existent. That's why it's good that you're providing a solution :-) 

Will add it, or you can add it? :-) This requires adding JS link to Header below. So for JSLink just provide an array of strings. 

```powershell
$Script:Configuration {

        DataTables       = @{
            Comment      = 'DataTables'
            HeaderAlways = @{
                Css         = "$PSScriptRoot\..\Resources\CSS\datatables.css"
                CssNoscript = "$PSScriptRoot\..\Resources\CSS\datatables.noscript.css"
            }
            Header       = @{
                CssLink = 'https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.18/af-2.3.2/b-1.5.4/b-colvis-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/fc-3.2.5/fh-3.1.4/kt-2.5.0/r-2.2.2/rg-1.1.0/rr-1.2.4/sc-1.5.0/sl-1.2.6/datatables.min.css'
                Css     = "$PSScriptRoot\..\Resources\CSS\datatables.min.css"
                JsLink  = "https://cdn.datatables.net/v/dt/jq-3.3.1/dt-1.10.18/af-2.3.2/b-1.5.4/b-colvis-1.5.4/b-html5-1.5.4/b-print-1.5.4/cr-1.5.0/fc-3.2.5/fh-3.1.4/kt-2.5.0/r-2.2.2/rg-1.1.0/rr-1.2.4/sc-1.5.0/sl-1.2.6/datatables.min.js"
                JS      = "$PSScriptRoot\..\Resources\JS\datatables.min.js"
            }
        }
}
```

And adding your change to New-HTMLTable as you've shown.

**Comment by ferwe** [comment]
I'm testing with a html site atm. 

If i got this running, I will try to add it :)

**Comment by PrzemyslawKlys** [comment]
Thank you again, great work. Impressive attention to details!

**Comment by Ridis** [comment]
Hi and thank you for the amazing tool.

Is there a way to bypass this error in the sorting now?

**Comment by PrzemyslawKlys** [comment]
@Ridis what error?

**Comment by Ridis** [comment]
When I use in powershell
Table -DataTable $Final -DefaultSortColumn [Get-date]Timestamp -DefaultSortOrder "Descending" -HideFooter 

the initial sorting in the HTML file seems OK. However, when I click on the "Timestamp" header in the HTML file, the sorting becomes as Ferwe reported above. Am I missing something?.

**Comment by Ridis** [comment]
No worries. I needed to add -DateTimeSortingFormat 'DD/MM/YYYY HH:mm:ss'
