### ISSUE TITLE
upgrade breaks View.  0.0.111 > 0.0.130

### ISSUE THREAD

**Issue by madmax01** [EvotecIT/PSWriteHTML#188]
Hi everyone,

so far i used 0.0.111  and everything worked fine.

i just upgraded to 0.0.130 > since then the view is kinda broken .

i reverted back,.... all fine again.

Before upgrade
![image](https://user-images.githubusercontent.com/5938215/105744255-23036180-5f3d-11eb-95af-754989988877.png)

After upgrade
![image](https://user-images.githubusercontent.com/5938215/105744345-44fce400-5f3d-11eb-8a32-c349f13fce3d.png)

it seems the ordering logic and the Search box went somewhere else.  

was something change after - so i need to change the Code?

**Comment by PrzemyslawKlys** [comment]
Can you give me some code to reproduce it?

**Comment by madmax01** [comment]
Hi,

i removed just some contents and added dummy commands for some variables.... 

dummy content you should see then inside the "Clusters Tab"  > "Clusters View Section"

`##v2.1

param (  

	[Parameter(ValueFromPipeline = $true, HelpMessage = "Enter desiRed title for report")]
	[String]$ReportTitle = "test Report",
	#Location the report will be saved to
	
	[Parameter(ValueFromPipeline = $true, HelpMessage = "Enter desiRed directory path to save; Default: C:\Automation\")]
	[String]$ReportSavePath = "C:\"
)




#Check for ReportHTML Module
$reporthtml = Get-Module -ListAvailable -Name "ReportHTML"

If ($null -eq $reporthtml)
{
	
	Write-Host "ReportHTML Module is not present, attempting to install it"
	
	Install-Module -Name ReportHTML -requiRedversion 1.4.1.2 -Force
	Import-Module ReportHTML -ErrorAction SilentlyContinue
}

#Check for PSWriteHTML Module
$pswritehtml = Get-Module -ListAvailable -Name "PSWriteHTML"

If ($null -eq $pswritehtml)
{
	
	Write-Host "PSWriteHTML Module is not present, attempting to install it"
	
	Install-Module -Name PSWriteHTML -requiRedversion 0.0.111 -Force
	Import-Module PSWriteHTML -ErrorAction SilentlyContinue
}

$mycolclusters = get-folder
$mycoldatastores = "0"
$mycolvms = "0"
$mycolhosts = "0"

$PieObjectVMObjOS = Get-HTMLPieChartObject
$PieObjectVMObjOS.Title = "Guest Operating Systems"
$PieObjectVMObjOS.ChartStyle.ColorSchemeName = "ColorScheme3"
$PieObjectVMObjOS.ChartStyle.ColorSchemeName = "Generated3"
$PieObjectVMObjOS.ChartStyle.ColorSchemeName = 'Random'

$GraphComputerOS = New-Object 'System.Collections.Generic.List[System.Object]'
$SimpleCountTable = New-Object 'System.Collections.Generic.List[System.Object]'
$datastoreIssuesTable = New-Object 'System.Collections.Generic.List[System.Object]'
$clustersissuesTable = New-Object 'System.Collections.Generic.List[System.Object]'
$vmsissuesTable = New-Object 'System.Collections.Generic.List[System.Object]'
$hostutilizationissuesTable = New-Object 'System.Collections.Generic.List[System.Object]'



$objULic.PSObject.Properties  | ForEach-Object {
$GraphComputerOS.Add([PSCustomObject]@{'Name'  = $_.Name;"Count" =$_.Value})
}

$objULic = [PSCustomObject]@{
		'Amount Clusters' = ($clusters.name).Count
		'Amount VMHosts' = ($vmhosts.name).Count
		'Amount VMs' = ($vms.name).Count
	}
$SimpleCountTable.Add($objULic)

$objUlic = [PSCustomObject]@{
			'Amount Green' = (($mycolhosts |where {$_.status -match "Green"}).name).count
			'Amount Yellow' = (($mycolhosts|where {$_.status -match "Yellow"}).name).count
			'Amount Red' = (($mycolhosts |where {$_.status -match "Red"}).name).count
	}
$hostutilizationissuesTable.Add($objULic)

$objUlic = [PSCustomObject]@{
			'Amount Green' = (($mycolclusters |where {$_.status -match "Green"}).name).count
			'Amount Yellow' = (($mycolclusters|where {$_.status -match "Yellow"}).name).count
			'Amount Red' = (($mycolclusters |where {$_.status -match "Red"}).name).count
	}
$clustersissuesTable.Add($objULic)


$objUlic = [PSCustomObject]@{
			'Amount Green' = (($mycoldatastores |where {$_.status -match "Green"}).name).count
			'Amount Yellow' = (($mycoldatastores |where {$_.status -match "Yellow"}).name).count
			'Amount Red' = (($mycoldatastores |where {$_.status -match "Red"}).name).count
	}
$datastoreIssuestable.Add($objULic)

$objUlic = [PSCustomObject]@{
			'Amount Green' = (($mycolvms |where {$_.status -match "Green"}).name).count
			'Amount Yellow' = (($mycolvms |where {$_.status -match "Yellow"}).name).count
			'Amount Red' = (($mycolvms |where {$_.status -match "Red"}).name).count
	}
$vmsIssuestable.Add($objULic)

$tabarray = @('Dashboard', 'Clusters', 'Datastores','VMHosts', 'VMs')

Write-Host "Compiling Report..." -ForegroundColor Green

#Dashboard Report
$FinalReport = New-Object 'System.Collections.Generic.List[System.Object]'
$FinalReport.Add($(Get-HTMLOpenPage -TitleText $ReportTitle -LeftLogoString $CompanyLogo  -RightLogoString $RightLogo))
$FinalReport.Add($(Get-HTMLTabHeader -TabNames $tabarray))

$FinalReport.Add($(Get-HTMLTabContentopen -TabName $tabarray[0] -TabHeading ("Report: " + (Get-Date -Format MM-dd-yyyy))))
$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "Infra Counts"))
$FinalReport.Add($(
new-html -Online{
New-HTMLTable -DataTable $SimpleCountTable -HideFooter -DisableSearch -DisableOrdering -DisableInfo -Buttons @() {
New-HTMLTableHeader 'Amount Clusters'  -Alignment center
New-HTMLTableHeader 'Amount VMHosts'  -Alignment center
New-HTMLTableHeader 'Amount VMs'  -Alignment center
New-HTMLTableContent -ColumnIndex 1,2,3 -Alignment center
}}))
$FinalReport.Add($(Get-HTMLContentClose))

$FinalReport.Add($(New-HTML -TitleText 'Services Status' -Online  {
    New-HTMLSection -Invisible {
	
		if ($clustersissuesTable.'Amount Red' -gt "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'CLUSTERS ISSUES' -Text $clustersissuesTable.'Amount Red' -TextColor Red -BarColorLeft Red -IconSolid info-circle -IconColor Red}
			}
		if ($clustersissuesTable.'Amount Red' -eq "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'CLUSTERS ISSUES' -Text $clustersissuesTable.'Amount Red' -TextColor Green -BarColorLeft Green -IconSolid check-circle -IconColor Green}
			}
	
		if ($vmsissuesTable.'Amount Red' -gt "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'VMS ISSUES' -Text $vmsissuesTable.'Amount Red' -TextColor Red -BarColorLeft Red -IconSolid info-circle -IconColor Red}
			}
		if ($vmsissuesTable.'Amount Red' -eq "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'VMS ISSUES' -Text $vmsissuesTable.'Amount Red' -TextColor Green -BarColorLeft Green -IconSolid check-circle -IconColor Green}
			}
      }
	   New-HTMLSection -Invisible {
	   if ($hostutilizationissuesTable.'Amount Red' -gt "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'HOSTS Utilization ISSUES' -Text $hostutilizationissuesTable.'Amount Red' -TextColor Red -BarColorLeft Red -IconSolid info-circle -IconColor Red}
			}
		if ($hostutilizationissuesTable.'Amount Red' -eq "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'HOSTS Utilization ISSUES' -Text $hostutilizationissuesTable.'Amount Red' -TextColor Green -BarColorLeft Green -IconSolid check-circle -IconColor Green}
			}
	
		if ($datastoreIssuesTable.'Amount Red' -gt "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'DATASTORES ISSUES' -Text $datastoreIssuesTable.'Amount Red' -TextColor Red -BarColorLeft Red -IconSolid info-circle -IconColor Red}
			}
		if ($datastoreIssuesTable.'Amount Red' -eq "0") {
			New-HTMLPanel -Invisible {New-HTMLToast -TextHeader 'DATASTORES ISSUES' -Text $datastoreIssuesTable.'Amount Red' -TextColor Green -BarColorLeft Green -IconSolid check-circle -IconColor Green}
			}
	   }
}))
$FinalReport.Add($(Get-HTMLTabContentClose))

$FinalReport.Add($(Get-HTMLTabContentopen -TabName $tabarray[1] -TabHeading ("Report: " + (Get-Date -Format MM-dd-yyyy))))
$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "Clusters View"))
$FinalReport.Add($(
New-HTMLTable -DataTable $clustersissuesTable -HideFooter -DisableSearch -DisableOrdering -DisableInfo -Buttons @() {
New-HTMLTableHeader 'Amount Green' -BackGroundColor Green -Alignment center
New-HTMLTableHeader 'Amount Yellow' -BackGroundColor Yellow -Alignment center
New-HTMLTableHeader 'Amount Red' -BackGroundColor Red -Alignment center
New-HTMLTableContent -ColumnIndex 1,2,3 -Alignment center
}
))
$FinalReport.Add($(New-HTMLSection -HeaderText 'Clusters View Section' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mycolclusters -HideFooter -ScrollCollapse -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength{
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Green -BackgroundColor Green
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Yellow -BackgroundColor Yellow
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Red -BackgroundColor Red
}
}))
$FinalReport.Add($(Get-HTMLContentClose))
$FinalReport.Add($(Get-HTMLTabContentClose))

$FinalReport.Add($(Get-HTMLTabContentopen -TabName $tabarray[2] -TabHeading ("Report: " + (Get-Date -Format MM-dd-yyyy))))
$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "Datastores View"))
$FinalReport.Add($(
New-HTMLTable -DataTable $datastoreIssuestable -HideFooter -DisableSearch -DisableOrdering -DisableInfo -Buttons @() {
New-HTMLTableHeader 'Amount Green' -BackGroundColor Green -Alignment center
New-HTMLTableHeader 'Amount Yellow' -BackGroundColor Yellow -Alignment center
New-HTMLTableHeader 'Amount Red' -BackGroundColor Red -Alignment center
New-HTMLTableContent -ColumnIndex 1,2,3 -Alignment center
}
))
$FinalReport.Add($(New-HTMLSection -HeaderText 'Datastores View Section' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mycoldatastores -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength {
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Green -BackgroundColor Green
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Yellow -BackgroundColor Yellow
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Red -BackgroundColor Red
#New-HTMLTableContent -ColumnIndex 0,1,2,3,4,5,6,7 -Alignment center
}}))
$FinalReport.Add($(Get-HTMLContentClose))
$FinalReport.Add($(Get-HTMLTabContentClose))

$FinalReport.Add($(Get-HTMLTabContentopen -TabName $tabarray[3] -TabHeading ("Report: " + (Get-Date -Format MM-dd-yyyy))))
$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "VMHosts Utilization"))
$FinalReport.Add($(
New-HTMLTable -DataTable $hostutilizationissuesTable -HideFooter -DisableSearch -DisableOrdering -DisableInfo -Buttons @() {
New-HTMLTableHeader 'Amount Green' -BackGroundColor Green -Alignment center
New-HTMLTableHeader 'Amount Yellow' -BackGroundColor Yellow -Alignment center
New-HTMLTableHeader 'Amount Red' -BackGroundColor Red -Alignment center
New-HTMLTableContent -ColumnIndex 1,2,3 -Alignment center
}))
$FinalReport.Add($(New-HTMLSection -HeaderText 'VMHosts Utilization View Section' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mycolhosts -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength {
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Green -BackgroundColor Green
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Yellow -BackgroundColor Yellow
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Red -BackgroundColor Red
}}))
$FinalReport.Add($(Get-HTMLContentClose))
$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "VMHosts HW View"))
$FinalReport.Add($(New-HTMLSection -HeaderText 'VMHosts HW View Section' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mycolhosts -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength
}))
$FinalReport.Add($(Get-HTMLContentClose))

$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "VMHosts Spec View"))
$FinalReport.Add($(New-HTMLSection -HeaderText 'VMHosts Spec View Section' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mycolhosts -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength
}))
$FinalReport.Add($(Get-HTMLContentClose))

$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "VMHosts Vmware Versions"))
$FinalReport.Add($(New-HTMLSection -HeaderText 'VMHosts Vmware Versions Section' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mycolhosts -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength
}))
$FinalReport.Add($(Get-HTMLContentClose))
$FinalReport.Add($(Get-HTMLTabContentClose))

$FinalReport.Add($(Get-HTMLTabContentopen -TabName $tabarray[4] -TabHeading ("Report: " + (Get-Date -Format MM-dd-yyyy))))
$FinalReport.Add($(Get-HTMLContentOpen -HeaderText "Vms View"))
$FinalReport.Add($(
New-HTMLTable -DataTable $vmsIssuestable -HideFooter -DisableSearch -DisableOrdering -DisableInfo -Buttons @() {
New-HTMLTableHeader 'Amount Green' -BackGroundColor Green -Alignment center
New-HTMLTableHeader 'Amount Yellow' -BackGroundColor Yellow -Alignment center
New-HTMLTableHeader 'Amount Red' -BackGroundColor Red -Alignment center
New-HTMLTableContent -ColumnIndex 1,2,3 -Alignment center
}))
$FinalReport.Add($(New-HTMLSection -HeaderText 'Vms View Section' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mycolvms -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength{
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Green -BackgroundColor Green
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Yellow -BackgroundColor Yellow
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value Red -BackgroundColor Red
}}))
$FinalReport.Add($(Get-HTMLContentClose))


$Day = (Get-Date).Day
$Month = (Get-Date).Month
$Year = (Get-Date).Year
$ReportName = ("$Day-$Month-$Year-Lab_vCenter_Report")

Save-HTMLReport -ReportContent $FinalReport  -ReportName $ReportName  -ReportPath $ReportSavePath







`

**Comment by madmax01** [comment]
just as info. i didn't changed the Install-Module to 0.0.130... it's at 0.0.111 inside.

**Comment by PrzemyslawKlys** [comment]
Well you're using a mix of ReportHTML and PSWriteHTML. Pick one and stick to it. I can't be responsible for ReportHTML html/js/css that may be conflictng with PSWriteHTML. I have no clue why would you need to use both.

**Comment by madmax01** [comment]
well thx for the Info....... was just long time ago when i created this... and at that Time i had Issues - and Solution to get it working was to combine both Worlds together... May was related to older Builds... i don't really remember what Issue it was.

i will try to remove reporthtml from latest PSWriteHTML setup and see how goes.

Very sry i overlocked that this is still part...

And by the Way i never mentioned anyone to be Responsive,.. i just hoped to get an Clue why this breaks after the Upgrade. Because worked before ;). that's all.  but thx for the Response.. Will check further

**Comment by PrzemyslawKlys** [comment]
It's much easier to maintain PSWriteHTML - and it should be fairly easy to fix it to use PSWriteHTML alone. I saw you had tabs, sections, and tables only. Converting it should be pretty straightforward.

**Comment by PrzemyslawKlys** [comment]
The reason it doesn't work or things visually changed is that I've switched PSWriteHTML to almost fully FlexBox https://css-tricks.com/snippets/css/a-guide-to-flexbox/ - if you mix it up with non-flexbox approach things start to break when it comes to margins and other things. So you need to change tabs/sections to pswritehtml and you will be fine. And it will look much better.
