### ISSUE TITLE
Support for authenticated URLs on AjaxJSON data files 

### ISSUE THREAD

**Issue by daniel0x00** [EvotecIT/PSWriteHTML#189]
I was planning to host both `.html` & `.json` file on the same Azure Storage Account, so I can use `AjaxJSON` and send via email an authenticated link to the `.html` file, which will asynchronously load the data in also an authenticated way. My data set is ~300MB. 

I realized the `New-TableServerSide` function hardcodes the data file as `$DataTableID.json`, whereas files with Azure Storage with SAS tokens look like this: `https://<name>.blob.core.windows.net/<container>/<file.ext>?<sas_token>`. 

Thereby I was thinking to do a PR for this function -or its parents- to allow custom data filenames. However when I modify the `.html` file to point out to the Azure Storage URL and host both files there, ajax loads the data well, pagination shows up but I see no data, even when using `-AllProperties`. No JS errors either. 

Am I missing something?
Thanks a lot!

**Comment by PrzemyslawKlys** [comment]
Could it be CORS issue?

**Comment by PrzemyslawKlys** [comment]
Also what about HTML - does it show properly built column names? Maybe I broke AjaxJSON - I haven't tested it for a while.

**Comment by daniel0x00** [comment]
Not a CORS issue, file is loading and pagination is loaded too. But no build of column names. I'd like to give you a hand with a PR to support custom data set names, but really got clueless on why columns are not loading. 

![image](https://user-images.githubusercontent.com/6474092/106309852-ff088e80-6262-11eb-85b2-35b761c5fccb.png)

**Comment by PrzemyslawKlys** [comment]
```powershell
$DataTable1 = @(
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 1.42 }
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 1.72 }
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 1.22 }
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 2.73 }
)

New-HTML {
    New-HTMLTable -DataTable $DataTable1 -Title 'Test1' -PagingLength 2 -DataStore AjaxJSON -DataTableID 15
} -ShowHTML -FilePath $PSScriptRoot\Example7_01.html -Online
```

So the JS for the table should have columns that match data

```js
                          "columns": [
                                {
                                    "data": "Test"
                                },
                                {
                                    "data": "Test2"
                                },
                                {
                                    "data": "Test3"
                                },
                                {
                                    "data": "Test4"
                                }
                            ],
```

But also data for thead/tfoot should match it as well

```html
                <table width="100%" id="15" class="dataTables display compact">
                    <thead>
                        <tr>
                            <th>Test</th>
                            <th>Test2</th>
                            <th>Test3</th>
                            <th>Test4</th>
                        </tr>
                    </thead>
                    <tfoot>
                        <tr>
                            <th>Test</th>
                            <th>Test2</th>
                            <th>Test3</th>
                            <th>Test4</th>
                        </tr>
                    </tfoot>
                </table>
```

In your case it seems like there's no match. There's only one problem that when I generate content for my stuff I don't see the data in the file. So maybe some bug. 

I'll do some checks but you check generated html/js for matching column names to your data files.

**Comment by PrzemyslawKlys** [comment]
Ok, i found bug for generating.

**Comment by PrzemyslawKlys** [comment]
Ok, i've released new version. Please give it a try. The trick is columns in JS needs to be an array even with 1 element, or 1 column. Data in files has to be in special format which was broken at some point after I switched from native ConvertTo-Json to my own ConvertTo-JsonLiteral.

**Comment by PrzemyslawKlys** [comment]
Does it work now?

**Comment by daniel0x00** [comment]
It'll test it this afternoon. Haven't had the time yet, sorry. Will let you know. Thanks!

**Comment by daniel0x00** [comment]
Works very well now. Thanks a lot!!!
