### ISSUE TITLE
Table headers pushed to left

### ISSUE THREAD

**Issue by Jay6111** [EvotecIT/PSWriteHTML#191]
Single tab worked fine but when I separated the code into multiple tabs, the HTML page opens on a random tab. That tab will have all table headers aligned properly, but any other tab the table headers are all pushed to the far left while the data remains properly centered.
As soon as you sort any column this fixes the column headers for that table but has to be done for each and every table on that tab. 
![Table-Header](https://user-images.githubusercontent.com/7865537/106612078-51310480-652e-11eb-9d50-f35ff34b5d94.jpg)

The code for that particular section is, 

New-HTMLTab -TabName "Msol" -TabHeading $ReportTitleDate -IconBrands microsoft  {
New-HTMLSection -Name "O365 User Stats" -BackgroundColor DarkGray -CanCollapse -HeaderBackGroundColor Gray {
					New-HTMLSection -Name 'O365 Users' -HeaderTextAlignment left -CanCollapse -HeaderBackGroundColor MediumVioletRed -BackgroundColor Lavender  {
						New-htmlPanel {
							new-htmlTable -DataTable $O365UsersTable -DisableResponsiveTable -HideFooter -PagingOptions 15, 30, 50 -ScrollX #-ScrollX -ScrollY -ScrollSizeY 300
						}
					}
				}

**Comment by PrzemyslawKlys** [comment]
This is related to ScrollX. Seems like a bug but most likely not directly in PSWriteHTML. If you remove -ScrollX it will work.

```powershell

New-HTML {
    New-HTMLTab -TabName "Msol" -TabHeading $ReportTitleDate -IconBrands microsoft {
        New-HTMLTable -DataTable $O365UsersTable -HideFooter -DisableResponsiveTable -PagingOptions 15, 30, 50  #-ScrollX -ScrollY -ScrollSizeY 300
    }
    New-HTMLTab -TabName "Msol" -TabHeading $ReportTitleDate -IconBrands microsoft {
        New-HTMLTable -DataTable $O365UsersTable -HideFooter -DisableResponsiveTable -PagingOptions 15, 30, 50  #-ScrollX -ScrollY -ScrollSizeY 300
    }
} -ShowHTML -Online
```

**Comment by PrzemyslawKlys** [comment]
Fixed - based on discussion in: https://datatables.net/forums/discussion/comment/186568#Comment_186568
