### ISSUE TITLE
New-TableCondition - Special Chars?

### ISSUE THREAD

**Issue by smasterson** [EvotecIT/PSWriteHTML#192]
I seem to be unable to create a table condition with a string comparison using > or <
Is there a way to escape somehow?

```
$a = [PSCustomObject]@{

  Name    = 'My Test'
  MyValue = 'two > one'


}


New-HTML -Online -Temporary -ShowHTML {

  New-HTMLSection -HeaderText "Testing" {
  
    New-HTMLTable -DataTable $a {
    
      New-TableCondition -Name MyValue -ComparisonType string -Operator contains -Value '>' -BackgroundColor red
    
    }
  
  }

}
```

**Comment by PrzemyslawKlys** [comment]
If you take a look at source of HTML you will notice that < is actually represented as HTML equivalent `&lt;`

![image](https://user-images.githubusercontent.com/15063294/106904852-f77e3500-66fb-11eb-9b4d-cb70b1ac64a9.png)

So doing 

```powershell
New-HTMLTableCondition -Name 'Total send size' -Value '&lt;' -BackgroundColor Yellow
```

seems to work properly. Even if you use invokehtmltags and the translation is prevented

![image](https://user-images.githubusercontent.com/15063294/106904972-167cc700-66fc-11eb-806a-31ca392fe316.png)

you still have to use 

```powershell
New-HTMLTableCondition -Name 'Total send size' -Value '&lt;' -BackgroundColor Yellow
```

 to find it. So just check how it's saved in your way or find equivalent in HTML.  Most likely special chars will be similar to the replacement I do in code for New-HTMLTable. 

```powershell
    if ($InvokeHTMLTags) {
        # By default HTML tags are displayed, in this case we're converting tags into real tags
        $Table = $Table -replace '&lt;', '<' -replace '&gt;', '>' -replace '&amp;', '&' -replace '&nbsp;', ' ' -replace '&quot;', '"' -replace '&#39;', "'"
    }
```

**Comment by smasterson** [comment]
:bulb: As soon as I saw `&lt;`

Thanks as always for the quick response!
