### ISSUE TITLE
New-ChartLegend -Color not processing custom color codes correctly

### ISSUE THREAD

**Issue by sbourdeaud** [EvotecIT/PSWriteHTML#196]
When using something like:
New-ChartLegend -Name 'Series 1','Series 2' -Color '#024DA1', '#AFD135'

Only the first custom color code is processed correctly and applied to both series.

**Comment by PrzemyslawKlys** [comment]
Fixed in https://github.com/EvotecIT/PSSharedGoods/commit/25918c186a6cd1a150e954d3ab26aa27e94a8f0f

Normally it would work when used with standard 800 colors. When using Hex it would terminate after first entry. Will be in next release
