### ISSUE TITLE
Problem with umlauts in HTML Table

### ISSUE THREAD

**Issue by mobernberger** [EvotecIT/PSWriteHTML#206]
Hi,
I am working on some Reports for our Management and as we are located in Austria some of our User Displaynames has Umlauts in there.
The Problem is that, that the Umlauts aren't correctly shown in the HTML-Table.
Any hints how to solve that?

Here is a code sample to reproduce the issue. 
```
$DataTable1 = @(
    [PSCustomObject] @{ Test = 'Ätzend'; Test2 = 'Name2'; Test3 = 'Name3' }
    [PSCustomObject] @{ Test = 'Österreich'; Test2 = 'Name2'; Test3 = 'Name3' }
    [PSCustomObject] @{ Test = 'Übel'; Test2 = 'Name2'; Test3 = 'Name3' }    
)
New-HTML {
    New-HTMLTable -DataTable $DataTable1 -Title 'Test Umlauts'
  } -ShowHTML -FilePath $PSScriptRoot\Example-Umlauts.html -Online
```

**Comment by PrzemyslawKlys** [comment]
Works fine here. You need to make sure to set proper encoding of your file to UTF-8 with BOM. 

![image](https://user-images.githubusercontent.com/15063294/109397769-b6fb8b00-7938-11eb-98b0-c08fb3377f74.png)

**Comment by mobernberger** [comment]
Thanks that was a great hint. Thought I tested this before but seems not to be the case.
