### ISSUE TITLE
New-ChartEvent

### ISSUE THREAD

**Issue by tomerikko** [EvotecIT/PSWriteHTML#207]
New-ChartEvent <-- this command appear in many examples for charts.
but i dont seems to find this command.  i am running .132 version.

i was BTW looking for a way to have a dynamic line-chart that filters based on the table filter - not sure if its even possible.

Tomer.

**Comment by PrzemyslawKlys** [comment]
This will be available in 0.0.133 - I'm still trying to make the best of it. Basically, while you click on a bar chart, pie chart, or similar it searches the content in the table. It's not working the other way around tho.

**Comment by tomerikko** [comment]
Ok, gotcha.

Thanks for the quick response.
