### ISSUE TITLE
Out-HTMLView does not work in IE or Chrome for me

### ISSUE THREAD

**Issue by NJK-Work** [EvotecIT/PSWriteHTML#21]
Is there something I need to enable in IE or Chrome to get all the features to work for Out-HTMLView?  I just get a plain old HTML table in IE and chrome - none of the fancy buttons, filters, exports, etc.

Just trying something simple like get-service | out-htmlview.

Thanks
NK

**Comment by PrzemyslawKlys** [comment]
Hi, 

Internet Explorer may not work. It's a bit old. As for Chrome, you must have JS enabled. Probably it's disabled on your machine for local files. By default, it's enabled but if it's company laptop maybe it's forced. JavaScript is responsible for all those bells and whistles.

**Comment by NJK-Work** [comment]
Thank you.
