### ISSUE TITLE
Current published version

### ISSUE THREAD

**Issue by tomerikko** [EvotecIT/PSWriteHTML#211]
Hi, 
i am currently using 0.0.132.
from powershell gallery it loosk like 0.0.135 is out:
https://www.powershellgallery.com/packages/PSWriteHTML/0.0.135
but when i run "Update-Module -Name PSWriteHTML"
i get a long weird error, 
Get-PSGalleryApiAvailability : PowerShell Gallery is currently unavailable.  Please try again later.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2038 char:13
+             Get-PSGalleryApiAvailability -Repository (Get-SourceName  ...
+             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Get-PSGalleryApiAvailability], InvalidOperationException
    + FullyQualifiedErrorId : PowerShellGalleryUnavailable,Get-PSGalleryApiAvailability
 
WARNING: Unable to resolve package source 'https://www.powershellgallery.com/api/v2'.
PackageManagement\Install-Package : No match was found for the specified search criteria and module name 'PSWriteHTML'. Try Get-PSRepository to see all available registered module repositories.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:2052 char:20
+ ...           $sid = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : ObjectNotFound: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package], Exception
    + FullyQualifiedErrorId : NoMatchFoundForCriteria,Microsoft.PowerShell.PackageManagement.Cmdlets.InstallPackage
 

Thoughts of what can be the problem?

**Comment by PrzemyslawKlys** [comment]
I would say it's related to TLS 1.0 -> https://evotec.xyz/powershellgallery-disables-support-for-tls-1-0-breaking-install-module/

```powershell
[Net.ServicePointManager]::SecurityProtocol = [Net.ServicePointManager]::SecurityProtocol -bor [Net.SecurityProtocolType]::Tls12
install-module powershellget -force -SkipPublisherCheck -Scope CurrentUser -AllowClobber
```

You're using highly outdated PowerShellGet.

**Comment by tomerikko** [comment]
Man you are good!  Many thanks!
I am on Srv2016 due to other tools limitation, and on the default PS version - so you were absolutely right.
thanks a lot!
