### ISSUE TITLE
New-HTMLChart & title font size

### ISSUE THREAD

**Issue by tomerikko** [EvotecIT/PSWriteHTML#218]
hi, i could not find a way to change the font size of the New-HTMLChart title.
since it quite big, any chance there is a workaround or its in the pipeline?

New-HTMLChart -title

**Comment by PrzemyslawKlys** [comment]
You would need to add this functionality. According to docs: https://apexcharts.com/docs/options/title/

```json
title: {
    text: undefined,
    align: 'left',
    margin: 10,
    offsetX: 0,
    offsetY: 0,
    floating: false,
    style: {
      fontSize:  '14px',
      fontWeight:  'bold',
      fontFamily:  undefined,
      color:  '#263238'
    },
}
```

It's possible. Seems like an easy change.
