### ISSUE TITLE
New-HTMLTable resizing 

### ISSUE THREAD

**Issue by codaamok** [EvotecIT/PSWriteHTML#22]
Hello! I love what you've made. I plan to chip in on docs when I'm more familiar with some of the options.

I'm creating a HTML table with the following:

> New-HTMLTable -DataTable $Result -Buttons ("copyHtml5", "excelHtml5", "csvHtml5", "pdfHtml5") -DisableColumnReorder -HideFooter -DisablePaging {
    ..
}

I notice if I resize the browser window, dropdowns are created for where the columns couldn't fit fit. The columns would resize to the new browser window size if I just refresh the page. Is there a trick I can easily do with options available to make the columns adjust dynamically, and if they can't all fit, then have a horizontal scroll bar?

I see you recently worked on something that's somewhat similar to what I experience but not sure: https://github.com/EvotecIT/PSWriteHTML/issues/2

Interestingly the columns do resize with Internet Explorer but half the toys are missing, but that's OK I'm not expecting IE support - I'm not an idjit.

I created a gif to demo what I mean in case I'm unclear: https://imgur.com/a/A8DT5hw

**Comment by PrzemyslawKlys** [comment]
Hi,

I know what you mean. I'll add in. 

- ScrollX -> https://datatables.net/examples/basic_init/scroll_x.html
- ScrollY + ScrollX - https://datatables.net/examples/basic_init/scroll_xy.html
- Scroll but with sticky left/right columns https://datatables.net/extensions/fixedcolumns/examples/initialisation/left_right_columns.html

It's really easy to add. I'm currently working on something different:

![image](https://user-images.githubusercontent.com/15063294/60186325-d836da80-982b-11e9-95c1-087f8d3ddfec.png)

here's code generating it - having some issues with multiple columns. Unfortunately, it seems like it will always be an issue. 

```powershell
$Properties = @(
    'Name'
    'Id'
    'PriorityClass'
    'FileVersion'
    'HandleCount'
    'WorkingSet'
    'PagedMemorySize'
    'PrivateMemorySize'
    'VirtualMemorySize'
    'TotalProcessorTime'
    <#
    'SI'
    'Handles'
    'VM'
    'WS'
    'PM'
    'NPM'
    #>
)
$ProcessesAll = Get-Process | Select-Object -First 10
$Processes = $ProcessesAll | Select-Object -First 10 -Property $Properties

New-HTML -TitleText 'Title' -UseCssLinks:$true -UseJavaScriptLinks:$true -FilePath $PSScriptRoot\Example08.html -ShowHTML {

    New-HTMLContent -HeaderText '0 section' {
        New-HTMLPanel {
            New-HTMLTable -DataTable $Processes -HideFooter -ScrollCollapse {
                New-HTMLTableHeader -Names 'Name', 'ID' -Title 'Process Information'
                New-HTMLTableHeader -Names 'PagedMemorySize', 'PrivateMemorySize', 'VirtualMemorySize' -Title 'Memory'
            }
        }
    }
    New-HTMLContent -HeaderText '0 section' {
        New-HTMLPanel {
            New-HTMLTable -DataTable $Processes {
                New-HTMLTableHeader -Names 'Name', 'ID' -Title 'Process Information'
                New-HTMLTableHeader -Names 'PriorityClass', 'FileVersion', 'HandleCount', 'WorkingSet' -Title 'Merge'
                New-HTMLTableHeader -Names 'PagedMemorySize', 'PrivateMemorySize', 'VirtualMemorySize' -Title 'Memory'
            } -Filtering
        }
    }
}
```

**Comment by codaamok** [comment]
Looks good!

I'll have a play and see what I can come up with.

**Comment by PrzemyslawKlys** [comment]
All you have to do is modify hashtable/ordereddictionary in New-HTMLTABLE 

```
    $Options = [ordered] @{
        <# DOM Definition: https://datatables.net/reference/option/dom
            l - length changing input control
            f - filtering input
            t - The table!
            i - Table information summary
            p - pagination control
            r - processing display element
            B - Buttons
            S - Select
        #>
        dom              = 'Bfrtip'
        #buttons          = @($Buttons)
        buttons          = @(
            if ($CustomButtons) {
                $CustomButtons
            } else {
                foreach ($button in $Buttons) {
                    if ($button -ne 'pdfHtml5') {
                        @{
                            extend = $button
                        }
                    } else {
                        @{
                            extend      = 'pdfHtml5'
                            pageSize    = 'A3'
                            orientation = 'landscape'
                        }
                    }
                }
            }
        )
        "colReorder"     = -not $DisableColumnReorder.IsPresent


        # https://datatables.net/examples/basic_init/scroll_y_dynamic.html
        "paging"         = -not $DisablePaging
        "scrollCollapse" = $ScrollCollapse.IsPresent

        <# Paging Type
            numbers - Page number buttons only
            simple - 'Previous' and 'Next' buttons only
            simple_numbers - 'Previous' and 'Next' buttons, plus page numbers
            full - 'First', 'Previous', 'Next' and 'Last' buttons
            full_numbers - 'First', 'Previous', 'Next' and 'Last' buttons, plus page numbers
            first_last_numbers - 'First' and 'Last' buttons, plus page numbers
        #>
        "pagingType"     = $PagingStyle
        "lengthMenu"     = @(
            , @($PagingOptions + (-1))
            , @($PagingOptions + "All")
        )
        "ordering"       = -not $DisableOrdering.IsPresent
        "order"          = @() # this makes sure there's no default ordering upon start (usually it would be 1st column)
        "info"           = -not $DisableInfo.IsPresent
        "procesing"      = -not $DisableProcessing.IsPresent
        "responsive"     = @{
            details = -not $DisableResponsiveTable.IsPresent
        }
        "select"         = -not $DisableSelect.IsPresent
        "searching"      = -not $DisableSearch.IsPresent
        "stateSave"      = -not $DisableStateSave.IsPresent
    }
```
The way it works is that $Options is converted to JSON in the end, giving same look and feel as JavaScript output. 

```
    var table = $('#example').removeAttr('width').DataTable( {
        scrollY:        "300px",
        scrollX:        true,
        scrollCollapse: true,
        paging:         false,
        columnDefs: [
            { width: 200, targets: 0 }
        ],
        fixedColumns: true
    } );
```

So the task here is adding one or more parameters to a single hashtable, testing and making sure things still work as they should. Of course, there's also some design decision on parameters. Good luck  :-) I appreciate it!

**Comment by PrzemyslawKlys** [comment]
Btw if you will be playing with this be aware of this issue: https://github.com/DataTables/DataTablesSrc/issues/143

Just tried it out. You need to remove responsive from hashtable for things to work.

**Comment by PrzemyslawKlys** [comment]
I've added that feature now. Sorry that I didn't give you an option to do it yourself but I needed to test it with one of the new features. You can take a look at the commit how "simple" it was. It would be a pleasure to get some work from you on the project in future ;)

**Comment by codaamok** [comment]
Hey, don't be sorry!! I'm sorry I didn't get stuck in quick enough. I'll take a look and see how it looks today.

**Comment by PrzemyslawKlys** [comment]
New release was published, along with new blog post.

**Comment by codaamok** [comment]
If I specify -ScrollX and the datatable does not enough properties to make the width of the table breach the window, the table header sticks to the left and the body always stays fixed in the center at fixed width.

![image](https://user-images.githubusercontent.com/6683266/60443720-b5ce0400-9c13-11e9-960f-45830887fa2d.png)

Interestingly, if I then remove -ScrollX I would expect the unexpected behaviour to be reverted. This is not true. Even clearing cache and killing browser processes does not. I must log off and log back on again to get back to expected results.

Have you noticed this?

A seperate unrelated question. I was half way through updating docs for some commands noticed the layout for the parameters and syntax. What posh command did you use to generate these? I notice they aren't the same as what get-help generates. I feel it's important whatever changes I make should fit existiing formatting. For example, the notations for datatype don't match and the "syntax" line doesn't match.

**Comment by PrzemyslawKlys** [comment]
The fix for that ScrollX behavior is to add `width="100%">` into Table

Current:

```html
<table id="DT-HhhZKTpC" class="display compact">
```

Needed:
```html
<table id="DT-HhhZKTpC" class="display compact" width="100%">
```

Test it and let me know. I don't see the same problem as you do. Changing false/true works as expected. 

About docs:

When updating docs you need to go by typing two/three # and then my VSCode generates it for me. 

```
function New-ChartToolbar {
    <#
    .SYNOPSIS
    Short description
    
    .DESCRIPTION
    Long description
    
    .PARAMETER Download
    Parameter description
    
    .PARAMETER Selection
    Parameter description
    
    .PARAMETER Zoom
    Parameter description
    
    .PARAMETER ZoomIn
    Parameter description
    
    .PARAMETER ZoomOut
    Parameter description
    
    .PARAMETER Pan
    Parameter description
    
    .PARAMETER Reset
    Parameter description
    
    .PARAMETER AutoSelected
    Parameter description
    
    .EXAMPLE
    An example
    
    .NOTES
    General notes
    #>
    
    [alias('ChartToolbar')]
    [CmdletBinding()]
    param(
        [switch] $Download,
        [switch] $Selection,
        [switch] $Zoom,
        [switch] $ZoomIn,
        [switch] $ZoomOut,
        [switch] $Pan,
        [switch] $Reset,
        [ValidateSet('zoom', 'selection', 'pan')][string] $AutoSelected = 'zoom'
    )

    [PSCustomObject] @{
        ObjectType = 'Toolbar'
        Toolbar    = @{
            #Show         = $Show.IsPresent
            #tools        = [ordered] @{
            download     = $Download.IsPresent
            selection    = $Selection.IsPresent
            zoom         = $Zoom.IsPresent
            zoomin       = $ZoomIn.IsPresent
            zoomout      = $ZoomOut.IsPresent
            pan          = $Pan.IsPresent
            reset        = $Reset.IsPresent
            #}
            autoSelected = $AutoSelected
        }
    }
}
```

Then when I do that I use PlatyPS to generate an update for me. PlatyPS when rerun regenerates docs from that data I think + it adds all the types/missing stuff.

**Comment by PrzemyslawKlys** [comment]
Tested fix with following code:

```powershell
$PSDefaultParameterValues["New-HTMLContent:SelectorColor"] = "DeepSkyBlue"
$PSDefaultParameterValues["New-HTMLContent:HeaderBackGroundColor"] = "DeepSkyBlue"
$PSDefaultParameterValues["New-HTMLTable:DisableColumnReorder"] = $true
$PSDefaultParameterValues["New-HTMLTable:HideFooter"] = $true
$PSDefaultParameterValues["New-HTMLTable:DisablePaging"] = $true
$PSDefaultParameterValues["New-HTMLTable:ScrollX"] = $true
$PSDefaultParameterValues["New-HTMLTable:Buttons"] = ("copyHtml5", "excelHtml5", "csvHtml5", "pdfHtml5")

$Title = "Summary of not used folders"

$SummaryNotUsedFolders = Get-Process | Select -First 50 -Property Name, Id, FileVersion

New-HTML -TitleText $Title -FilePath $PSScriptRoot\Testoooor.html -UseCssLinks -UseJavaScriptLinks {
    New-HTMLTab -Name $Title {
        New-HTMLContent -HeaderText $Title {
            New-HTMLPanel {
                New-HTMLTable -DataTable $SummaryNotUsedFolders -ResponsivePriorityOrder Path, TotleBytes, TotalMBytes, TotalGBytes, DirCount, FileCount, DirFailed, FileFailed {
                    New-HTMLTableCondition -Name "DirFailed" -Type number -Operator gt -Value 0 -BackgroundColor Orange
                }
            }
        }
    }
} -ShowHTML
```

**Comment by codaamok** [comment]
Yes, https://github.com/EvotecIT/PSWriteHTML/commit/d20a492b61c17ff481f0746cbd89e4418a04e8a1 resolves this!
