### ISSUE TITLE
New-HTMLListItem & hyperlinks in a new TAB

### ISSUE THREAD

**Issue by tomerikko** [EvotecIT/PSWriteHTML#223]
There is an example called 'Example-Texts", in it you show how to use hyperlinks.

can we somehow open the hyperlink in a new TAB?
similar to using "target=”_blank”" inside an "<a href=...."when you write an HTML code.

example code;
New-HTMLListItem -Text "[Participate](https://evotec.xyz)"-FontSize 15

**Comment by PrzemyslawKlys** [comment]
You will have to resort to something like this:

```
New-HTMLText -Text @(
    'This is some text with HTML inside <a href="http://example.com/" target="_blank">Hello, world!</a>'
)
New-HTMLList {
    New-HTMLListItem -Text '[Link2](https://evotec.xyz) SomeText (TestingText in brackets) and more [more test in brackets] (and more)'
    New-HTMLListItem -Text 'Using standard link <a href="http://example.com/" target="_blank">Hello, world!</a>'
}
```

According to this: https://stackoverflow.com/questions/4425198/can-i-create-links-with-target-blank-in-markdown there are multiple ways markdown defines it, depending on platform using it. So I could pick one and implement, but not sure if it's worth the effort.

**Comment by PrzemyslawKlys** [comment]
You can also use:

```powershell
New-HTMLList {
    New-HTMLListItem -Text '[Link2](https://evotec.xyz) SomeText (TestingText in brackets) and more [more test in brackets] (and more)'
    New-HTMLListItem -Text 'Using standard link ', (New-HTMLLink -Text 'Hello World' -Target "_blank" -HrefLink 'https://evotec.xyz')
}
```

Which seems nice way to not play with HTML at all.
