### ISSUE TITLE
 New-ChartAxisX -name not working

### ISSUE THREAD

**Issue by tomerikko** [EvotecIT/PSWriteHTML#225]
Hi, 
i Noticed that on my report lately the X Axis no longer shows the dates, it shows numbers (1, 2, 3, 4...)
i started checking this but could not find a good solution, then i looked on your example here:

https://github.com/EvotecIT/PSWriteHTML/blob/b906cbfe975eb5df9bb827da06d9a510febede70/Examples/Example-Charts/Example-ChartsLine.ps1

and it has the same problem.
i use ver: 0.0.148

ideas?

![image](https://user-images.githubusercontent.com/10564814/114609753-6d27f380-9c9f-11eb-9b41-5232468f36d7.png)

**Comment by PrzemyslawKlys** [comment]
I've broken it while rebuilding charts. Sorry. Will try to fix it back.

**Comment by PrzemyslawKlys** [comment]
Fixed: 

![image](https://user-images.githubusercontent.com/15063294/114614713-289f5680-9ca5-11eb-80f1-150bc102311d.png)


Will be in the next version - whenever that is... going back to 146 should fix it, as changes where introduced on 147

**Comment by tomerikko** [comment]
thanks!  appreciated your commitment on this tool that makes our life so awesome.
