### ISSUE TITLE
disable labels on line on linechart

### ISSUE THREAD

**Issue by solipsist01** [EvotecIT/PSWriteHTML#232]
If we take the following example:
https://github.com/EvotecIT/PSWriteHTML/blob/master/Examples/Example-Charts/Example-ChartsLine.ps1

How would one disable / remove the labels on the linechart ?
I have scoured through the example and docs, but couldn't find such parameter.
Can someone point me in the right direction ?

Thank you !

![image](https://user-images.githubusercontent.com/16472221/116689392-592b0400-a9b8-11eb-9166-42f4c2a947c1.png)

**Comment by PrzemyslawKlys** [comment]
```powershell
    New-HTMLPanel {
        New-HTMLChart -Title 'Incidents Reported vs Solved' -TitleAlignment center {
            New-ChartDataLabel
            New-ChartAxisX -Name 'Jan', 'Feb', 'Mar', 'Apr', 'May', 'Jun', 'Jul', 'Aug', 'Sep'
            New-ChartLine -Name 'Incidents per month' -Value 10, 41, 35, 51, 49, 62, 69, 91, 148 -Color Red -Cap square -Dash 5
            #New-ChartLine -Name 'Incidents per month resolved' -Value 5, 10, 20, 31, 49, 62, 69, 91, 148 -Color Green -Curve stepline -Width 10
        }
    }
```

Basically add `New-ChartDataLabel` which by default overwrites any data label default settings, including disabling labels. Yoou need to explicitly enable it to show.

**Comment by PrzemyslawKlys** [comment]
It may not work in the production version, as I've improved it in PreRelease which is released to PSGallery as prerelease as it requires more testing and fixes for other stuff.

**Comment by solipsist01** [comment]
Works perfectly in the pre-release :) Thanks !
