### ISSUE TITLE
ChartBar empty when last 2 values are 0

### ISSUE THREAD

**Issue by tomerikko** [EvotecIT/PSWriteHTML#234]
Hey PrzemyslawKlys, 
i think i might had found a new bug with ChartBar

if the last 2 bars values are 0, none of the bars will be drawn.

so in the example below, it will work as expected, but if you change the value to 2,3,0,0 == none of the bars will be drawn.

```powershell
  New-HTML   -TitleText "title" -AddComment  -Online -FilePath "c:\temp\tt.html"  {   
                                    New-HTMLChart  -TitleAlignment center -TitleFontSize 12 -Height 200 {
                                        New-ChartBarOptions -DataLabelsColor black -Vertical
                                        New-ChartLegend -Name "a","b", "c","d" # , "%"
                                        New-ChartBar -Name "name" -Value 2,3,4,5
                                        IF ($_.Name -like "GHW_Level1"){Write-Host "            ...GHW! |$($_.Name )| $( $_.Reader)  $( $_.Candidate)  $($_.Contributor)  $($_.Publisher)" -ForegroundColor Yellow}
                                        sleep 1
			                    		
                                    }
    }-ShowHTML
```

![image](https://user-images.githubusercontent.com/10564814/116983876-e62cd080-acca-11eb-8641-7f571ae68ee1.png)

**Comment by PrzemyslawKlys** [comment]
Does it behave the same on preview?

**Comment by tomerikko** [comment]
what do you mean on "preview" ?

**Comment by PrzemyslawKlys** [comment]
It's now fixed. You can test it using Install-Module PSWriteHTML -AllowPrerelease. Production version will be related later this month when I get to fix some outstanding issues.

**Comment by tomerikko** [comment]
i rather wait for the official release rather than use a pre-release but man you are a rock star!
thanks for the quick solution, and i have a bunch of fixes that i wait for now, so hope to see the next release out soon :)
Tomer.
