### ISSUE TITLE
Challenging to load html 340MB report 

### ISSUE THREAD

**Issue by Jekastr** [EvotecIT/PSWriteHTML#240]
We have a script that collects a tone of data and HTML output is realy large in size, more than 300MB. Is there any way to shrink the szie of html report or get it loaded by the browser?

**Comment by PrzemyslawKlys** [comment]
Read up: https://evotec.xyz/advanced-html-reporting-using-powershell/

Interesting read for you is in section: PSWriteHTML Performance Improvements

**Comment by PrzemyslawKlys** [comment]
The alternative is to use Navigation and split per pages - new feature in 0.0.150, but highly experimental and not ready for production as changes can occur pretty quick in next few releases

- https://github.com/EvotecIT/PSWriteHTML/blob/master/Examples/Example41-Navigation01
- https://github.com/EvotecIT/PSWriteHTML/tree/master/Examples/Example41-NavigationTopMenu
- https://github.com/EvotecIT/PSWriteHTML/tree/master/Examples/Example41-NavigationFloat
- https://github.com/EvotecIT/PSWriteHTML/tree/master/Examples/Example41-Navigation02

The idea is you can have different pages, having different data. it's less portable - but allows to work with larger data.

**Comment by Jekastr** [comment]
> Read up: https://evotec.xyz/advanced-html-reporting-using-powershell/
> 
> Interesting read for you is in section: PSWriteHTML Performance Improvements
Great, I will try Javascript option and see if it helps. If not, do you have any articales how to set up any web server for the AjaxJSON option?

**Comment by PrzemyslawKlys** [comment]
You can also try option `Minify` for `New-HTML` which requires [PSParseHTML](https://github.com/EvotecIT/PSParseHTML) module. Not sure what will be the gain and whether everything will work as expected tho. 

As for AjaxJSON - any server will do - I use IIS myself. As soon as navigation will be "production-ready" and I will be happy with the new project that utilizes it - this would be my recommendation. Going for advanced navigation with separate pages, javascript (still better) and accessed via IIS/apache or any other server to serve static content. 

![image](https://user-images.githubusercontent.com/15063294/120240355-a375fe00-c260-11eb-957b-201d9a32237a.png)

340MB HTML file, even if it will be responsive via JavaScript store it's not best idea ;-) 

Maybe I'll do the blog post later on - how to create static page on IIS with access protected via Windows Authentication.

**Comment by PrzemyslawKlys** [comment]
Is your issue resolved?

**Comment by Jekastr** [comment]
Sorry. Yes you can close the ticket. Thank you so much for your help.. The
json approach is really what I was looking for!!
