### ISSUE TITLE
Query on code in New-TableConditionalFormatting

### ISSUE THREAD

**Issue by codaamok** [EvotecIT/PSWriteHTML#25]
Hello

What language is within $Condition1, $Condition3 and $Condition 5, is it jQuery?

I'm trying to implement a wildcard operator if $Condition.Type -eq string.

**Comment by PrzemyslawKlys** [comment]
This is badly implemented Js/Jquery. 

Materials for improvements:

- https://datatables.net/reference/option/rowCallback
- https://datatables.net/forums/discussion/42441/conditional-formatting
- https://datatables.net/forums/discussion/40652/conditional-formatting-on-some-of-the-cells-in-my-table
- https://datatables.net/forums/discussion/36595/change-the-row-color-based-on-column-data
- https://stackoverflow.com/questions/19731030/how-do-i-apply-conditional-formatting-using-datatables-js
- https://stackoverflow.com/questions/50010208/datatables-js-conditional-formatting-based-on-rank-of-data-value/50010364#50010364

Actually, I want to modify this command to support a lot more things. Right now it works only via Columns. So check the value in column X and if it 's Y set color. What would be great is having more complicated things such as: 
- check if column X has the value 'This is some value' and column Y has value False  make it red
- check if column X has the value 'This is some value' and column Y  has value True make it green

But it means you would need to catch row of value in Column X and check the same row for column Y.

**Comment by jojiklmts** [comment]
> This is badly implemented Js/Jquery.
> 
> Materials for improvements:
> 
> * https://datatables.net/reference/option/rowCallback
> * https://datatables.net/forums/discussion/42441/conditional-formatting
> * https://datatables.net/forums/discussion/40652/conditional-formatting-on-some-of-the-cells-in-my-table
> * https://datatables.net/forums/discussion/36595/change-the-row-color-based-on-column-data
> * https://stackoverflow.com/questions/19731030/how-do-i-apply-conditional-formatting-using-datatables-js
> * https://stackoverflow.com/questions/50010208/datatables-js-conditional-formatting-based-on-rank-of-data-value/50010364#50010364
> 
> Actually, I want to modify this command to support a lot more things. Right now it works only via Columns. So check the value in column X and if it 's Y set color. What would be great is having more complicated things such as:
> 
> * check if column X has the value 'This is some value' and column Y has value False  make it red
> * check if column X has the value 'This is some value' and column Y  has value True make it green
> 
> But it means you would need to catch row of value in Column X and check the same row for column Y.

Exactly What I am looking for.

**Comment by PrzemyslawKlys** [comment]
I believe you can already do a lot of that as it has been improved a lot since original post.

- https://evotec.xyz/advanced-html-reporting-using-powershell/ - section `contditional formatting in HTML Tables`

**Comment by jojiklmts** [comment]
Awesome! I was looking at New-TableConditionGroup but could not figure out the syntax. Now I see it. Many thanks
