### ISSUE TITLE
line breaks in tables

### ISSUE THREAD

**Issue by raymix** [EvotecIT/PSWriteHTML#273]
Hi 

I'm trying to include line breaks in table cells (<td>) to make them multi-line. I've tried adding <br>, <hr>, <p> tags, but they just end up being rendered as text. 

Using "`n" and "`r" kinda works when inspecting table using browser developer tools - I can see that both text and html code is breaking my text correctly, but it is still being rendered in one long line in table.

I have tried adding `-Wordbreak` to `Table` and` -NewLine` to `TableOption` cmdlets, but they had no effect.

Thanks

**Comment by PrzemyslawKlys** [comment]
If you want to play with Html in the tables you need to use `InvokeHTMLTags` switch. Otherwise, it treats HTML tags as text. 

Natively you can do it using the proper new line PowerShell way.

```powershell
$Array = @(
    [PSCustomObject] @{
        Test  = "Multiline" + [System.Environment]::NewLine + "Text"
        Test2 = "Multiline" + [System.Environment]::NewLine + "Text"
        Test3 = "Multiline" + [System.Environment]::NewLine + "Text"
    }
    [PSCustomObject] @{
        Test  = "Multiline" + [System.Environment]::NewLine + "Text"
        Test2 = "Multiline" + [System.Environment]::NewLine + "Text"
        Test3 = "Multiline" + [System.Environment]::NewLine + "Text"
    }
)
$Array | Out-HtmlView
```

**Comment by raymix** [comment]
Thank you so much, it works great @PrzemyslawKlys 

Here's what I ended up using:
```
@("One", "Two", "Three") -join [System.Environment]::NewLine
```
