### ISSUE TITLE
Sorting by date Improvements

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWriteHTML#28]
Even thou #18 was fixed I believe we should try and improve it to be a bit more automatic so that PowerShell dates would be supported no matter what.

**Comment by PrzemyslawKlys** [comment]
Referencing pull: https://github.com/EvotecIT/PSWriteHTML/pull/20
May need improvement to try and automate date handing

**Comment by whoot** [comment]
This is still an issue if you are using something like this:
date.tostring("dd.MM.yyyy HH:mm:ss")

![grafik](https://user-images.githubusercontent.com/8066322/64126168-0f39e700-cdad-11e9-9f5b-6b797989f281.png)

Sorts first by day, then by month and then by year.

**Comment by PrzemyslawKlys** [comment]
I guess I will have to take a look at it. I've been avoiding this date problem since I expect it to not be trivial;/

**Comment by PrzemyslawKlys** [comment]
This was resolved in March 2021. Blog post: https://evotec.xyz/advanced-html-reporting-using-powershell/ describes how to use data sorting and how to use it in conditionals.
