### ISSUE TITLE
-LegendPosition parameter requires lower case argument in New-ChartLegend function (case sensitivity)

### ISSUE THREAD

**Issue by n8-mills** [EvotecIT/PSWriteHTML#283]
I developed a solution using one of the "charts" examples, playing with the -LegendPosition parameter by inputting "Right" broke the chart output.  After some trial and error it became clear that -LegendPosition is case sensitive.  I recommend including .ToLower() for this parameter within the New-ChartLegend function.

**Comment by PrzemyslawKlys** [comment]
ye, there are probably a few more like that. Unfortunately, javascript is case sensitive so it has to be exactly as the author of the library wants it.
