### ISSUE TITLE
How to define hidden details

### ISSUE THREAD

**Issue by noaboa97** [EvotecIT/PSWriteHTML#286]
So I was wondering how the hidden details are getting choosen or how I can define them.

I create a custom PSCustomObject with Name, Path, Id, AccessRights, AccessRightGroups.

The AccessRightGroup are also a PSCustomObject which I would like to add into the hidden details. 

For example Get-Process if piped to Out-HtmlView will have a blue (+) and additional detail/information is written there. Can I define that somehow? Or is there a workaround?

**Comment by PrzemyslawKlys** [comment]
You can choose ResponsivePriorityOrder - this would give you what you want. You can also `New-HTMLTableHeader` and choose ResponsiveOperations and have more granular control if you would like some 

```powershell
        New-HTMLTable -DataTable $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount', 'WorkingSet' -ResponsiveOperations none

        } -ResponsivePriorityOrder 'ID', 'HandleCount', 'WorkingSet'
```

You can also use `PriorityProperties` this will change the order of columns as you want it without affecting your PSCustomObject

**Comment by noaboa97** [comment]
Thanks for your response.


So `$report | Out-HtmlView -ResponsivePriorityOrder 'Name', 'Path', 'Id' , 'AccessRights' ` hasn't worked for me. Same result as before.

But:

```
New-HTML{

    New-HTMLTable -DataTable $report -HideFooter {

            New-HTMLTableHeader -Names 'AccessRightGroups' -ResponsiveOperations none

    } -ResponsivePriorityOrder 'Name', 'Path', 'Id' , 'AccessRights' -DisablePaging
        
} -ShowHTML
```
has worked fine. However `New-HTML {} -ShowHTML` was missing.

Now another question. How can I tell that it should display the array object nicely? 
Currently it shows an Object like `@{Name=AD-Group; Id=9999; Rights=Write (200)}`
And Objects in an Array like `System.Object[]`

Is there somewhere a documentation for the functions and their parameters where I could read about that? Or just the articles with the usecases?

**Comment by noaboa97** [comment]
I found a workaround and added the objects from the array to the object.

foreach($acr2 in $accessrights2){
        
        $object | Add-Member -MemberType NoteProperty -Name $acr2.name -Value $acr2.Rights
        
        
        }

But thats not that nice. I would like to add the object array directly.

Also it's not displayed to nicley and has makes it hard to read. Is there a way to align the name and values like in a table? So it's easy to read?

**Comment by PrzemyslawKlys** [comment]
If it would be an array of strings yes. If it's an array of objects not really because I can't be sure what you may want to do it. What if there are 50 array objects there? It just doesn't play well. But array of strings is possible to convert automatically.

```powershell
New-HTML {
    New-HTMLTableOption -DataStore JavaScript -ArrayJoin -BoolAsString
    New-HTMLTable ... 
}

**Comment by noaboa97** [comment]
Okay thanks. Then I will use the workaround. Even though  the list also isn't to nice since the name and value have no spaces and is hard to read. 

Well I would expect, that the same object types or objects with the same Members get grouped and would show in a nice list. 
If there are two diffrent objects types then create two lists and also group those who are the same. 

Thank you!
