### ISSUE TITLE
ChartLine Color Issue

### ISSUE THREAD

**Issue by MathiasBaden27** [EvotecIT/PSWriteHTML#298]
Hi - Anyone know why is get different colors on the number bullets? Check image here:
![image](https://user-images.githubusercontent.com/35427700/144761003-5fbef318-42c3-4b6b-a188-77b1f331641d.png)

**Comment by PrzemyslawKlys** [comment]
Always provide reproducible code please.

**Comment by PrzemyslawKlys** [comment]
No details provided
