### ISSUE TITLE
How do you add Html to Table

### ISSUE THREAD

**Issue by crshnbrn66** [EvotecIT/PSWriteHTML#30]
I have a constructed object that has an html link in it how do I get it to be "clickable" from New-Htmltable

**Comment by crshnbrn66** [comment]
$customobject = [pscustomobject]@{user = 'user1'
name = 'thom'
link = 'https://powershellposse.com'}
new-html -titletext 'test' -useCsslinks:$true -useJavascriptlinks:$true -filepath "c:\temp\thom.html"{
New-HTMLTab -tabname 'summary'{
 New-HTMLContent -HeaderText 'summary'{
    new-htmltable -DataTable $customobject -InvokeHTMLTags -HideFooter
    }
 }
}

**Comment by PrzemyslawKlys** [comment]
Use New-htmltable with -InvokeHtmltags switch

**Comment by PrzemyslawKlys** [comment]
You may need to modify that object to add html to it

**Comment by PrzemyslawKlys** [comment]
```PowerShell
$customobject = [pscustomobject]@{user = 'user1'
    name                               = 'thom'
    link                               = 'https://powershellposse.com'
    activeLink                         = '<a href="https://powershellposse.com">You can use here text or again link</a>'
}
New-HTML -titletext 'test' -useCsslinks:$true -useJavascriptlinks:$true -filepath $PSScriptRoot\Teo.html -ShowHTML {
    New-HTMLTab -tabname 'summary' {
        New-HTMLContent -HeaderText 'summary' {
            New-HTMLTable -DataTable $customobject -InvokeHTMLTags -HideFooter
            New-HTMLTable -DataTable $customobject -HideFooter
        }
    }
}
```

InvokeHTMLTags is responsible making links and other HTML stuff "active". Otherwise, activeLink would be just a text-based representation of it. But you still need to build that HTML object yourself.

**Comment by crshnbrn66** [comment]
Perfect ... Thank you

**Comment by crshnbrn66** [comment]
Thank you
