### ISSUE TITLE
Rename the "Search" Label

### ISSUE THREAD

**Issue by gcorly** [EvotecIT/PSWriteHTML#303]
Hi all, 

I think it's not so difficult but I cannot find wher I have to change the "Search" label (even if everybody should understand, I have  some requests to modify it).

Somebody can help me to modify this ?

Thank you

![image](https://user-images.githubusercontent.com/11346602/146164815-72101347-ba77-4a0e-970f-9322628bfafd.png)

**Comment by PrzemyslawKlys** [comment]
Configuration is not exposed in any way at the moment.

**Comment by PrzemyslawKlys** [comment]
But maybe you're willing to add this for us?

- https://datatables.net/reference/option/language
- https://www.datatables.net/examples/basic_init/language.html

I guess New-TableLanguage which would modify language property with proper entries

**Comment by PrzemyslawKlys** [comment]
Will be in the next release

```powershell
New-HTML -TitleText "Example41 - Table" -FilePath "$PSScriptRoot\Example41.html" {
    New-HTMLSection -HeaderText "Testing" -HeaderTextAlignment center -Content {
        New-HTMLTable -DataTable $Values {
            New-TableLanguage -Search 'Find' -PaginateFirst 'piwer' -EmptyTable 'testing'
            New-HTMLTableConditionGroup {
                New-HTMLTableCondition -Name 'Test1' -Value 1 -ComparisonType number
                New-HTMLTableCondition -Name 'Test2' -Value 2 -ComparisonType number
            } -BackgroundColor Salmon -FailBackgroundColor Goldenrod -Logic OR -HighlightHeaders 'Test1', 'Test2', 'DisplayName', 'DomainName'
        } -DataStore JavaScript
    }
} -ShowHTML -Online
```

**Comment by gcorly** [comment]
> But maybe you're willing to add this for us?
> 
> * https://datatables.net/reference/option/language
> * https://www.datatables.net/examples/basic_init/language.html
> 
> I guess New-TableLanguage which would modify language property with proper entries

I don't think I'm good enough to do this unfortunately. 
I don't really know anything about JS, I only understand PS but to be honest, not good enough to implement features :(

Btw, thank you for your answer, I will give you an update if I manage to do something

**Comment by PrzemyslawKlys** [comment]
Its already added. Will show up in new release.
