### ISSUE TITLE
Responsive Table Question

### ISSUE THREAD

**Issue by crshnbrn66** [EvotecIT/PSWriteHTML#32]
I want to force the browser to show the rolled up items in a list I have.
Such that I have a list of two items in a row I only want the first item to show and the second item to only show when the + is clicked.

This behavior works when resizing the browser window. I'd like it to be a default though. How do you override the css behavior to get the desired result

**Comment by codaamok** [comment]
I think what you're after is discussed here near the bottom: https://evotec.xyz/all-your-html-tables-are-belong-to-us/

**Comment by codaamok** [comment]
Specifically, `-ResponivePriorityOrder` or `-ResponsivePriorityOrderIndex`

**Comment by PrzemyslawKlys** [comment]
I believe he wants something different. To show always one item, and one item only. And when someone clicks plus it shows up. Right?

**Comment by crshnbrn66** [comment]
exactly... I want the default for the items to be rolled up

**Comment by PrzemyslawKlys** [comment]
This is doable using https://datatables.net/extensions/responsive/classes

![image](https://user-images.githubusercontent.com/15063294/62732737-5ee2f800-ba25-11e9-8f3e-1cba3250ae5d.png)

- none - Column will never be visible, regardless of the browser width, but the data will be shown in a child row

Need to think on how to implement it where it makes sense, so it has more use cases than one. For this case, it would mean getting all column names and assigning all columns value none.

**Comment by PrzemyslawKlys** [comment]
Ok, this seems like an easy fix:

```
                            <thead>
                                <tr>
                                    <th class='all'>Name</th>
                                    <th class='none'>Id</th>
                                    <th class='none'>HandleCount</th>
                                    <th class='none'>WorkingSet</th>
                                </tr>
                            </thead>
```

So what New-HTMLTable needs is a way to control class per Header. When you set any of the columns to None you need to set rest to All. 

Was thinking 

```
New-HTMLTable -HideColumns Id,HandleCount,WorkingSet
```

And it would set class 'none' for all and rest set to 'all'.

However, I believe this would be a waste of the feature. If you take a look at what is available you can control this really a lot, deciding which column is visible on which device and in what way. 

> You can tell Responsive what columns should be visible on different devices through the use of class names on the columns. The breakpoints are horizontal screen resolutions and the defaults are set for common devices:
> 
> desktop x >= 1024px
> tablet-l (landscape) 768 <= x < 1024
> tablet-p (portrait) 480 <= x < 768
> mobile-l (landscape) 320 <= x < 480
> mobile-p (portrait) x < 320
> You may leave the -[lp] option from the end if you wish to just target all tablet or mobile devices. Additionally, add min-, max- or not- as a prefix to the class name to perform logic operations. For example, not-mobile would cause a column to appear as visible on desktop and tablet devices, while min-tablet-l would require at least a horizontal width of 768 for the browser window to be shown, and be shown at all sizes larger.
> 
> Additionally, there are three special class names:
> 
> all - Always display
> none - Don't display as a column, but show in the child row
> never - Never display
> control - Used for the column responsive.details.type option.
> Please refer to the Responsive manual for further details of these options.
> 
> This example shows the salary column visible on a desktop only - office requires a tablet, while the position column requires a phone in landscape or larger. The name column is always visible and the start date is never visible.
> 
> This can be useful if you wish to change the format of the data shown on different devices, for example using a combination of mobile and not-mobile on two different columns would allow information to be formatted suitable for each device type.
> 

@codaamok what do you think? @crshnbrn66  any thoughts?

**Comment by PrzemyslawKlys** [comment]
After some thinking, I believe

New-HTMLTableHeader will get ResponiveOperations. One can define an operation per column name(s). Everything that's not defined will get 'all'. 

```
function New-HTMLTableHeader {
    [alias('TableHeader', 'EmailTableHeader')]
    [CmdletBinding()]
    param(
        [string[]] $Names,
        [string] $Title,
        [RGBColors] $Color,
        [RGBColors] $BackGroundColor,
        [int] $FontSize,
        [ValidateSet('normal', 'bold', 'bolder', 'lighter', '100', '200', '300', '400', '500', '600', '700', '800', '900')][string] $FontWeight,
        [ValidateSet('normal', 'italic', 'oblique')][string] $FontStyle,
        [ValidateSet('normal', 'small-caps')][string] $FontVariant,
        [string] $FontFamily,
        [ValidateSet('left', 'center', 'right', 'justify')][string] $Alignment,
        [ValidateSet('none', 'line-through', 'overline', 'underline')][string] $TextDecoration,
        [ValidateSet('uppercase', 'lowercase', 'capitalize')][string] $TextTransform,
        [ValidateSet('rtl')][string] $Direction,
        [switch] $AddRow,
        [int] $ColumnCount,
        [ValidateSet(
            'all',
            'none',
            'never',
            'desktop',
            'not-desktop',
            'tablet-l',
            'tablet-p',
            'mobile-l',
            'mobile-p',
            'min-desktop',
            'max-desktop',
            'tablet',
            'not-tablet',
            'min-tablet',
            'max-tablet',
            'not-tablet-l',
            'min-tablet-l',
            'max-tablet-l',
            'not-tablet-p',
            'min-tablet-p',
            'max-tablet-p',
            'mobile',
            'not-mobile',
            'min-mobile',
            'max-mobile',
            'not-mobile-l',
            'min-mobile-l',
            'max-mobile-l',
            'not-mobile-p',
            'min-mobile-p',
            'max-mobile-p'
        )][string] $ResponiveOperations

    )
```

**Comment by crshnbrn66** [comment]
would it be possible for you to provide an example of what you mean?

**Comment by PrzemyslawKlys** [comment]
You leave responsive as is (generated by PSWriteHTML). What you have to modify is the HTML Table itself by adding a class parameter to THEAD for each row with information on how each column has to behave.

![image](https://user-images.githubusercontent.com/15063294/62758331-5c60bc80-ba7e-11e9-9358-8d862293b335.png)

**Comment by PrzemyslawKlys** [comment]
The usage would be:

```Powershell
Import-Module .\PSWriteHTML.psd1 -Force

$Processes = Get-Process | Select-Object -First 2 -Property Name, ID, HandleCount, WorkingSet
$Title = 'My title'

New-HTML -TitleText $Title -UseCssLinks:$true -UseJavaScriptLinks:$true -FilePath $PSScriptRoot\Example13.html {

    <#
    New-HTMLContent -HeaderText '0 section' {
        New-HTMLPanel {
            New-HTMLTable -ArrayOfObjects $Processes -HideFooter #-ImmediatelyShowHiddenDetails
        }
        New-HTMLPanel {
            New-HTMLTable -ArrayOfObjects $Processes -HideFooter
        }
        New-HTMLPanel {
            New-HTMLTable -ArrayOfObjects $Processes -HideFooter
        }
        New-HTMLPanel {
            New-HTMLTable -ArrayOfObjects $Processes -HideFooter
        }
        New-HTMLPanel {
            New-HTMLTable -ArrayOfObjects $Processes -HideFooter
        }
    }
    #>
    New-HTMLContent -HeaderText '1 section' {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount' -ResponsiveOperations none
        } -ImmediatelyShowHiddenDetails
    }
    New-HTMLContent -HeaderText '2 section' {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount' -ResponsiveOperations none
        } -ImmediatelyShowHiddenDetails -HideShowButton
    }
    New-HTMLContent -HeaderText '2 section' {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount' -ResponsiveOperations none
        } -ImmediatelyShowHiddenDetails -HideShowButton -DisableResponsiveTable
    }
    <#
    New-HTMLContent -Invisible {
        New-HTMLPanel {
            New-HTMLTable -ArrayOfObjects $Processes -HideFooter
        }
        New-HTMLPanel {
            New-HTMLTable -ArrayOfObjects $Processes -HideFooter

        }
    }
    New-HTMLPanel {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter

    }
    #>
} -ShowHTML
```

However, I have found some bug I introduced in the last release and need to fix this before delivering.

**Comment by crshnbrn66** [comment]
stellar thanx for the update.

**Comment by PrzemyslawKlys** [comment]
```
Update-Module PSWriteHTML
```

Should work after that.

**Comment by PrzemyslawKlys** [comment]
```
    New-HTMLContent -HeaderText '1 section' {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount' -ResponsiveOperations none
        } -ImmediatelyShowHiddenDetails
    }
    New-HTMLContent -HeaderText '2 section' {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount' -ResponsiveOperations none
        } -ImmediatelyShowHiddenDetails -HideShowButton
    }
    New-HTMLContent -HeaderText '3 section' {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount' -ResponsiveOperations none
        } -ImmediatelyShowHiddenDetails -HideShowButton -DisableResponsiveTable
    }
    New-HTMLContent -HeaderText '4 section' {
        New-HTMLTable -ArrayOfObjects $Processes -HideFooter {
            New-HTMLTableHeader -Names 'ID', 'HandleCount', 'WorkingSet' -ResponsiveOperations none
        }
    }
```

In your case section 4 will be what you want, however, you can mix it up with new options
