### ISSUE TITLE
New-HTMLTableCondition doesn't work as expected

### ISSUE THREAD

**Issue by SapnaSoni123** [EvotecIT/PSWriteHTML#325]
I have the following code here:

$baselinejson = Get-Content somejson.json | ConvertFrom-Json
          $newjson = Get-Content newjson.json | ConvertFrom-Json

          $baselinejson,$newjson | Out-HtmlView -Compare -HighlightDifferences -Filtering -WordBreak break-all -
          {
            New-HTMLTableCondition -Name 'Status' -ComparisonType string -Operator eq -Value $false -BackgroundColor Red -Color White
          }

Issue is that the Status column with false values do not change the font color from **black** to **white** as specified in New-HTMLTableCondition. 
Am I missing something here? Or is it not correct to use it this way?

**Comment by PrzemyslawKlys** [comment]
Most likely ComparisonType needs to be set to bool?

**Comment by SapnaSoni123** [comment]
No, just tried that and it does not work with bool also.
{
 New-HTMLTableCondition -Name 'Status' -ComparisonType bool -Operator eq -Value $false -BackgroundColor Red -Color White
}

**Comment by PrzemyslawKlys** [comment]
You sure 

```powershell
 $baselinejson,$newjson | Out-HtmlView -Compare -HighlightDifferences -Filtering -WordBreak break-all -
      {
        New-HTMLTableCondition -Name 'Status' -ComparisonType string -Operator eq -Value $false -BackgroundColor Red -Color White
      }
``` 

Is correct? What about that `-` at the end?

**Comment by SapnaSoni123** [comment]
"-" at the end is added by mistake in the comment. Following is the correct code:
$baselinejson,$newjson | Out-HtmlView -Compare -HighlightDifferences -Filtering -WordBreak break-all
      {
        New-HTMLTableCondition -Name 'Status' -ComparisonType string -Operator eq -Value $false -BackgroundColor Red -Color White
      }
But it still does not work

**Comment by PrzemyslawKlys** [comment]
Without some reproducible code it will be hard to help you. I don't have the json files. Can you replicate it on smaller example?

**Comment by SapnaSoni123** [comment]
Okay, will the below json work?

$baselinejson = {
  "auditReportVersion": 4,
  "vulnerabilities": {
    "@pmmmwh/react-refresh-webpack-plugin": {
      "name": "@pmmmwh/react-refresh-webpack-plugin",
      "severity": "high",
      "isDirect": false,
      "via": [
        "ansi-html"
      ],
      "effects": [
        "react-scripts"
      ],
      "range": "<=0.5.0-rc.6",
      "nodes": [
        "node_modules/@pmmmwh/react-refresh-webpack-plugin"
      ],
      "fixAvailable": {
        "name": "react-scripts",
        "version": "5.0.1",
        "isSemVerMajor": true
      }
    }

$newjson= {
  "auditReportVersion": 2,
  "vulnerabilities": {
    "@pmmmwh/react-refresh-webpack-plugin": {
      "name": "@pmmmwh/react-refresh-webpack-plugin",
      "severity": "high",
      "isDirect": false,
      "via": [
        "ansi-html"
      ],
      "effects": [
        "react-scripts"
      ],
      "range": "<=0.5.0-rc.6",
      "nodes": [
        "node_modules/@pmmmwh/react-refresh-webpack-plugin"
      ],
      "fixAvailable": {
        "name": "react-scripts",
        "version": "5.0.1",
        "isSemVerMajor": true
      }
    }

**Comment by PrzemyslawKlys** [comment]
It's a nested object, isn't it? So how are you comparing it?

![image](https://user-images.githubusercontent.com/15063294/175552190-c55667ea-6252-44fd-a6db-9986a2d5be2e.png)

**Comment by PrzemyslawKlys** [comment]
```powershell
$baselinejson = Get-Content old.json | ConvertFrom-Json
$newjson = Get-Content new.json | ConvertFrom-Json

$baselinejson, $newjson | Out-HtmlView -Compare -Filtering -WordBreak break-all {
    New-HTMLTableCondition -Name 'Status' -ComparisonType string -Operator eq -Value $false -Color Blue -BackgroundColor YourPink
} -FlattenObject
```

![image](https://user-images.githubusercontent.com/15063294/175553300-087b7699-22fa-46b8-8804-d598b0f9b448.png)

If I add highlight

![image](https://user-images.githubusercontent.com/15063294/175553449-f70ae354-19e8-4b49-a586-c0655bf315cb.png)

It seems to work fine, with exception of the background color which probably is in conflict with built-in rules.

**Comment by SapnaSoni123** [comment]
Oh, I get it. It is working fine for me now. Thanks much.
Also, is there a way we can get the value of Status in a variable?
