### ISSUE TITLE
Compare does a line by line comparison instead of a cross comparison?

### ISSUE THREAD

**Issue by SapnaSoni123** [EvotecIT/PSWriteHTML#326]
I have 2 jsons whose smaller form look similar to
**$json1** = {
  "Projects": [
    {
      "Name": "Tests",
      "FilePath": "tests\\Unit\\Tests.csproj",
      "TargetFrameworks": [
        {
          "Name": ".NETCoreApp,Version=v3.1",
          "Dependencies": [
            {
              "Name": "NJsonSchema",
              "ResolvedVersion": "10.3.1",
              "LatestVersion": "10.7.2",
              "UpgradeSeverity": "Minor"
            },
            {
              "Name": "System.IO.Abstractions",
              "ResolvedVersion": "13.2.9",
              "LatestVersion": "17.0.18",
              "UpgradeSeverity": "Major"
            }
          ]
        }
      ]
    },
    {
      "Name": "Common",
      "FilePath": "Common\\src\\lib\\Common.csproj",
      "TargetFrameworks": [
        {
          "Name": ".NETStandard,Version=v2.1",
          "Dependencies": [
            {
              "Name": "FluentValidation",
              "ResolvedVersion": "9.0.0",
              "LatestVersion": "11.1.0",
              "UpgradeSeverity": "Major"
            },
            {
              "Name": "Microsoft.Identity.Client",
              "ResolvedVersion": "4.31.0",
              "LatestVersion": "4.45.0",
              "UpgradeSeverity": "Minor"
            }
          ]
        }
      ]
    }
 ]
 }

**$json2** = {
  "Projects": [
    {
      "Name": "Tests.E2E",
      "FilePath": "tests\\E2E\\Tests.E2E.csproj",
      "TargetFrameworks": [
        {
          "Name": ".NETCoreApp,Version=v3.1",
          "Dependencies": [
            {
              "Name": "Microsoft.Extensions.Configuration.Binder",
              "ResolvedVersion": "3.1.9",
              "LatestVersion": "6.0.0",
              "UpgradeSeverity": "Major"
            },
            {
              "Name": "Microsoft.Extensions.Configuration",
              "ResolvedVersion": "3.1.9",
              "LatestVersion": "6.0.1",
              "UpgradeSeverity": "Major"
            }
          ]
        }
      ]
    },
    {
      "Name": "Tests",
      "FilePath": "tests\\Unit\\Tests.csproj",
      "TargetFrameworks": [
        {
          "Name": ".NETCoreApp,Version=v3.1",
          "Dependencies": [
            {
              "Name": "System.IO.Abstractions",
              "ResolvedVersion": "13.2.9",
              "LatestVersion": "17.0.18",
              "UpgradeSeverity": "Major"
            },
            {
              "Name": "Microsoft.Extensions.FileProviders.Physical",
              "ResolvedVersion": "3.1.9",
              "LatestVersion": "6.0.0",
              "UpgradeSeverity": "Major"
            },
            {
              "Name": "AutoFixture",
              "ResolvedVersion": "4.11.0",
              "LatestVersion": "4.17.0",
              "UpgradeSeverity": "Minor"
            }
		]
       	 }
      ]
    }
 ]
 }
**Issue:** 
$json1 = Get-Content json1.json | ConvertFrom-Json
$json2 = Get-Content json2.json | ConvertFrom-Json
$json1, $json2 | Out-HtmlView -Compare -HighlightDifferences -Filtering -FlattenObject 

does not do a cross comparison and does a line by line comparison. I would want project name "Tests" in json1 to be compared to project name "Tests" in json 2.

Also, the -FlattenObject is not able to compare the nested "Dependencies" objects.

**Comment by PrzemyslawKlys** [comment]
It's not that easy. You're comparing Array to Array. How am I supposed to know which object you want to compare to which object? There is a work in progress in this branch for something that could address this - but it's not there yet https://github.com/EvotecIT/PSWriteHTML/compare/master...Compare

**Comment by SapnaSoni123** [comment]
Sure, thanks for the reply.
