### ISSUE TITLE
DefaultSortOrder parameter input dsc instead of desc

### ISSUE THREAD

**Issue by BaTarrY** [EvotecIT/PSWriteHTML#329]
After digging in the HTML to understand what went wrong, I discovered that the -DefaultSortOrder parameter writes dsc instead of **desc**.
This is causing the order not to function (same as not using the parameter).

Image shows comparing the use of the parameter:

Left: Descending
Right: Ascending.

Only Ascending works.
![Decending VS Ascending](https://user-images.githubusercontent.com/26472689/181871157-a9774d45-18ab-4aeb-852f-c5b1bc30957e.png)

**Comment by BaTarrY** [comment]
I believe changing the following will do the trick:
File: PSWriteHTML-master\Public\New-HTMLTable.ps1
Line: 777
Change: Change "dsc" to "desc"

![image](https://user-images.githubusercontent.com/26472689/181871524-11423a10-6bc4-4d57-9f1e-96097b20374b.png)

**Comment by PrzemyslawKlys** [comment]
Care to make a PR?

**Comment by BaTarrY** [comment]
@PrzemyslawKlys Done.
I made sure to verify it on my computer, and now the parameter DefaultSortOrder with value descending is working as expected.

**Comment by PrzemyslawKlys** [comment]
Fixed in 0.0.176. Thank you.
