### ISSUE TITLE
Out-HtmlView and what happens when there are so many columns you need to scroll

### ISSUE THREAD

**Issue by rpodric** [EvotecIT/PSWriteHTML#333]
I'm new to PSWriteHTML, so just put on v0.0.177 yesterday, and am trying to use it for this:
https://raw.githubusercontent.com/12Knocksinna/Office365itpros/master/GetGraphUserStatisticsReport.PS1

That script puts out a lot of columns, so many that with Out-GridView you have to scroll horizontally to see them all (I suppose if you had a very large, very high-resolution monitor that wouldn't be needed).

With Out-HtmlView, however, a line for which I added at the end of the script, the .html file is created just fine, and if you look at it with a text editor all the data seems to be there, but when you open it up in any desktop browser I've tried so far (Chrome, Firefox), you only see a certain number of columns, as expected, but what's not expected is that there is no horizontal scrollbar so there's no way to see the rest.

I figure that I should be using a particular switch with Out-HtmlView, but I'm not seeing which one pertains to this.

**Comment by PrzemyslawKlys** [comment]
The default setting hides additional data under blue plus on the right side.  You can see that in the example shown:

https://evotec.xyz/out-htmlview-html-alternative-to-out-gridview/

You can also use the ScrollX switch to have scrolling enabled. You can also use 30 other parameters to manipulate it.

**Comment by rpodric** [comment]
Ah, that one. It's possible that I even tried that one (guessing from among the many), but if so I apparently didn't notice that it worked since you have to scroll all the way to the bottom before the scrollbar appears. Tricky!
