### ISSUE TITLE
Button Refresh Comman

### ISSUE THREAD

**Issue by amroth3003** [EvotecIT/PSWriteHTML#334]
Hello, is there a way to make a button that re-executes the powershell code?

**Comment by PrzemyslawKlys** [comment]
No - there's no way for HTML to interact with anything on your desktop unless you do it on the server which is outside of scope for now. But what you can do is run task scheduler that refreshes HTML every X minutes/days or whatever and then have an autorefresh set so it refreshes from time to time.
