### ISSUE TITLE
Misnamed Variable

### ISSUE THREAD

**Issue by gregwold** [EvotecIT/PSWriteHTML#34]
Hi Przemyslaw.

In PSWriteHTML.psm1 there's a misnamed variable. In the function Add-TableContent, a variable named "$SideRight" is used, but on line 139 it's named "$SideRighte". Not sure if it's causing issues, but I happened to notice it while looking at the code.

Greg

![PSWriteHTML psm1 - Misnamed Variable](https://user-images.githubusercontent.com/54694367/63988060-7fdcbd00-caa8-11e9-9005-d3384c27fa51.png)

**Comment by PrzemyslawKlys** [comment]
Hello,

Thank you. Yes, it matters if someone is using formatting and using 'le' on the comparison.
