### ISSUE TITLE
Bouton change language title text

### ISSUE THREAD

**Issue by dakhama-mehdi** [EvotecIT/PSWriteHTML#356]
Hi i'm asking if it this possible to use a bouton for change title text, i know do it from .net or Powershell but not on HTML,
any suggestion any idea ?
it will be great to add language change for report
thanks,

**Comment by PrzemyslawKlys** [comment]
You need to provide example with information which button you actually mean. Show some example, with a screenshot.

**Comment by dakhama-mehdi** [comment]
I want that when i click on the language name (it's a Navlink) the title of section change on the correct language like these, if it this possible 
![image](https://user-images.githubusercontent.com/49924401/207659939-30dbf470-418a-4cd7-8491-693084d7ca98.png)

**Comment by PrzemyslawKlys** [comment]
It's not an option currently. That would require some heavy coding to make it easy

**Comment by dakhama-mehdi** [comment]
I'know it will be take a times, thanks
