### ISSUE TITLE
Color Parameter of New-Chartbar override other color of Bar Chart

### ISSUE THREAD

**Issue by crimsonread** [EvotecIT/PSWriteHTML#369]
Hi,

If I specify colors on New-ChartBar, it overrides other color of Bar chart.
If I set colors on the first New-ChartBar cmdlet, it overrides the other color of other New-ChartBar cmdlet
even though I specify different color.

      New-ChartBar -Name '2022' -Color Violet,YellowGreen -Value 20,130
      New-ChartBar -Name '2023' -Color Blue,Orange -Value 10,140
      New-ChartBarOptions -Type barStacked100Percent 

![msedge_GmdXYgWjF2](https://user-images.githubusercontent.com/98467179/215705791-7b2445f7-079a-400d-b8c4-5ec1f1fc231b.png)

**Comment by PrzemyslawKlys** [comment]
Yes, it doesn't work that way. You can't have different colors on different Bars. 2 values on chart bar means 2 colors only in total.

Colors property was added to fix: 
- https://github.com/EvotecIT/PSWriteHTML/discussions/362

You still have to use either Legend to provide colors once for both values of a bar, or you could use one per bar which will build up the colors properly.

**Comment by crimsonread** [comment]
Okay. I see.
Thank you.
