### ISSUE TITLE
Divergent behavior in Ubuntu container (Github Actions)

### ISSUE THREAD

**Issue by DevOptimusPrime** [EvotecIT/PSWriteHTML#370]
I've got a simple line chart dashboard I am attempting to regenerate periodically with a Github Action. The action calls a script with code similar to this:

```
Import-Module PSWriteHTML

New-HTML -TitleText 'Test Dashboard' -Online -FilePath $PSScriptRoot\test.html {
    New-HTMLTabStyle -SlimTabs
    New-HTMLTab -Name 'Projected Hours' -IconRegular hourglass {
        New-HTMLSection -Name 'Hours Projected by Month' -Collapsable -TextBackGroundColor "#000000" -TextColor "#ff7900" {
            New-HTMLPanel -Invisible {
                New-HTMLChart -Title 'Projected Hour Requirements' -TitleAlignment center -TitleFontSize 18 -SubTitleFontSize 18 {
                    New-ChartAxisX -Name 'Eng1', 'Eng2', 'Eng3' -TitleText 'Engineer'
                    ChartLegend -Name 'Needed Hours by month/year' -Color "#ff7900" -FontSize 24
                    New-ChartLine -Name 'Contract Hour Totals' -Value 100, 200, 4300 -Color Green -Curve stepline -Width 10
                    New-ChartLine -Name 'Engineer Planned Hours' -Value 100, 200, 500 -Color Red -Curve stepline -Width 10
                    New-ChartAxisY -Show -TitleText 'Hour Totals'
                }
            }
        }
    }
}
```
This code works as expected locally on my MacBook. However when running it via the Github action (an Ubuntu container) or a Codespace (also an Ubuntu container) it outputs the following warning and fails to produce the dashboard contents:

```
WARNING: New-HTMLTag - Error: Method invocation failed because [System.String] does not contain a method named 'Add'.. Failed value: 
        if ($Content) {
            Invoke-Command -ScriptBlock $Content
        }
```

Both environments are using the latest module version and the most current version of Powershell 7 (7.3.2.)
- Github Actions env = Ubuntu 20.04.5 LTS 
- Local env = MacBook Ventura 13.0

**Comment by PrzemyslawKlys** [comment]
Similar doesn't mean exact. There must be a difference. Most likely instead of string, an array of strings is passed and it blows up.

**Comment by DevOptimusPrime** [comment]
The code I started with was an array of strings (which also works locally strangely enough). But I've since reduced it. This sample is all that is left running in both spots:

![image](https://user-images.githubusercontent.com/9951123/216422585-9910741b-0dda-4ff1-82b7-3910c3e9591e.png)


Even reducing the items to plot to a single value exhibits the same problem:
![image](https://user-images.githubusercontent.com/9951123/216423182-468c7361-0be9-4662-8d2a-6e4a18c660e0.png)

**Comment by PrzemyslawKlys** [comment]
Is it same pswritehtml version?

**Comment by DevOptimusPrime** [comment]
Argh! Good call I was on `.180` locally and `.181` in the Github env. I've got the behavior locally now for better or worse 😆 
![Screenshot 2023-02-02 at 3 37 14 PM](https://user-images.githubusercontent.com/9951123/216444028-ff959846-ebc6-4d0f-9c19-7957f1a88b47.png)

**Comment by PrzemyslawKlys** [comment]
Ok, this comes from 

https://github.com/EvotecIT/PSWriteHTML/blob/aebc340c498ea56a74f0cd0434345b3ba992aad9/Public/New-HTMLChart.ps1#L166

It's because you are using ChartLegend. ChartLeged overwrites Colors variable, that higher up is setup as a list.

https://github.com/EvotecIT/PSWriteHTML/blob/aebc340c498ea56a74f0cd0434345b3ba992aad9/Public/New-HTMLChart.ps1#L98

I need to fix this.

**Comment by PrzemyslawKlys** [comment]
This commit fixes it, but keep in mind that if you specify the chart legend color first (just one color) and then add colors for the lines so it would be like you added 3 colors already, and only first X numbers of colors from the list will be picked.

**Comment by DevOptimusPrime** [comment]
Excellent thank you so much for your help!! As an aside big fan of all your tech! Thanks for years of cool stuff.
