### ISSUE TITLE
ajax inside can be used?

### ISSUE THREAD

**Issue by ericxin1982** [EvotecIT/PSWriteHTML#385]
Hi

Just wondering whether it can support ajax inside, like interaction over internet.
Or it is just being used for report only.

Thanks
Eric Xin

**Comment by ericxin1982** [comment]
Would you please give me some example, I can learn it from example, thanks very much!

**Comment by PrzemyslawKlys** [comment]
I can only point you to; https://evotec.xyz/advanced-html-reporting-using-powershell/ which shows example of using DataTables with ajax, but i've not touched that since then.

**Comment by ericxin1982** [comment]
I have read, and I have not found this has ajax example inside.
