### ISSUE TITLE
BinaryFormatter disabled in .Net 8 breaks Out-HTMLView/New-HTML/etc

### ISSUE THREAD

**Issue by crlogic** [EvotecIT/PSWriteHTML#389]
While testing [PowerShell 7.4-preview4](https://github.com/PowerShell/PowerShell/releases/tag/v7.4.0-preview.4), reports built using PSWriteHTML v0.0.190 no longer work.

### Expected behavior
`Get-Process | Out-HTMLView` returns without error

### Actual behavior
`Copy-Dictionary: Exception calling "Serialize" with "2" argument(s): "BinaryFormatter serialization and deserialization are disabled within this application. See https://aka.ms/binaryformatter for more information."`

Following the rabbit-hole I dug up;
* 7.4-preview4 is updated to .NET 8 Preview 4 https://github.com/PowerShell/PowerShell/pull/19696
* the binaryserializer is now disabled https://learn.microsoft.com/en-us/dotnet/core/compatibility/serialization/8.0/binaryformatter-disabled
* if I replace the `Copy-Dictionary` function w/ the clixml serializer example then my report builts and `Out-HTMLView` works (https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.3)

```

# function Copy-Dictionary { 
#     [alias('Copy-Hashtable', 'Copy-OrderedHashtable')]
#     [cmdletbinding()]
#     param(
#         [System.Collections.IDictionary] $Dictionary
#     )
#     # create a deep-clone of an object
#     $ms = [System.IO.MemoryStream]::new()
#     $bf = [System.Runtime.Serialization.Formatters.Binary.BinaryFormatter]::new()
#     $bf.Serialize($ms, $Dictionary)
#     $ms.Position = 0
#     $clone = $bf.Deserialize($ms)
#     $ms.Close()
#     $clone
# }
function Copy-Dictionary {
    [alias('Copy-Hashtable', 'Copy-OrderedHashtable')]
    [cmdletbinding()]
    param(
        [System.Collections.IDictionary] $Dictionary
    )
    $clone = [System.Management.Automation.PSSerializer]::Serialize($Dictionary, [int32]::MaxValue)
    return [System.Management.Automation.PSSerializer]::Deserialize($clone)
}
```

**Comment by PrzemyslawKlys** [comment]
I've opened an issue about it in PowerShell:
- https://github.com/PowerShell/PowerShell/issues/19878

Does the PSserializer actually works in PS 5.1 tho?

**Comment by PrzemyslawKlys** [comment]
I actually have more "manual" way to copy Dictionaries:
- https://github.com/EvotecIT/PSSharedGoods/blob/master/Public/Objects/Copy-DictionaryManual.ps1

I guess I need to play with it.

**Comment by crlogic** [comment]
> Does the PSserializer actually works in PS 5.1 tho?

Good question, haven't tested.  

I did try different `[System.AppContext]::SetSwitch('xxx',$true)` options as C# projects seemed to support a bypass but could not find a working combination in PS.

**Comment by PrzemyslawKlys** [comment]
Actually the PSSerializer seems to work in PS 5.1. Just wondering on the downsides or compatibility issues.

**Comment by crlogic** [comment]
> Just wondering on the downsides or compatibility issues.

The [article ](https://learn.microsoft.com/en-us/powershell/scripting/learn/deep-dives/everything-about-hashtable?view=powershell-7.3) mentions memory consumption and a depth limit of 48 which might be worth testing against your manual function?

**Comment by PrzemyslawKlys** [comment]
For PSWriteHTML it's non-issue because it's maybe 2 levels deep. For users of PSSharedGoods and my other modules - I guess it depends. But still I wonder on the difference between BinaryFormatter an PSSerializer.

**Comment by PrzemyslawKlys** [comment]
I've removed copying completly from PSWriteHTML which should solve the issue.
