### ISSUE TITLE
Issue with 0.0.191 release

### ISSUE THREAD

**Issue by shivtorov** [EvotecIT/PSWriteHTML#391]
```text
PS> Update-Module -Name PSWriteHTML
```

Install-Package: Authenticode issuer 'CN=Przemysław Kłys EVOTEC, O=Przemysław Kłys EVOTEC, L=Mikołów, C=PL' of the new module 'PSWriteHTML' with version '0.0.191' from root certificate authority 'CN=DigiCert Trusted Root G4, OU=www.digicert.com,
O=DigiCert Inc, C=US' is not matching with the authenticode issuer 'CN=Przemysław Kłys EVOTEC, O=Przemysław Kłys EVOTEC, L=Katowice, S=Śląskie, C=PL' of the previously-installed module 'PSWriteHTML' with version '0.0.190' from root
certificate authority 'CN=DigiCert Assured ID Root CA, OU=www.digicert.com, O=DigiCert Inc, C=US'. If you still want to install or update, use -SkipPublisherCheck parameter.

**Comment by PrzemyslawKlys** [comment]
```
Install-Module PSWriteHTML -Force -Verbose -SkipPublisherCheck
```

I've changed certificate for all my modules as the old one is expiring in days. Unfortunately this means you have to kind of accept new certificate before being able to install new module.
