### ISSUE TITLE
Use fonts loaded by PowerShell script

### ISSUE THREAD

**Issue by Tarterman** [EvotecIT/PSWriteHTML#399]
I was just wondering if there is a way to use fonts that are loaded by the PowerShell script.  I've used some of the code from [here](https://stackoverflow.com/questions/67467159/embedding-a-font-file-otf-into-a-powershell-forms-script) to embed a font but I can't seem to figure out how to use it in the script (possible because it isn't possible).  I used [this website](https://products.aspose.app/font/base64/ttf) to convert the font file to a base64 string.

Here's the part of the code I have used (I've shortened the base64 string just to make things more readable in the post):

```
Add-Type -AssemblyName System.Drawing

$fontBase64 = 'T1RUTwAOAIAAAwBg.......'
$fontBytes  = [Convert]::FromBase64String($fontBase64)
$fontPtr = [System.Runtime.InteropServices.Marshal]::AllocCoTaskMem($fontBytes.Count)
[System.Runtime.InteropServices.Marshal]::Copy($fontBytes, 0, $fontPtr, $fontBytes.Count)
$privateFonts = [System.Drawing.Text.PrivateFontCollection]::new()
$privateFonts.AddMemoryFont($fontPtr, $fontBytes.Count)
[System.Runtime.InteropServices.Marshal]::FreeCoTaskMem($fontPtr)
$myFont = [System.Drawing.Font]::new($privateFonts.Families[0],12)
```

Am I attempting something that isn't possible?

**Comment by StartAutomating** [comment]
@Tarterman my web font understanding is a _little_ rusty, but, yes I'm about 80% sure you couldn't get from point A to point B here (at least like this).

Most of the fonts on a Windows machine will be True Type (`.ttf`) or OpenFont (`.otf`) format.

Web fonts, on the other hand, are Web Open Font Format (`.woff`)

There are a few converters online you can use, but just hoping for the font to carry right over would be asking the browser to have more communication with the OS than browsers tend to like.

Just my $0.02 from too long doing PowerShell + web stuff.

If you want to find a good WOFF font, I'd suggest Google Fonts.

**Comment by PrzemyslawKlys** [comment]
Here's a way to convert font-woff as mentioned above to "local/offline" way. 

- https://github.com/EvotecIT/PSWriteHTML.Helper/blob/master/Public/Repair-FontsAwesome.ps1

I use this code to make sure font awesome/font simple are usable when using PSWriteHTML in offline mode. 

Maybe you want to use some font that has WOFF available.

**Comment by Tarterman** [comment]
Thanks for the responses.  I forgot to mention what font I was using which is Open Sans (which is a TTF font).  I know when websites want to use a TTF that isn't on Windows by default, they will do something like this to allow them to reference the fonts:

```
<link href='[//fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,300,400,600,700,800](https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,300,400,600,700,800)' rel='stylesheet' type='text/css' />
```
I found a TTF to WOFF converter online so I could go that route (@PrzemyslawKlys, I tried the link you provided but it took me to a "404 page not found").  If I have a WOFF font, how would I use that in PSWriteHTML?

**Comment by PrzemyslawKlys** [comment]
It should show up now. Was private project as it's really useful only for me.

**Comment by Tarterman** [comment]
Alright, I got this working and figured I would share how for anyone else.  First thing I did was download the entire family of fonts for Open Sans.  I don't know how it is with other fonts but with Google Fonts, there is a button at the top of the page for the font you are looking.  It downloads a zip file that, at least in the case of Open Sans, contains two .ttf files along with some other files.  One of them was standard fonts and the other was italic.  The TFF files are variable font file so they contains all variations of weight and such.

If you only need a specific variation of the font, there are ways to get the WOFF2 file specific to just that variation.

I'm only interested in standard so I grabbed that one and uploaded it to [Font Squirrel](https://www.fontsquirrel.com/tools/webfont-generator) which is a site to convert the TTF file to WOFF and WOFF2.

Once I finished that, I took the WOFF2 file that it created and uploaded it to [Woff2Base](https://hellogreg.github.io/woff2base/) which converts font files to Base64 strings to include directly in your CSS files.

Once I got that string, I added this inside my New-HTMLHeader section (I shortened the base64 string below to not flood this post with a bunch of text):

```
New-HTMLTag -Tag 'style' -Attributes @{type ='text/css'} -Value {
   "@font-face {
      font-family: 'Open Sans';
      font-style: normal italic;
      src: url(data:application/octet-stream;base64,d09GMgA...............);
   }"
}
```

Now I can reference that font anywhere you can do a -FontFamily parameter.

The thing I can't figure out now, and might not be possible, is if I can use it for the font of the buttons (Copy, Excel, CSV, PDF, Show X Rows, and Search Builder) and if I can use it for the font that is inside the filter boxes when you use the -Filter parameter.

**Comment by PrzemyslawKlys** [comment]
So the way to do this is something like this. You are basically adding another style which is added after original body which defines different font for the whole document. If you would like to have different styles for different places you need to find out which classes those are using and apply them to specific classes. You may also need to use !important as part of the style to overwrite things properly. 

```powershell
$DataTable = @(
    [PSCustomObject] @{ Name = 'Service Desk 1'; Incidents = 1; Resolved = 0; Year = 2001 }
    [PSCustomObject] @{ Name = 'Service Desk 2'; Incidents = 20; Resolved = 15; Year = 2002 }
)

New-HTML {
    Add-HTMLStyle -Placement Header -Css @{
        "@font-face" = @{
            "font-family" = 'Open Sans'
            "font-style"  = "normal italic"
            "src"         = 'url(data:application/octet-stream;base64,d09GMgA...............)'
        }
    }
    Add-HTMLStyle -Placement Header -Css @{
        'body' = @{
            'background-color' = '#34ebeb'
            'font-family'      = '"Raleway", sans-serif'
            'font-size'        = '16px'
        }
    }
    $SectionStyle1 = New-HTMLSectionStyle -RequestConfiguration
    Add-HTMLStyle -Placement Header -Css @{
        "$($SectionStyle1.SectionHead)" = @{
            'background-color' = 'yellow'
            'font-size'        = '50px'
        }
        "$($SectionStyle1.Section)"     = @{
            'margin' = '10px'
            'width'  = 'calc(100% - 20px)'
        }
    }
    New-HTMLSection -HeaderText 'Test' {
        for ($i = 0; $i -le 1; $i++) {
            New-HTMLTable -DataTable $DataTable -HideFooter
        }
    } -Direction column -StyleSheetsConfiguration $SectionStyle1
} -ShowHTML -Online -FilePath $PSScriptRoot\Example-StyleChange.html
```

One could also improve `Get-ConfigurationCSS` and `Add-ConfigurationCss` and `remove-configurationcss` and `set-configuraitoncss` that are private functions to directly write to main configuration and then use `Enable-HTMLFeature` to enable things if not already enabled. This would allow you to replace current defaults with new defaults without having double style for same thing. 

But those never were meant for external use so would require some work

**Comment by Tarterman** [comment]
Awesome!  Thanks for this.  It will give me something more to play around
with next week.
