### ISSUE TITLE
Cannot fork if already forked azurefieldnotes/ReportHTML

### ISSUE THREAD

**Issue by spaelling** [EvotecIT/PSWriteHTML#4]
Hi

I recently made some updates to azurefieldnotes/ReportHTML, but from reading on a recent post on Reddit the project is no longer being maintained or actively developed.

I have made some performance optimizations (I think you did the same), and added functionality for

- images
- links (got rid of the URL01, URL02 encapsulation)
- image links
- line chart, including multiple lines in a single chart

I tried forking this repo so that I could re-implement some of this code, but I cannot fork a repository if I have already forked the original. And then I am unable to make a pull request, I think. 

I really like the concept of generating html (incl. JS and CSS) with PowerShell to get a portable and presentable element to PowerShell. 

How would you suggest contributing to this repository?

**Comment by PrzemyslawKlys** [comment]
As mentioned on reddit please try creating Organization for yourself and fork it there. Whenever I fork anything I get to fork it either to myself or to EvotecIT. Should work for you as well.

**Comment by PrzemyslawKlys** [comment]
Closing this, as you managed to fork it away. Feel free to open new ISSUES / PR's. I'm more than happy to work on this together.
