### ISSUE TITLE
Issu with New-HTMLMarkdown

### ISSUE THREAD

**Issue by Rapidhands** [EvotecIT/PSWriteHTML#402]
Hi Klys, 
 I've teste your sample in this page https://evotec.xyz/unlocking-seamless-html-report-creation-harness-the-power-of-markdown-with-pswritehtml-powershell-module/ using one of my mardown file.
This markdown file has some powershell code and some console output in it. 
Here a sample : 

- [x] **Avoid repeated calls to a function**. Calling a function can be an expensive operation. If you calling a function in a long running tight loop, consider moving the loop inside the function.

Demo : 

````Powershell
$ranGen = New-Object System.Random
$RepeatCount = 10000

Measure-MyScript -Name "Basic for-loop" -Unit ms -Repeat 10 -ScriptBlock {
    for ($i = 0; $i -lt $RepeatCount; $i++) {
        $Null = $ranGen.Next()
    }
}

# wraps the random number generator in a function that's called in a tight loop
Measure-MyScript -Name "Wrapped in a function" -Unit ms -Repeat 10 -ScriptBlock {
    function Get-RandNum_Core {
        param ($ranGen)
        $ranGen.Next()
    }

    for ($i = 0; $i -lt $RepeatCount; $i++) {
        $Null = Get-RandNum_Core $ranGen
    }
}
# The function is only called once but the code still generates 10000 random numbers. 
Measure-MyScript -Name "For-loop in a function" -Unit ms -Repeat 10 -ScriptBlock {
    function Get-RandNum_All {
        param ($ranGen)
        for ($i = 0; $i -lt $RepeatCount; $i++) {
            $Null = $ranGen.Next()
        }
    }

    Get-RandNum_All $ranGen
}
````

````output
name                    Avg                   Min                   Max
----                    ---                   ---                   ---
Basic for-loop          8,1763 Milliseconds   7,1114 Milliseconds   9,1556 Milliseconds
Wrapped in a function   157,3784 Milliseconds 148,9869 Milliseconds 165,9685 Milliseconds
For-loop in a function  5,4158 Milliseconds   4,7084 Milliseconds   7,1147 Milliseconds
````

The display in the html file is weird.  The powershell block code is fragmented. 

![2023-09-03_21-14](https://github.com/EvotecIT/PSWriteHTML/assets/48151863/2520b5c3-1174-4df6-98ec-079632f8e040)

Another point : In the beginning of the screenshot, I've a check box
![2023-09-03_21-16](https://github.com/EvotecIT/PSWriteHTML/assets/48151863/2f8990c6-2814-4a3a-bf8a-f915b1325e3a)
The display is weird too. I'm using "Markdown Checkboxes" extension in VSCode to do this. 

regards

**Comment by PrzemyslawKlys** [comment]
Can you provide full sample of Markdown using codeblock so i can play with it?

**Comment by Rapidhands** [comment]
herre a short test mardown file
regards
________________________________
De : Przemysław Kłys ***@***.***>
Envoyé : dimanche 3 septembre 2023 21:50
À : EvotecIT/PSWriteHTML ***@***.***>
Cc : Rapidhands ***@***.***>; Author ***@***.***>
Objet : Re: [EvotecIT/PSWriteHTML] Issu with New-HTMLMarkdown (Issue #402)


Can you provide full sample of Markdown using codeblock so i can play with it?

**Comment by PrzemyslawKlys** [comment]
There's no file? Emails don't bring files over

**Comment by Rapidhands** [comment]
Hi Klys

Here a .zip file, with my test.

  *   The script I'm using (renamed to  .ps1.txt, to avoid mail restriction)
  *   The 2 markdown files (+ an export in PDF of these files)
  *   The Html file generate by the script.

Nota  : It seems to have another issue in the html file :  Characters with accents do not display well. It's fine in the pdf (md ==> pdf) but not in the html.

regards
Olivier
________________________________
De : Przemysław Kłys ***@***.***>
Envoyé : lundi 4 septembre 2023 07:37
À : EvotecIT/PSWriteHTML ***@***.***>
Cc : Rapidhands ***@***.***>; Author ***@***.***>
Objet : Re: [EvotecIT/PSWriteHTML] Issu with New-HTMLMarkdown (Issue #402)


There's no file? Emails don't bring files over

**Comment by PrzemyslawKlys** [comment]
Again, attach it manually to issue. Emails don't work.

**Comment by Rapidhands** [comment]
[Test Markdown.zip](https://github.com/EvotecIT/PSWriteHTML/files/12509938/Test.Markdown.zip)

I put the zip direct here. 
regards
Olivier

**Comment by PrzemyslawKlys** [comment]
Few things:

- I'll fix encoding problem in next version
- You can use `EnableTaskLists` switch to enable tasks correctly
- You are using 4 \` instead of 3 \` for code blocks which is causing issues 

![image](https://github.com/EvotecIT/PSWriteHTML/assets/15063294/ae05f39f-f776-4cb2-bd29-1aeb26804bcc)

- For inline code you are using again 4 \` instead of just 1 \`

This means:

- [x] Use **````begin````, ````process````, ````end````**.

Should be:

- [x] Use `begin`, `process`, `end`.

Here's how it looks as code:

![image](https://github.com/EvotecIT/PSWriteHTML/assets/15063294/1ca9e52b-87cd-4473-baa8-7fca8b6c679f)

**Comment by Rapidhands** [comment]
My bad, 
I've had an issue at the end of the largest markdown file. 
<3backticks>Powershell
this works fine
<3backticks>

<3backticks> Powershell
this doesn't works. Note the space before Powershell
<3backticks>

**Comment by PrzemyslawKlys** [comment]
But you have 4 backticks everywhere in your markdown. It's not really valid MD

**Comment by PrzemyslawKlys** [comment]
1.8.0 should fix encoding issue. Rest is about incompatible markdown which you can fix.

**Comment by Rapidhands** [comment]
Tested and approved 🙂
Thanks
Olivier
________________________________
De : Przemysław Kłys ***@***.***>
Envoyé : lundi 4 septembre 2023 13:55
À : EvotecIT/PSWriteHTML ***@***.***>
Cc : Rapidhands ***@***.***>; Author ***@***.***>
Objet : Re: [EvotecIT/PSWriteHTML] Issu with New-HTMLMarkdown (Issue #402)


1.8.0 should fix encoding issue. Rest is about incompatible markdown which you can fix.
