### ISSUE TITLE
New-TablePercentageBar - Conditional BarColor?

### ISSUE THREAD

**Issue by smasterson** [EvotecIT/PSWriteHTML#408]
With New-TablePercentageBar it doesn't seem possible to create a condition for things like BarColor?

Ideally, being able to say something like the following would be great:
- If Value > 70 BarColor eq Yellow
- If Value > 80 BarColoer eq Orage
- If Value > 90 BarColor eq Red

Love this addition, not sure when it popped in, just needs this one tweak to be super useful!

**Comment by PrzemyslawKlys** [comment]
hi, 

Not sure it's natively possible:
- https://datatables.net/plug-ins/dataRender/percentageBars

The JS code is here:
- https://cdn.datatables.net/plug-ins/1.13.4/dataRender/percentageBars.js

Source codes (to commit back to DataTables after fixes)
- https://github.com/DataTables/Plugins/blob/master/dataRender/percentageBars.js

This would require some modification to support conditions, but doable. 

Some links to consider:
-https://datatables.net/examples/basic_init/data_rendering.html

**Comment by PrzemyslawKlys** [comment]
I actually just hardcoded this and it seems to work, so I'll work on it to make it nice and fancy

**Comment by smasterson** [comment]
Gotcha, I didn't assume it was tied directly to DataTables - thanks!

My current workaround is to use manual HTML with -InvokeHTMLTags:
$tmp1 | % { $_.'% Used' = "$($_.'% Used')" + '%  <meter value="' + "$($_.'% Used')" + '" optimum="25" low="70" high="85" max="100"></meter>' }

Very ugly but works...my biggest issue was trying to make it 'pretty' as I am not familiar with CSS, etc...

**Comment by PrzemyslawKlys** [comment]
The change is pretty trivial

![image](https://github.com/EvotecIT/PSWriteHTML/assets/15063294/afdbddc9-d6c3-42be-a15d-83cd1be97c42)

Just before returning style, you can hardcode cBar to some value. I am now checking on how you can pass hashtable of sorts so it would work

**Comment by PrzemyslawKlys** [comment]
I've created PR for this change in datatables. Lets see how that works out. I'll probably release my own version until they process it properly on their own side.

**Comment by PrzemyslawKlys** [comment]
From a PowerShell perspective:

```powershell
$DataTable = @(
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 1.42; Percents = 50 }
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 5.72; Percents = 5 }
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 16.22; Percents = 17 }
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 23.73; Percents = 99 }
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 50.73; Percents = 105 } # will be trimmed to 100%
    [PSCustomObject] @{ Test = 'Name'; Test2 = 'Name2'; Test3 = 'Name3'; Test4 = 90; Percents = 105 } # will be trimmed to 100%
)

New-HTML {
    New-HTMLTable -DataTable $DataTable -AlphabetSearch {
        New-TablePercentageBar -ColumnID 4 # runs on defaults
        New-TablePercentageBar -ColumnID 3 -BackgroundColor Blue -TextColor White -BorderColor Grey -BarColor gold -BorderStyle ridge -Type round {
            New-TablePercentageBarCondition -Minimum 0 -Maximum 10 -BackgroundColor Blue -TextColor White -BarColor Red
            New-TablePercentageBarCondition -Minimum 11 -Maximum 20 -BackgroundColor Blue -TextColor White -BarColor Green
            New-TablePercentageBarCondition -Minimum 21 -Maximum 25 -BackgroundColor Blue -TextColor White -BarColor AppleBlossom
            New-TablePercentageBarCondition -Minimum 26 -Maximum 85 -BackgroundColor Grey -TextColor Black -BarColor Cyan
            New-TablePercentageBarCondition -Minimum 86 -Maximum 100 -BackgroundColor Blue -TextColor White -BarColor Yellow
        }
    } -ImmediatelyShowHiddenDetails
} -ShowHTML -FilePath $PSScriptRoot\Example7_PercentageBar.html -Online
```

**Comment by smasterson** [comment]
Love it, as usual! Thanks!

**Comment by smasterson** [comment]
Is this working in 1.9.0?
The example does not appear to be working for me...no errors
![image](https://github.com/EvotecIT/PSWriteHTML/assets/4913609/e17e049a-5f12-463f-a3ef-0c8bdd8aed4f)

**Comment by PrzemyslawKlys** [comment]
It is, but was working without `-Online`. I forgot to change version number in configuration url. Republished 1.10.0 which should work in both cases.

**Comment by smasterson** [comment]
Thanks!
