### ISSUE TITLE
Issue with New-HTMLTableCondition

### ISSUE THREAD

**Issue by Rapidhands** [EvotecIT/PSWriteHTML#421]
Hi Klys, 
I'm using you rmodule to generate an Certificate report and there is an issue with New-HTMLTableCondition with Date
eg : 
```
# Gathering Date
$MachineCerts = foreach ($Container in $AllMachineCertContainers)
{
    Get-ChildItem -Path Cert:\LocalMachine\$Container
....
# Begining report
# ...
 New-HTMLTable -DataTable $MachineCerts {
                New-HTMLTableCondition -Name 'NotAfter' -Type date -Operator lt -Value $(Get-Date) -BackgroundColor Orange
            }#end-newhtmltable
```

As you could see in the attach screenshoot, I'm thinking there is a issue with the TableCondition. 

My current culture is FR-Fr. I've also checked that the Type of the NotAfter property. It's a [DateTime] type. Then, I'm thinking that it's the way the cmdlet compares Dates that is problemtic.

Could you investigate ?

Sorry for the inconvenience. That doesn't stop me from being a big fan of your work. :-)

Regards
Olivier

**Comment by PrzemyslawKlys** [comment]
You should read on: https://evotec.xyz/advanced-html-reporting-using-powershell/

There's topic of date comparison covered there.
