### ISSUE TITLE
Add a logo image from file into a header report

### ISSUE THREAD

**Issue by geraluca** [EvotecIT/PSWriteHTML#423]
good evening, I have a question, how can I upload an image from a file and put it as a logo next to the title? Thank you

**Comment by PrzemyslawKlys** [comment]
Take a look at some examples in issues or discussions:
- https://github.com/EvotecIT/PSWriteHTML/discussions/360
- https://github.com/EvotecIT/PSWriteHTML/discussions/178

What you most likely want is New-HTMLImage -Inline switch which 

Links to a file:
```ps
 New-HTMLImage -Source "C:\Evotec-Logo-600x190.png"
```

Inlines as binary:
```ps
 New-HTMLImage -Source "C:\\Evotec-Logo-600x190.png" -Inline
```

**Comment by geraluca** [comment]
not work

**Comment by PrzemyslawKlys** [comment]
> not work

That's super helpful. 

```ps
New-HTML -TitleText 'This is a test' -FilePath "$PSScriptRoot\Example29-01.html" {
    New-HTMLHeader {
        New-HTMLSection -Invisible {
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source 'https://evotec.pl/wp-content/uploads/2015/05/Logo-evotec-012.png' -UrlLink 'https://evotec.pl/' -AlternativeText 'My other text' -Class 'otehr' -Width '50%' -Inline
            }
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source 'https://evotec.pl/wp-content/uploads/2015/05/Logo-evotec-012.png' -UrlLink 'https://evotec.pl/' -AlternativeText 'My other text' -Width '20%' -Inline
            } -AlignContentText right
        }
    }
    New-HTMLTab -TabName 'Dashboard' {
        New-HTMLTable -DataTable (Get-Process | Select-Object -First 2)
    }
    New-HTMLFooter {
        New-HTMLSection -Invisible {
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source 'https://evotec.pl/wp-content/uploads/2015/05/Logo-evotec-012.png' -UrlLink 'https://evotec.pl/' -AlternativeText 'My other text' -Class 'otehr' -Width '50%' -Inline
            }
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source 'https://evotec.pl/wp-content/uploads/2015/05/Logo-evotec-012.png' -UrlLink 'https://evotec.pl/' -AlternativeText 'My other text' -Width '20%' -Inline
            } -AlignContentText right
        }
    }
} -ShowHTML -Online
```

Pretty sure this works just fine.

**Comment by geraluca** [comment]
Let's clarify, the code that uses the link and the url works, the code that loads from the computer disk doesn't work, I tried to write both C:|| chw c:\ that C:// that c:/ doesn't work

**Comment by geraluca** [comment]
New-HTML -TitleText 'This is a test' -FilePath "$PSScriptRoot\Example29-01.html" {
    New-HTMLHeader {
        New-HTMLSection -Invisible {
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source "C:\HTML-TEST" -Width '50%' -Inline
            }
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source "C:\HTML-TEST" -Width '20%' -Inline
            } -AlignContentText right
        }
    }
    New-HTMLTab -TabName 'Dashboard' {
        New-HTMLTable -DataTable (Get-Process | Select-Object -First 2)
    }
    New-HTMLFooter {
        New-HTMLSection -Invisible {
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source "C:\HTML-TEST" -Width '50%' -Inline
            }
            New-HTMLPanel -Invisible {
                New-HTMLImage -Source "C:\HTML-TEST" -Width '20%' -Inline
            } -AlignContentText right
        }
    }
} -ShowHTML -Online


This don't work, you ave a suggest ? Thanks

**Comment by PrzemyslawKlys** [comment]
Pretty sure C:\HTML-TEST won't work. It has to be actual Image.

**Comment by geraluca** [comment]
I apologize, when I copied the code the image was left out, it works, thank you for your patience and your professional availability
