### ISSUE TITLE
Section in section below echt other

### ISSUE THREAD

**Issue by DonDom86** [EvotecIT/PSWriteHTML#425]
Hello,
how can the subsections be arranged one below the other?
Many thanks for your feedback.

`New-HTML {

        New-HTMLSection -HeaderText 'Section' -CanCollapse {
            for($i = 1; $i -lt 10; $i++)
            {     
                New-HTMLSection -HeaderText $('Sub-Section ' + $i) -CanCollapse -Collapsed {

                        New-HTMLText -Text 'Test'

                }
            }
        }
} -Online -FilePath $PSScriptRoot\Test.html -TitleText 'Container Panel Section' -ShowHTML`

Greetings
Dom

**Comment by PrzemyslawKlys** [comment]
```powershell
    New-HTMLSection -HeaderText 'Test' {
        New-HTMLContainer {
            New-HTMLSection -HeaderText 'Test 1' {
                New-HTMLTable -DataTable $ProcessSmaller
            }
            New-HTMLSection -HeaderText 'Test 2' {
                New-HTMLTable -DataTable $ProcessSmaller
            }
            New-HTMLSection -HeaderText 'Test 3' {

            }
        }
    }
```

**Comment by DonDom86** [comment]
Thank you
