### ISSUE TITLE
Add support for multiline labels

### ISSUE THREAD

**Issue by mg07647** [EvotecIT/PSWriteHTML#426]
Add support for multiline label names as shown in this link:
- https://apexcharts.com/docs/multiline-text-and-line-breaks-in-axes-labels/

**Comment by PrzemyslawKlys** [comment]
You can already do that:

```powershell
New-ChartAxisX -Name 'Jan', 'Feb', 'Mar', @('Apr','Apr1'), 'May', 'Jun', 'Jul', 'Aug', 'Sep'
```

**Comment by mg07647** [comment]
In my case I changed the `$Name` parameter in `New-ChartBar` line 13875 from `[string]` to `[Array]`, and that worked!
Thanks for pointing out a fix.
