### ISSUE TITLE
New-HTMLTable HREF date sort not working

### ISSUE THREAD

**Issue by permster** [EvotecIT/PSWriteHTML#427]
Does an HTML table support sorting by date when your using HREF link text?

For example the table cell content is:
`<a href="http://localhost">2/11/2023 5:21:32 AM</a>`

My sorting format is -DateTimeSortingFormat 'M/d/yyyy h:mm:ss tt' but I can't get it to work.  It does sort but it's not treating them as dates so some dates aren't in the correct order.  I'm guessing perhaps the date sort logic isn't capable of handling the HREF link text.

**Comment by PrzemyslawKlys** [comment]
We would need to build some custom sorting. DataTables for sure supports it, but you would need find how to implement it, as the sorting would effectively need to remove "tags" and content and just leave a date. Doable, but probably not great. Especially that it could be something more complicated.
