### ISSUE TITLE
Search option

### ISSUE THREAD

**Issue by geraluca** [EvotecIT/PSWriteHTML#430]
I kindly ask if it is possible to disable the presence of the "search" window in the html datatable page, thank you

**Comment by PrzemyslawKlys** [comment]
```ps
New-HTMLTable -DisableSearch
```

?

**Comment by geraluca** [comment]
Perfect thanks


Il giorno mar 23 gen 2024 alle ore 15:23 Przemysław Kłys <
***@***.***> ha scritto:
