### ISSUE TITLE
Donut chart colour issue

### ISSUE THREAD

**Issue by RobinpZA** [EvotecIT/PSWriteHTML#436]
Hi,

Adding a color to a donut chart, seems to mess up the colours altogether, not showing the correct colours on the chart.
Not sure If I'm doing something incorrectly? But have tried with multiple colours, using names and hex codes.
Pie chart colours are working fine.

New-HTMLChart -Title 'OneDrive Utilization' -TitleAlignment center     {
                    New-ChartLegend -LegendPosition bottom
                    New-ChartDonut  -Name  'OneDrive Utilization' -Value $activeOneDrivePercentage -Color'#6dbf88'
                    New-ChartDonut  -Name  'Not Utilized' -Value $OneDriveremainingPercentage -Color "#FFFFFF"
![Screenshot 2024-04-04 171630](https://github.com/EvotecIT/PSWriteHTML/assets/165141638/66ec7f4f-9257-4a02-b798-9d2f2ffeaf0b)

**Comment by PrzemyslawKlys** [comment]
New version should fix it:

```powershell
New-HTML {
    New-HTMLChart -Title 'OneDrive Utilization' -TitleAlignment center {
        New-ChartLegend -LegendPosition bottom
        New-ChartDonut -Name 'OneDrive Utilization' -Value 15 -Color '#6dbf88'
        New-ChartDonut -Name 'Not Utilized' -Value 20 -Color Yellow
    }
} -ShowHTML -FilePath $PSScriptRoot\OneDriveUtilization.html -Online
```

![image](https://github.com/EvotecIT/PSWriteHTML/assets/15063294/5b56012b-35cc-46e4-91ff-8ac873b26db1)
