### ISSUE TITLE
Question: Building an EmailBody

### ISSUE THREAD

**Issue by nickds1** [EvotecIT/PSWriteHTML#438]
Hi

I'm trying to build up an email report for several domains from a collection...

I'm not great at PS and am having trouble working out how to add several blocks together - each block is constructed in a function which computes the report for the passed domain. At the end, the completed report needs to be emailed.

Currently, I'm trying something like:

```powershell
function DoDomainReport
{
    [OutputType([System.Int32])]
    param(
        [string] $url,
        [ref]    $EmailReport
    )
   ...do stuff...
   $EmailReport += {
     EmailText ....
   }
}
$EmailReport = @{}
$TotalErrors = 0
$urls = @('www.domain1.com','www.domain2.com')

foreach ($url in $urls) {
    $TotalErrors += DoDomainReport -url $url -EmailReport ([ref]$EmailReport)
}
$EmailReport = EmailBody -FontFamily 'Calibri' -Size 15  ...
```

...then send email

...but that is obviously a complete fail! Would appreciate some pointers. Thanks!

**Comment by PrzemyslawKlys** [comment]
I have no idea what you're doing and why you're doing it with ref and why would you merge hashtable with scriptblock - all of it doesn't add up.
