### ISSUE TITLE
Show ChartLegend when hover over table row and not over bar

### ISSUE THREAD

**Issue by whoot** [EvotecIT/PSWriteHTML#44]
When you have a very large bar and a very small bar, it makes it nearly impossible to hover over the small bar to get the value.

Example - Hovering over the 'Password not Required' bar is neraly impossible, because its painfully small:
![grafik](https://user-images.githubusercontent.com/8066322/64125580-c1bc7a80-cdaa-11e9-972a-84a7179143f8.png)

It would be better to show the 'value' when hovering over the table row and not over the bar.
An alternative solution would be to ensure, that the bar is at least big enough to show the value.

**Comment by xlrod** [comment]
Was reading the documentation for the ApexCharts and found that the dataLabels can be added to the script with an offsetX. Looked at the code and it seems it's already there, so I went ahead and recreated the chart and it does display a value now, not when hovered though. If the code was already there, it could have been that the font was set to White and the value could not be seen due to the background of the chart being White as well.



    New-HTMLSection -HeaderText 'Bar' -CanCollapse {
        New-HTMLPanel {
            New-HTMLChart {                
                New-ChartBar -Name 'LockedOut' -Value 59
                New-ChartBar -Name 'pwdLastSet >= 1 Year' -Value 1347
                New-ChartBar -Name 'Password Expired' -Value 193
                New-ChartBar -Name 'Password Never Expired' -Value 1463
                New-ChartBar -Name 'Password Not Required' -Value 1
                New-ChartBar -Name 'Reversible Pwd Encr.' -Value 0
                New-ChartBarOptions -DataLabelsColor White
            }
        }
        New-HTMLPanel {
            New-HTMLChart {                
                New-ChartBar -Name 'LockedOut' -Value 59
                New-ChartBar -Name 'pwdLastSet >= 1 Year' -Value 1347
                New-ChartBar -Name 'Password Expired' -Value 193
                New-ChartBar -Name 'Password Never Expired' -Value 1463
                New-ChartBar -Name 'Password Not Required' -Value 1
                New-ChartBar -Name 'Reversible Pwd Encr.' -Value 0
                New-ChartBarOptions -DataLabelsColor DarkBlue # White
            }
        }
    }


![bar](https://user-images.githubusercontent.com/48139416/70154882-44d9bf00-167f-11ea-91ec-2a40f4cfd87a.JPG)

**Comment by whoot** [comment]
great catch! I will check as soon as I have the time

**Comment by PrzemyslawKlys** [comment]
Great work xlrod :-) It takes some time to swift thru documentation and then thru code. Glad you're helping out!

**Comment by whoot** [comment]
Okay, this seems to be fixed in the current version of PSHTML, because I just ran the initial script and got the following:

![Tables](https://user-images.githubusercontent.com/8066322/71171280-a85a1400-225d-11ea-8faf-322861e6172c.png)


So I guess I can close this issue :)

**Comment by PrzemyslawKlys** [comment]
Thats weird? Did the font color change from white to black by itself?

**Comment by PrzemyslawKlys** [comment]
Btw this is PsWriteHTML. Pshtml is diff project :-p

**Comment by whoot** [comment]
>
>
> Thats weird? Did the font color change from white to black by itself?

I actually dont know. I updated PSWriteHTML to the current version an rerun my script.

> 
> 
> Btw this is PsWriteHTML. Pshtml is diff project :-p

Oh yeah, thats what i meant :)
