### ISSUE TITLE
Enhancement: Modify Image Background Color in `New-HTMLImage` to Include None/Transparent Option

### ISSUE THREAD

**Issue by Imran-imtiaz48** [EvotecIT/PSWriteHTML#441]
With the increasing adoption of dark mode themes across various email clients, the default white background color applied when inserting images can lead to inconsistent visual experiences. This enhancement ensures that when images are inserted using the `New-HTMLImage` function, the background color can be customized, including the option to set it to none/transparent, thereby maintaining design integrity across different themes.

**Comment by PrzemyslawKlys** [comment]
Seems identical to:
- https://github.com/EvotecIT/PSWriteHTML/issues/264

**Comment by PrzemyslawKlys** [comment]
Or are you actually doing a PR to solve it?
