### ISSUE TITLE
AutoRefresh functionality in Internet Explorer exhibits a propensity to revert the active tab to the initial tab in the sequence.

### ISSUE THREAD

**Issue by Imran-imtiaz48** [EvotecIT/PSWriteHTML#442]
When configuring a dashboard with the -AutoRefresh option, Internet Explorer consistently defaults to the initial tab upon refresh, whereas Chrome maintains the currently active tab. This discrepancy likely stems from inherent limitations within IE's tab management functionality. Aligning IE's behavior with Chrome's, ensuring it preserves the user's current tab, would be highly beneficial and enhance user experience.

**Comment by PrzemyslawKlys** [comment]
Unfortunately this will not be worked on. I've started to remove IE support from PSWriteHTML module, and already half of the stuff isn't working either. 

- https://learn.microsoft.com/en-us/lifecycle/faq/internet-explorer-microsoft-edge

IE support ended on June 15, 2022. While it's still on the servers, you should use Edge. Maintaining any sort of IE support is pain and kind of waste of time. If you want to continue using IE I advice use the version from like 3 releases ago and continue using it as you wish.

**Comment by PrzemyslawKlys** [comment]
Besides it's already discussed here:
- https://github.com/EvotecIT/PSWriteHTML/issues/78

The issue is related to IE not working correctly with local content, it works as Hosted Page as far as I remember.
