### ISSUE TITLE
Incorporate Thermographic Visualizations.

### ISSUE THREAD

**Issue by Imran-imtiaz48** [EvotecIT/PSWriteHTML#443]
"Incorporate Thermographic Visualizations" means to include graphical representations where data values are depicted through variations in color intensity, similar to a thermal map. These visualizations allow for the easy identification of patterns, trends, and outliers in complex datasets, offering a clear and intuitive way to analyze and interpret the information.

**Comment by PrzemyslawKlys** [comment]
What does that even mean? What exactly you want?
