### ISSUE TITLE
Ability to put Tabs inside of Tabs

### ISSUE THREAD

**Issue by colonydude** [EvotecIT/PSWriteHTML#48]
I just wanted to say thanks for putting this module together.  It has made my life a little easier.

I was hoping you would consider adding a way to put tabs inside a tab.

I have been playing the version on Powershell Gallery and I was hoping to Have a "Servers Status" tab at the top with tabs for each server inside.

Thanks

**Comment by PrzemyslawKlys** [comment]
Added in last version.
