### ISSUE TITLE
Report paging does not work in Microsoft Edge or IE?

### ISSUE THREAD

**Issue by c3rberus** [EvotecIT/PSWriteHTML#49]
When I create a HTML report using New-HTML and view it in Chrome everything looks good, the data tables show 15 records and have a pager for more data. 

If the same report is open under MS Edge or IE it shows all the records on one page (there is no pager). This makes it very difficult to use because you end up with a huge page scroll without paging. This was tested on latest Windows 10 1903.

Is it possible to get the paging to work for Edge/IE or am I missing some parameter?

**Comment by PrzemyslawKlys** [comment]
All the hard work is done by JavaScript. Not sure if IE will be able to handle advanced JS but that’s what you need to get it running. I use Edge Chromium myself. For standard Edge it could possibly work I guess but you need to make sure JavaScript for local files is allowed. Of course it’s possible that both products are so legacy some features of modern internet Won’t work.

**Comment by PrzemyslawKlys** [comment]
In other words, what you did in Powershell is enough. The hard part is now verification whether IE or non-chromium Edge can be used with it.

**Comment by c3rberus** [comment]
I am using Edge with the default settings from a Windows 10 install (not domain joined so no group policy settings are being applied to harden it). This should be fairly easy to reproduce if you load a larger data table in Edge. I don't think there is any blocking going on. The report worked fine in ReportHTML but once I converted over to PSWriteHTML the bug is there in Edge.

**Comment by PrzemyslawKlys** [comment]
I could always reproduce it. I just assumed this won't work on IE or Edge. But actually I can see that indeed it works if I open up: https://datatables.net/examples/advanced_init/complex_header.html 

So maybe it's just my implementation that is struggling.  I don't promise a fix this week as I'm on delegation to France, but if I'll get a chance I'll try to push some checks and see what may be causing this.

**Comment by c3rberus** [comment]
Sounds good, thanks for the quick replies.

**Comment by PrzemyslawKlys** [comment]
https://datatables.net/download/compatibility

**Comment by PrzemyslawKlys** [comment]
Actually, it seems to be working fine: https://evotec.xyz/wp-content/uploads/2019/05/DashboardActiveDirectory.html when hosted on the website. This mean it only doesn't work for local files. This seems more like an issue with IE/Edge with the way I'm including those scripts.

**Comment by c3rberus** [comment]
You are right, only seems to be when the file is open locally vs. hosted. That is super strange, I wonder what causes it to break locally.

**Comment by PrzemyslawKlys** [comment]
Does it work locally with ReportHTML?

**Comment by 1RedOne** [comment]
Could you give some simple reproduction steps?  I can help diagnose what could be happening to the JS.

**Comment by PrzemyslawKlys** [comment]
Just take an example - for example, Example04-TableAndTabs and see how the Table loads in Chrome/Firefox and how it acts in IE. Basically JS doesn't seem to load properly. Or 

```
Get-Process | Out-HTMLView
```

And try the .html in diff browsers.

**Comment by PrzemyslawKlys** [comment]
Potentially related: https://docs.microsoft.com/en-us/previous-versions/windows/internet-explorer/ie-developer/compatibility/ms537628(v=vs.85)?redirectedfrom=MSDN

**Comment by PrzemyslawKlys** [comment]
https://blogs.msdn.microsoft.com/ieinternals/2011/03/23/understanding-local-machine-zone-lockdown/

https://blogs.msdn.microsoft.com/ieinternals/2012/06/19/enhanced-protected-mode-and-local-files/

But even thou I played with those settings it doesn't seem to work

**Comment by 1RedOne** [comment]
I tried downloading all of the JS, and basically everything related to this issue and can't find a workaround.  Seems that both IE and Edge just happen to suck. 

Works fine in FireFox, Chrome, EdgeDev, and everything else one might use.

**Comment by PrzemyslawKlys** [comment]
@c3rberus Do you know if  ReportHTML reports happen to work on IE/Edge when run locally? 

@1RedOne Ye, it's a bit of pity. IE is only available on servers for me.

**Comment by c3rberus** [comment]
No they do not work in IE/Edge when ran locally. We use Edge as default browser within the organization and everyone has Chrome installed as a secondary option. Edge plays nice with internal enterprise applications so we can't switch out the default quite yet. It would be great if we could make this work for IE/Edge. I wonder what is causing this, the datatables show being compatible and no errors are thrown when the html file is opened.

**Comment by 1RedOne** [comment]
This is caused by Internet Explorer and Edge's behavior of not loading JavaScript files for items in the Intranet zone.  I cannot find a workaround other than changing the setting in Internet Explorer.

**Comment by PrzemyslawKlys** [comment]
Did you manage to find settings that work?

I was thinking I need to try this out https://stackoverflow.com/questions/8146926/why-does-ie-restrict-the-javascript-files-of-local-html-pages with crlf.

**Comment by PrzemyslawKlys** [comment]
I tried fixing it, but I'm out of ideas. Leaving this open. maybe someone will manage to fix it. I even tried playing 

- https://social.technet.microsoft.com/Forums/ie/en-US/7f8e1bc1-f4be-4274-840c-73f1aab092b2/allow-blocked-content-javascript-on-local-html-files-ie11?forum=ieitprocurrentver
- http://woshub.com/how-windows-determines-that-the-file-has-been-downloaded-from-the-internet/

But neither NTFS streams or comment made any impact.

**Comment by 1RedOne** [comment]
I tried all of those options and some other things, like downloading all of
the JS scripts needed and referencing them locally.  I could not got IE to
load the JS without changing zone info, which is almost always going to be
blocked by group policy and so of little use.

Better idea?  Don't reference locally.  Use the IIS ability of the report
and push the reports there.

**Comment by 1RedOne** [comment]
No, even when I changed zone info using every possible trick, I could not get this to work.

**Comment by PrzemyslawKlys** [comment]
I've tracked this to Datatables 1.10.12 working fine, where 1.10.13+ doesn't work. But it only doesn't work if used with my code.

**Comment by PrzemyslawKlys** [comment]
This folder has 2 files: https://github.com/EvotecIT/PSWriteHTML/tree/master/Examples/Example-IE 

Both should work in IE. One is mine with 1.10.12, one is using some random example where I've put a similar version. 

This needs further debugging why it fails for higher versions.

**Comment by c3rberus** [comment]
I can confirm the TestIE-Works.html example works in IE and Edge.

**Comment by PrzemyslawKlys** [comment]
Yes. As always. Testing few other things.

**Comment by c3rberus** [comment]
Sounds good, thanks for getting this working in IE/Edge!

**Comment by PrzemyslawKlys** [comment]
Should be working in new release now. VIsNetwork still not fixed thou
