### ISSUE TITLE
Improve New-HTMLTable Height / Responsive / Simplify / Email options

### ISSUE THREAD

**Issue by c3rberus** [EvotecIT/PSWriteHTML#50]
When dealing with DataTable output the table has a lot of white space between each line. This is coming from the CSS being applied to the **<td>** tag, specifically **padding: 4px** and **height: 27px** styling.

Is it possible to override this (other than modifying the CSS files that are part of the module), using the New-HTMLTag or something? Here is a screenshot: https://ibb.co/7WZtskX

The goal being I want the data table to have very little wasted space and more stacked together, I tried the -Style parameter to no effect and do not want to use -Simplify as that gets rid of sorting.

This isn't so much of a issue but more of a usage question - if modifying the CSS is the only way to go that is fine but I though I'd ask to see if there was a PowerShell way to do it.

**Comment by PrzemyslawKlys** [comment]
I believe I added the height part because of the expand button. Probably needs some work. If you can make a test that changing padding/height doesn't impact the visual part of HTML Tables I don't see why the change shouldn't be applied globally. Of course, we could potentially expose that as a parameter to the table but not sure there's a need for that?

**Comment by c3rberus** [comment]
The -Height controls the height of the overall table, I am interested in controlling the padding and height around each column inside the table.

Here is an example of the default styling: https://ibb.co/2NhzZKM
Here is an example by changing the <td> height/padding CSS: https://ibb.co/SRDphVq

Trying to basically reduce the white space inside the columns. Is it possible using some parameter or should I just change the CSS?

**Comment by PrzemyslawKlys** [comment]
I know which parameter you meant. Height/padding of a row. Try adding10 columns and compare again. Or resize the window so that the data won't fit. When you have Responsive "on" it adds a button, blue button +-. This button doesn't fit nicely without the 27 height per row as far as I remember.

**Comment by PrzemyslawKlys** [comment]
As for modifying the CSS yourself, well if you want you can always do that. But you will have to do it on each and every release, and as you can see on history of this module I do that pretty frequently.

**Comment by c3rberus** [comment]
I see what you mean about the blue button appearing, makes sense for 27 height per row. If I use -DisableResponsiveTable it would be nice to be able to adjust row height to show more data. The padding looks like, but sometimes it is about being able to see more data without having to scroll or page.

**Comment by PrzemyslawKlys** [comment]
That's a good idea. I'll try to implement it. Unless you want to take a stab at it?

**Comment by allemanie** [comment]
Goodmorning,

I was wondering if there was any update on this parameter.
I would really appreciate if it is possible to change the row height. 

In the past i changed datatables.css but it seems that file is splitted up. Can't find the correct CSS class anymore.

Thanks in advance.

**Comment by PrzemyslawKlys** [comment]
It changed it's location ever since I wrote Hashtable to CSS converter. This is the new location

https://github.com/EvotecIT/PSWriteHTML/blob/9a3ac0a1a32b9b1ce417f9fb0a2f9909eb112dbd/Private/Parameters.Configuration.ps1#L348-L350

The way to do it is to modify New-HTMLTable 

```powershell
$Script:CurrentConfiguration['Features']['DataTables']['HeaderAlways']['CssInline']["td"]['height'] = 'NewValue'
```

You would need to add some parameters and some logic to change this value if DisableResponsive is used (or anything that disables responsive).

**Comment by allemanie** [comment]
Really thank you for the fast response! 

I am not really familliar with creating/edditing PS modules but i've now added the follow to the new-htmltable function: 
`      [string] $RowHeight`

And at the top of the function added:
`    if($RowHeight){
        $Script:CurrentConfiguration['Features']['DataTables']['HeaderAlways']['CssInline']["td"]['height'] = $RowHeight
    }`

The following is now working:
`  New-HTMLTable -RowHeight "25px"`

I don't see any problems with the plus logo, but maby it is browser related?

**Comment by PrzemyslawKlys** [comment]
When you remove height totally that's what you get

Edge Chromium
![image](https://user-images.githubusercontent.com/15063294/99822447-85ae3a80-2b53-11eb-8dab-a752ae369c47.png)

IE 11
![image](https://user-images.githubusercontent.com/15063294/99822753-e473b400-2b53-11eb-82f6-12cb35bfb22f.png)

Firefox

![image](https://user-images.githubusercontent.com/15063294/99822845-fce3ce80-2b53-11eb-95c5-3900d1191bf8.png)

Changing it to 20px could work. IE/Firefox behaves very weird with this anyways. I don't remember now why I've chosen 27px but there was a reason.  Maybe we should try replacing the button positioning to be consistent across + I believe the + is not equal from each side. 

Like they show here:

https://datatables.net/examples/api/row_details.html

![image](https://user-images.githubusercontent.com/15063294/99823465-b8a4fe00-2b54-11eb-8eb9-9e036fdb1d9c.png)
![image](https://user-images.githubusercontent.com/15063294/99823495-bfcc0c00-2b54-11eb-8bf3-b578508f4073.png)

It requires some work and adjustments and figuring out the best, consistent way for this. I am not really happy with 27px as it takes a lot of space but I did it for a reason (not sure why now tho).

**Comment by PrzemyslawKlys** [comment]
I believe new version will fix it

![image](https://user-images.githubusercontent.com/15063294/100487183-a6543280-3107-11eb-855c-36a7f59d60cb.png)

I'm also fixing simplified version to be consistent with DataTables

![image](https://user-images.githubusercontent.com/15063294/100487190-b3712180-3107-11eb-98f6-269c0e12a83f.png)

Email version (noscript option) may require a bit different approach (outlook):

![image](https://user-images.githubusercontent.com/15063294/100487229-e0bdcf80-3107-11eb-9840-ce332f179f1a.png)

![image](https://user-images.githubusercontent.com/15063294/100487248-ed422800-3107-11eb-8fa7-03fa5d13d7da.png)

and on gmail:

![image](https://user-images.githubusercontent.com/15063294/100487279-08149c80-3108-11eb-9af6-7c7427150712.png)

I'm not really happy with padding/usability in Outllook/Gmail

**Comment by PrzemyslawKlys** [comment]
With center text, but without borders, it's a bit hard to read.

![image](https://user-images.githubusercontent.com/15063294/100487348-6c376080-3108-11eb-8bea-9a2abc2c67ec.png)

**Comment by PrzemyslawKlys** [comment]
![image](https://user-images.githubusercontent.com/15063294/100499169-abe16500-3167-11eb-9b52-a5125ea6c6cc.png)

I'll leave it like that for email
