### ISSUE TITLE
Underlined space when using -Collapsable

### ISSUE THREAD

**Issue by whoot** [EvotecIT/PSWriteHTML#51]
Hey, thanks for the fix of the "Missing space character when using '-Collapsable'" issue.
However, the space gets unerlined now:

![grafik](https://user-images.githubusercontent.com/8066322/65942239-2829cc80-e42d-11e9-8078-5fa09a4749ad.png)

**Comment by Tuxhedoh** [comment]
I'd be happy to attempt this if you can point me to the file that has this. I attempted to find the fix that was mentioned in the issue, but couldn't find where it was addressed.

**Comment by PrzemyslawKlys** [comment]
It's in the last else:
https://github.com/EvotecIT/PSWriteHTML/blob/e254e77bf51ca7f1032986649c2373ad3b236dba/Public/New-HTMLSection.ps1#L121-L122

Basically what needs to be done is one needs to remove space from -Text field on lines 121 and 122 and move that into line 120 (basically add space to $HeaderText instead.

https://github.com/EvotecIT/PSWriteHTML/blob/e254e77bf51ca7f1032986649c2373ad3b236dba/Public/New-HTMLSection.ps1#L120

**Comment by PrzemyslawKlys** [comment]
I guess better looking would be only link to Hide/Show word without () but that's a bit harder. You would probably need to write New-HTMLTag -Tag a and all that stuff to build a better version of it.

**Comment by PrzemyslawKlys** [comment]
Closing. Will release fix this weekend with some other stuff probably.

**Comment by PrzemyslawKlys** [comment]
Thanks, Tuxhedoh for help!
