### ISSUE TITLE
Possibility for own colors

### ISSUE THREAD

**Issue by ferwe** [EvotecIT/PSWriteHTML#52]
Hey Przemyslaw

Is there a posibility to use own colors? Something like RGB codes or similar?
I'm looking for a possibility to change to colors to corporate idendity.

Cheers
Ferdi

**Comment by PrzemyslawKlys** [comment]
It's not possible, but it makes sense to add that. You would need to find all functions that use [RGBColors], add another parameter that allows for own Color. 

Alternatively, we could convert [RGBColors] from Enum to a Hashtable and change it to Argument Completer without Validation. This would mean you get to use Colors from completer but if you type #348434 it will still work (we would need to modify the Color commands as well). 

What do you think?

**Comment by ferwe** [comment]
The second sounds easier to me, but I'm not sure how we could realize this as I don't really understand how you are handling [RGBColors] and how it finaly works. O_o

But it would please me to help you!

**Comment by PrzemyslawKlys** [comment]
It uses that: 
- https://github.com/EvotecIT/PSSharedGoods/blob/master/Private/Parameters/Script.RGBColors.ps1

And that:
- https://github.com/EvotecIT/PSSharedGoods/blob/master/Enums/RGBColors.ps1

Basically Enums define the names and then you have this:
- https://github.com/EvotecIT/PSSharedGoods/blob/master/Public/Converts/Convert-Color.ps1
- https://github.com/EvotecIT/PSSharedGoods/blob/master/Public/Converts/Convert-FromColor.ps1

So [RGBColors] is enum that is responsible for displaying names. I used it because I didn't know how to use argument completer and I didn't wanted to dynamic parameters as those are ugly. Now that I know one could probably get rid of it in favor of that. You can see this in Icons handling. 

When you Remove [RGBColors] and use Argument Completer it will do the same in terms of giving suggestions. Then we would skip the validation part for the parameter or write our own where the validation would verify whether it's a Key in a hashtable of colors (or maybe not even that - because I believe CSS takes color names as well if you provide proper one) and then whether it matches RGB syntax. We could in theory just skip validation at all.

**Comment by ferwe** [comment]
Ok, I got where you storing the RGB Codes and the Names.

That means, that the input for any color parameter could be a official colorname or RGB Code. Depends if the CSS accepting both.

So the ToDo's at least would be:
- Check if CSS accept both type of inputs
- Remove Validation
- Remove Enum and replace it with a hashtable
and some more stuff?!

**Comment by ferwe** [comment]
Ok sounds good.
I would start with the colors to ensure, that the colors and the related rgb values are correct.

If I'm right the function "ConvertFrom-Color" needs to be adjusted for HEX values, right?
Should be the easiest solution with less efort.

**Comment by PrzemyslawKlys** [comment]
Useful links:

- https://htmlcolorcodes.com/color-names/
- https://www.rapidtables.com/web/color/html-color-codes.html
- https://htmlcolorcodes.com/

We should support:
- defined HTML colors (hopefully names are the same as the ones I already defined) in [RGBColors] so we can just update the hex value if necessary 
- hex colors 
- potentially RGB but not sure it makes sense, probably easy enough 

Yes, we should add another parameter [string] $MultiColor or something where after reading the value it would guess whether it's RGB, Hex or defined color and convert it to a Hex value. I would leave [RGBColors] as is to maintain backward compatibility for other projects.

**Comment by ferwe** [comment]
I will crosscheck your names and rgb values with this list:
https://github.com/codebrainz/color-names/blob/master/output/colors.csv
The css colornames and values are also listed there.

In my opinion the HEX value is enough. There is no need for the RGB values.

I agree, the old parameter should stay for compatibility.

**Comment by PrzemyslawKlys** [comment]
That list is huge. However, it doesn't seem to have same color names as the ones define in HTML (it has spaces). 

What I would like is to have a list of "proper" colors from HTML that hopefully matches those I have defined, and hopefully matches those on that csv file to an extend. And then have all those 800+ colors available to users and then support HEX ? 

What do you think?

**Comment by ferwe** [comment]
What about the list here?:
https://www.w3.org/TR/css-color-3/#svg-color

**Comment by ferwe** [comment]
I would only supprt the 100+ colors from W3C.
Anything else can be done by HEX.
Do you agree?

**Comment by PrzemyslawKlys** [comment]
To be honest I kind of like idea of 800 colors :) I myself very rarely play with HEX and prefer autocomplete. If we're able to somehow deliver all three things (compatible naming with old scheme, compatible naming with 100+ colors from W3C and those 800 colors I would prefer that).

**Comment by ferwe** [comment]
OK
But in that case i would just go for the 800+ colors. The 100+ CSS colors should be in that list.

**Comment by PrzemyslawKlys** [comment]
Yes. But it's worth to random compare. It should be easy to compare 2-3 hashtables and find out if those 100 colors or colors I've defined actually are on that 800+ list. If yes.. great. if not we merge. But if you don't want to do that comparison that's fine. You can just focus on implementation and eventually I'll check and fill out any blanks.

**Comment by PrzemyslawKlys** [comment]
How is it going @ferwe ?

**Comment by ferwe** [comment]
Unfortunately I was busy with other stuff. But today i had some spare time and added the functionality.

Can we define https://github.com/EvotecIT/PSSharedGoods/blob/master/Private/Parameters/Script.RGBColors.ps1
as a global variable?
I need the content for validation and also for the ArgumentCompleter.
And at the moment the variable is only available inside PSSharedGoods if i get it right.

**Comment by PrzemyslawKlys** [comment]
Feel free to do whatever is necessary. I believe we should move the code regarding colors to PSWriteHTML, and maybe find out what we use in PSWriteHTML and copy that also to make PSWriteHTML standalone. The only other module that I know of that uses it is PSTeams and PSTeams has that incorporated.

**Comment by ferwe** [comment]
I removed RGBColors from PSSharedGoods and added a ArgumentCompleter and also changed the list from script to global.

you can see the changes here:
https://github.com/automatery/PSWriteHTML/tree/SupportHexColor

https://github.com/automatery/PSSharedGoods/tree/SupportHexCOlor

**Comment by ferwe** [comment]
I can easily move the color stuff to PSWriteHTML.

**Comment by ferwe** [comment]
I like the idea to make pswritehtml standalone!

**Comment by PrzemyslawKlys** [comment]
I think we can leave PSSharedGood as is and simply create new Colors in PSWriteHTML, then anything that's needed in PSWriteHTML for colors just copy it over (one command I guess). When PSWriteHTML will be fully standalone when it comes to colors I'll copy other stuff and update pssharedgoods. 

We could even leave PSSharedGoods as is with RGBColors for other projects and have our own version of Global:Colors. 

I don't see color updates there? Did you compare it with 800+ colors? 

Btw. why not make `ConvertFrom-Color -Color $BackGroundColor` support both HEX and Colors?

```
If($Color -match "^#([A-Fa-f0-9]{6})$"){
        $ColorHEX = $Color
    }
    elseif($Color -in $Global:RGBColors.Keys){
        $ColorHEX = ConvertFrom-Color -Color $Color
    }
```

You're using it that way but that means 20+ places where you need to work with same code over and over. If you make ConvertFrom-Color support Hex it will just work. You can create new command in PSWriteColor based on that one.

**Comment by ferwe** [comment]
> I don't see color updates there? Did you compare it with 800+ colors?

We will add the colors to the hashtable, if everything is done.

> You can create new command in PSWriteColor based on that one.

Did you mean PSWriteHTML or do you want me to add the Convert-FromColor to PSWriteColor?

So I will move the color stuff to PSWriteHTML. The convert-FromColor should be removed from PSSharedGoods to avoid duplicated commands.

**Comment by PrzemyslawKlys** [comment]
Of course i meant pswritehtml. I have so many pswrite modules that all mixes up.

**Comment by ferwe** [comment]
We are on the hashtable with the colors.
The other stuff is done. But before merging, you need finish Issue #67 I think.

I will create the PR if the colors are done.

**Comment by PrzemyslawKlys** [comment]
Will be in next release. Thank you for your work.
