### ISSUE TITLE
Bar chart stacking options not being applied

### ISSUE THREAD

**Issue by colin-hall** [EvotecIT/PSWriteHTML#59]
When I try to create stacked bar charts using 
`New-ChartBarOptions -Type barStacked` or `New-ChartBarOptions -Type barStacked100Percent` the resulting charts are not stacked.  

This happens both in my own code as well as in your examples, such as [https://github.com/EvotecIT/PSWriteHTML/blob/master/Examples/Example23-Charts/Example-ChartsBar.ps1](url)

It does not matter whether I use Firefox, Chrome, IE, or Edge.  
I'm using PSWriteHTML 0.0.54 and PowerShell 5.1

Thanks,
Colin

**Comment by PrzemyslawKlys** [comment]
Fix will be available in 0.0.55. Probably released over the weekend.
