### ISSUE TITLE
Create seating map

### ISSUE THREAD

**Issue by cconrado** [EvotecIT/PSWriteHTML#60]
Wanted to use this to create an office seating map based off a floor plan image. Is that possible?

**Comment by PrzemyslawKlys** [comment]
Not sure I follow how would you do it based on an image? You mean you want to use background image and then write your points manually or what is that you want to create? Also, wouldn't it be easier to do this with proper drawing tools?

**Comment by cconrado** [comment]
Yes as a background image and mark the point where to show Information. Well those tools have cost and this let's me write out everything in ps 😁.

**Comment by cconrado** [comment]
Basically I'm thinking of a staff seating chart that's tied to a lookup table. That I can host HTML file anywhere.

**Comment by PrzemyslawKlys** [comment]
Should be doable - needs this working first: https://github.com/EvotecIT/PSWriteHTML/issues/61 so someone needs to add this first. 

And then you would disable physics, make fixed x/fixed y/ use X and Y position and probably other options.

**Comment by cconrado** [comment]
Yup that's what I wanted to confirm if I missed it. I'll close this out then. Thanks.
