### ISSUE TITLE
Allow Image to be background for Diagram

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWriteHTML#61]
https://stackoverflow.com/questions/34902087/how-can-i-add-a-background-image-in-vis-js-in-network

**Comment by PrzemyslawKlys** [comment]
Added.

**Comment by cconrado** [comment]
That was fast 😂

**Comment by PrzemyslawKlys** [comment]
Ye, but it's without export option (as in the image doesn't "save"). May need to search for diff option.

**Comment by cconrado** [comment]
What you mean?

If the image is within the HTML file I'm good.

**Comment by PrzemyslawKlys** [comment]
I mean on HTML it's visible. However, Diagram allows you to right click on Diagram and you can save it as an image. So far the image isn't visible.

**Comment by cconrado** [comment]
Ah I can live with that now just gotta experiment how to do it
