### ISSUE TITLE
Diagrams - Link Diagrams with table data

### ISSUE THREAD

**Issue by thomwatt** [EvotecIT/PSWriteHTML#64]
I've recently discovered PSWriteHTLML and I think the diagram functionality is awesome! I was looking for a way I could generate documentation based on IT configuration data (servers and their properties for example) and this looks like it will really help.

In my use case, I'll have many powershell objects describing nodes (servers) and its properties (IP Address, network zone, location etc.) I can see how I can easily generate a diagram from these objects but what I'd like to do is to click a node in a diagram then see the properties associated with it (it's IP address etc.) maybe in a linked table by click event.

Is this possible currently? - I don't think it is. If not, would you be able to add this functionality?

Many thanks
Tom

**Comment by PrzemyslawKlys** [comment]
It's not possible, but I've experimented with it and got a functional prototype. The thing I'm wondering about is how to affect the table. Should I just highlight the row with color or simply tell the table to do this via the Search field which will narrow the choice to only 1 (or more elements if they have similar names).

**Comment by thomwatt** [comment]
Thanks for the quick reply! I was thinking:

The nodes in a diagram could be of different types (servers, network devices, software, etc.) and therefore have a different set of properties. In this scenario a filter may not work as you would need a table that catered for a all parameter sets.

Is another option to generate a form displaying the properties of an individual node on click?

**Comment by PrzemyslawKlys** [comment]
Take a look at what is possible and see if there's anything you like: https://visjs.github.io/vis-network/examples/ 

That's the prototype I mentioned

![DWOYbCiHGT](https://user-images.githubusercontent.com/15063294/66478414-a542ea80-ea9a-11e9-9730-be382fe1c64e.gif)

So as you see, a popup + highlight in a table.

**Comment by PrzemyslawKlys** [comment]
Also, it should be possible to link different nodes to different tables.

**Comment by thomwatt** [comment]
That looks good and if we can link to different tables then that should be ok. Given your options, I'd vote for the highlight over the filter as I can see benefit in comparing highlighted nodes with others in the table.

Do you have a target date for this :)

**Comment by PrzemyslawKlys** [comment]
Probably sometime this month if I don't get overloaded with other stuff. The trick is to make it easy to define for a user how objects are linked to tables. 
```
New-DiagramEvent -OnClick -ID 'Node 1' -TableID 'TableID' -TableValue 'Node 1' -TableColumn 'ID' 
```
Then you would need to be allowed to define your own TableID parameter (normally it's autogenerated) so that you're aware how to link this to diagram.

**Comment by PrzemyslawKlys** [comment]
Till that happens you could play with a title (popup):

![image](https://user-images.githubusercontent.com/15063294/66479372-a543ea00-ea9c-11e9-8d2c-cdf95e71c89f.png)

**Comment by thomwatt** [comment]
Sounds good, I look forward to it and I'll give you feedback.

The New-DiagramEvent looks easy enough to me.

Thanks

**Comment by PrzemyslawKlys** [comment]
![PSWriteHTML-DiagramEvents](https://user-images.githubusercontent.com/15063294/66702665-513e3d00-ed0a-11e9-81c5-290ece9eed78.gif)

What do you think?

**Comment by PrzemyslawKlys** [comment]
Actually the command dso far is:

```
                    New-DiagramEvent -ID 'SpecialID123' #5-FadeSearch
                    New-DiagramEvent -ID 'OtherTable'
```

So kind of just telling Diagram to link tables, in that case, 2 tables.

**Comment by thomwatt** [comment]
It looks fantastic! Cant wait to try it out.

Many thanks for including this

**Comment by PrzemyslawKlys** [comment]
You already can. https://evotec.xyz/nested-tabs-diagram-updates-diagram-events-calendar-object-and-more-in-pswritehtml/ the command requires ColumniD for now but should bd good enough.

**Comment by thomwatt** [comment]
Great! Really good write up too. The hierarchy view will be really useful for me.

Thanks Again
