### ISSUE TITLE
Report tabs no longer work in Internet Explorer

### ISSUE THREAD

**Issue by DyoGTS** [EvotecIT/PSWriteHTML#71]
When creating an HTML report using the current version of PSWriteHTML, we are no longer able to click any in Internet Explorer. This occurs whether we open the html locally or upload it to SharePoint. Chrome works fine.
This was previously working fine using Dashimo 0.0.12, and may be related to the open issue with the paging options in IE?

**Comment by PrzemyslawKlys** [comment]
If it stopped working recently its related to nested tabs. Nested taba required diff engine so basically I’ve removed old code and added new one. From PSWriteHTML perspective nothing changed. Behind scenes everything did. Its possible new approach is too new for IE. Does it work with Edge? I’ll take a look, but I dont have high hopes. Most likely there will be two choices: add old code with a swith like -Compatibility where you loose nested tabs or juat get rid of IE once and for all.

**Comment by DyoGTS** [comment]
Unfortunately we rely too heavily on IE at my company, so I have to make sure it works there. For now I have just reverted to the old modules, which is fine (except if you use auto refresh it returns to the first tab). I can confirm that it also does not work in Edge.

**Comment by PrzemyslawKlys** [comment]
Give this a go: https://evotec.xyz/wp-content/uploads/2019/10/Example30-NestedTabs.html

Diagrams don't work, but Tabs/Calendar do work. Diagrams work in Edge.
