### ISSUE TITLE
Releases in this repository

### ISSUE THREAD

**Issue by michalzobec** [EvotecIT/PSWriteHTML#72]
Hello,

thank you for your project. I have a big request. Can you use releases here in GitHub repositories? Many of the servers I work with are offline, so I cannot use PowerShell Gallery. And too option watch "Releases only" here is more comfortable. ;)

Thank you very much
Michal

**Comment by PrzemyslawKlys** [comment]
Hi,

I need to implement a better publishing process. Until this is done you can use this process: https://evotec.xyz/making-powershellgallery-modules-portable/ 

I wrote it for Testimo but should work for PSWriteHTML or any other PSGallery module. 

Przemek

**Comment by michalzobec** [comment]
okay, I will try it

**Comment by michalzobec** [comment]
okay, sorry :)

**Comment by PrzemyslawKlys** [comment]
Will be done for the next release

**Comment by michalzobec** [comment]
thank you :)
