### ISSUE TITLE
0.0.58 Issues

### ISSUE THREAD

**Issue by madmax01** [EvotecIT/PSWriteHTML#75]
How can it be possible to force an specific PSWriteHTML together with Dashimo to be installed?

i installed somewhere else.  and Dashimo installed 0.0.58.

that version broke my Buttons and my conditional formats

How is Conditional Formating working with 0.0.58 ? i didn't had any Issues with 0.0.57

Below worked with 0.0.57.  with 0.0.58  (buttons are away, conditional formats away,... sortings away,...)

New-HTMLSection -HeaderText 'Test' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $mytest -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength{
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value green -BackgroundColor green
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value yellow -BackgroundColor yellow
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value red -BackgroundColor red
}
}

if i change to this.   (i see the Buttons,.... but the HTMLTableCondition is ignored)

New-HTMLSection -HeaderText 'Test' -CanCollapse -Collapsed {
New-HTMLTable -DataTable $test -HideFooter  -Buttons copyHtml5,excelHtml5,csvHtml5,pdfHtml5,pageLength
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value green -BackgroundColor green
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value yellow -BackgroundColor yellow
New-HTMLTableCondition -ComparisonType string -Name 'Status' -Operator eq -value red -BackgroundColor red
}

**Comment by madmax01** [comment]
i de/installed dashimo and pswritehtml.  i then installed just pswritehtml with requiredversion 0.0.57.   all  works again.

**Comment by PrzemyslawKlys** [comment]
Published 0.0.59. Had to use higher version of DataTables. In 0.0.58 I've downgraded DataTables to 1.10.12 because it works in IE. 1.10.20 doesn't. They fixed it on my bug report in 1.10.21-dev. Wanted to wait for 1.10.21 release but it may take time. Using nightly in 0.0.59. Hopefully, it won't break anything else.
