### ISSUE TITLE
AutoRefresh in IE reverts to first tab

### ISSUE THREAD

**Issue by DyoGTS** [EvotecIT/PSWriteHTML#78]
When creating a dashboard using the -AutoRefresh option, Internet Explorer always reverts back to the first tab, while Chrome will stay on whichever tab you're already looking at.

This may be a limitation of IE, but it would be great if we can get it to match the behavior of Chrome.

**Comment by PrzemyslawKlys** [comment]
This is because IE doesn't support Local Storage for Local files (only hosted ones should work). Local Storage is used to keep tabs open the way they are. 

There is a workaround for that: https://stackoverflow.com/questions/3392032/localstorage-object-is-undefined-in-ie but that's a hacky hack and requires zone changes.

**Comment by DyoGTS** [comment]
I should clarify that in my instance the file is being housed on our Sharepoint server, and site is in the Trusted sites zone. Would this still be the case?

**Comment by PrzemyslawKlys** [comment]
Open up IE console

![image](https://user-images.githubusercontent.com/15063294/68890252-c6909980-071e-11ea-8bce-f3c74b32d044.png)

And wait for things to happen. See if the message shows up. I'm doing try/catch.

As far as I understand this should work  on Hosted IE. 

You can try this and verify that local storage indeed works:

https://stackoverflow.com/questions/9539877/viewing-local-storage-contents-on-ie

**Comment by DyoGTS** [comment]
Yep, I can confirm that this is the same error on our hosted Sharepoint server.

![image](https://user-images.githubusercontent.com/56728841/68893753-68968e80-06eb-11ea-94a1-2ae9e60b208d.png)

![image](https://user-images.githubusercontent.com/56728841/68893781-777d4100-06eb-11ea-8f1f-65d0621fefef.png)

**Comment by PrzemyslawKlys** [comment]
This is related to this code:

https://github.com/EvotecIT/PSWriteHTML/blob/7e6f374d8853370dce10833505c6e5009c98978f/Resources/JS/tabbis.js#L86-L95

not sure if we can fix this. I don't know that much about JS

**Comment by PrzemyslawKlys** [comment]
Potentially to test if 

```html
<!DOCTYPE html>
<script>
  localStorage.setItem('test', '12345');
  alert(localStorage.getItem('test'));
  localStorage.clear();
</script>
```

Works as hosted page.
