### ISSUE TITLE
New-HTMLSection - Align Content to center

### ISSUE THREAD

**Issue by xlrod** [EvotecIT/PSWriteHTML#79]
Hello,

I haven't been able to get the content of a `New-HTMLSection` to be centered with the `-AlignContent` or the `-AlignItems` parameters. I ended up adding a new parameter to accept `-JutifyContent` and added the same string options as `-AlignItems`.

I added this below line 10383.
`[string][ValidateSet('stretch', 'flex-start', 'flex-end', 'center', 'baseline')] $JustifyContent`

Added the if/else below line 10446:
`    if($JustifyContent){
        $JustifyContent = "justify-content: $JustifyContent"
    } 
    else {
        $JustifyContent = "justify-content: baseline"
    }`

And also added the Style attribute on line 10488:
`-Attributes @{ class = "$ClassName collapsable"; id = $RandomNumber; Style = $JustifyContent; }`

After this, I was able to center the content I placed inside the `New-HTMLSection`.

Here's the code I was using which always ended up with the content/text aligned to the left, no matter the parameters selected:

`New-HTMLSection -HeaderText "Pending Load" -HeaderTextAlignment center -HeaderTextColor WhiteSmoke -HeaderBackGroundColor DarkBlue -AlignContent center {
                    "10"
                }`
![text alignment](https://user-images.githubusercontent.com/48139416/68897572-ca5ef480-06fb-11ea-89d9-e10bb9f7e753.png)

Was I doing something wrong or has this not been implemented yet?

**Comment by PrzemyslawKlys** [comment]
I was experimenting with those options, but couldn't get consistent output so I let it go and haven't really announced that feature. 

I'm a bit noob when it comes to HTML/CSS/jS so I get lost a lot ;)

**Comment by xlrod** [comment]
I've changed this and now it seems to work a bit better.
Changed the if/else statement to this:
 `    if($null -eq $JustifyContent){
        $JustifyContent = "baseline"
    } `

And changed the Style section to this:

`Style = "justify-content: $JustifyContent";`

**Comment by PrzemyslawKlys** [comment]
Would you be able to provide some usage examples, along with how would it work or not work with standard sections and other code? While playing with my code I was having inconsistent results when matching with standard settings. Can you provide some insight on how this will work/not work, what are the use cases and finally submit a PR?

**Comment by xlrod** [comment]
The only use case that prompted me to research this was making a number count that was centered instead of aligned to the left.

I tried to use both the `-AlignContent` and the `AlignItems` but did not center the text.
Also tried doing a `New-HTMLText` with the `-Alignment center` but still.
Playing with the elements I found that justify-content seemed to work.

![justify](https://user-images.githubusercontent.com/48139416/69364691-c46b9500-0c60-11ea-8b19-6f7f2f2476d7.JPG)

![justify2](https://user-images.githubusercontent.com/48139416/69364692-c59cc200-0c60-11ea-9cb7-8cf3d65dcc00.JPG)


    $Table = [PSCustomObject]@{
        Title = "Mr"
        GivenName = "John"
        SurName = "Doe"
        Phone = "555-5555"
    }

    New-HTML -TitleText "FST Monitor" -FilePath "$PSScriptRoot\Test-Dashboard.html" {
        # Text Section
        New-HTMLSection -HeaderText "Align Content / AlignItems" { 
            # Try to align text to center - AlignContent
            New-HTMLSection -HeaderText "Load Count" -AlignContent center {
                "100"
            }
            # Try to align text to center - AligntItems
            New-HTMLSection -HeaderText "Load Count" -AlignItems center {
                "200"
            }
            # Try to align text to center - New-HTMLText
            New-HTMLSection -HeaderText "Load Count" -AlignContent center {
                New-HTMLText -Text "300" -Alignment center
            }       
        }

        # Text Section
        New-HTMLSection -HeaderText "Justify Content" {
            # Try to align text to the left - JustifyContent
            New-HTMLSection -HeaderText "Load Count" -JustifyContent flex-start {
                "100"
            }
            # Try to align text to center - Justify Content
            New-HTMLSection -HeaderText "Load Count" -JustifyContent center {
                "200"
            }
            # Try to align text to right - New-HTMLText
            New-HTMLSection -HeaderText "Load Count" -JustifyContent flex-end {
                "300"
            }
        }
        # The JustifyContent doesn't work with anything other than text.
        New-HTMLSection -HeaderText "Data" -JustifyContent flex-end {
            New-HTMLTable -DataTable $Table {}
        }
    }


This is my current usage:
![current](https://user-images.githubusercontent.com/48139416/69364901-3a6ffc00-0c61-11ea-9b5d-a9cfaa4b0953.png)

**Comment by PrzemyslawKlys** [comment]
So basically we're trying to control content if it's not 100% width. It's a good idea.

**Comment by PrzemyslawKlys** [comment]
Part of 0.0.66 release. Thank you
