### ISSUE TITLE
PSHTML

### ISSUE THREAD

**Issue by spaelling** [EvotecIT/PSWriteHTML#8]
Have you seen [PSHTML](https://github.com/Stephanevg/PSHTML)?

**Comment by PrzemyslawKlys** [comment]
I did. I've contact to the author on Twitter. I thought about using it but it did require opening and closing within the same function so I dropped that idea since we were explicitly using -Open / -Close in different functions. Now that we have one function to open/close it's feasible to use it. We can even bundle it up.

Question is if it's needed and what benefits does it bring. 

In new version I've creaetd `Set-Tag` function which is able to take HashTable and build HTML an object out of it. 

```
function Add-HTMLImage {
    <#
    .SYNOPSIS


    .DESCRIPTION
    Long description

    .PARAMETER Source
    Parameter description

    .PARAMETER UrlLink
    Parameter description

    .PARAMETER AlternativeText
    Parameter description

    .PARAMETER Class
    Parameter description

    .PARAMETER Target
    Parameter description

    .PARAMETER Width
    Parameter description

    .PARAMETER Height
    Parameter description

    .EXAMPLE
    Add-HTMLImage -Source 'https://evotec.pl/image.png' -UrlLink 'https://evotc.pl/' -AlternativeText 'My other text' -Class 'otehr' -Width '100%'

    .NOTES
    General notes
    #>

    [CmdletBinding()]
    param(
        [string] $Source,
        [Uri] $UrlLink = '',
        [string] $AlternativeText = '',
        [string] $Class = 'Logo',
        [string] $Target = '_blank',
        [string] $Width,
        [string] $Height
    )
    [System.Collections.IDictionary] $Image = [Ordered] @{
        Tag        = 'img'
        Attributes = [ordered]@{
            'src'    = "$Source"
            'alt'    = "$AlternativeText"
            'width'  = "$Height"
            'height' = "$Width"
        }
        Value      = '' # if value is blank it will not be used
    }

    [System.Collections.IDictionary] $A = [Ordered] @{
        Tag        = 'a'
        Attributes = [ordered]@{
            'target' = $Target
            'href'   = $UrlLink
        }
        Value      = $Image
    }

    [System.Collections.IDictionary] $Div = [Ordered] @{
        Tag        = 'div'
        Attributes = [ordered]@{
            'class' = "$Class".ToLower()
        }
        Value      = $A
    }
    $HTML = Set-Tag -HtmlObject $Div
    return $HTML

}
```

It basically works in a way where if you define just Tag and nothing else it will create `<a />` if you fill in any attributes only those with value will be created so `<a src=".." />` and if you fill in value it will do `<a src=".."> SomeValue</a>`


It also supports what you see above so Tag within tag within tag.

```powershell
Add-HTMLImage -Source 'https://evotec.pl/image.png' -UrlLink 'https://evotc.pl/' -AlternativeText 'My other text' -Class 'otehr' -Width '100%'
```
Gives you this:
```html
<div class="otehr">
    <a target="_blank" href="https://evotc.pl/">
        <img
            src="https://evotec.pl/image.png"
            alt="My other text"
            height="100%"
        />
    </a>
</div>
```

My idea was that at some point in time I would rewrite everything that way and make Hashtable conversion at the very end on Save-HTML. What that would give you? You could save HashTable object, leave it next to generated HTML. If you then want to modify report you could just take that CustomObject, and add new Page to it, or expand body. It's something that could be useful but maybe not worth time.

**Comment by PrzemyslawKlys** [comment]
For your visibility - https://github.com/Stephanevg

**Comment by spaelling** [comment]
Now I've had some time to actually read what PSHTML does. I see the difference. So thinking out loud here; Would it make sense to leverage the work done in PSHTML to generate some of the html code (perhaps less focus on "writing" html)? Ex. to create a barchart with PSHTML an example below (somewhat more elegant than what is going on in [Get-HTMLBarChart.ps1](https://github.com/EvotecIT/PSWriteHTML/blob/master/Public/Get-HTMLBarChart.ps1)

This would mean the outcome is somewhat similar in many cases. I think PSHTML would require more work to achieve the same, but is also more "free". One can customize the outcome more, but the work has to be put in. in PSWriteHTML some choices are made for you which in many cases is a good thing.

Something else that could benefit from this is that it may be possible to generate the html using both approaches. Maybe in some cases one wishes to have abit more customized output, ex.

```powershell
New-HTML -Header {
        Header {
            h1 "This is h1 Title in header"
            div {
                p {
                    "This is simply a paragraph in a div."
                }
            }
        }
}
```

```powershell
import-module PSHTML


$BarCanvasID = "barcanvas"
$HTMLPage = html { 
    head {
        title 'Bar Chart'

    }
    body {

        h1 "PSHTML Graph"

        div {

           p {
               "This is a bar graph"
           }
           canvas -Height 400px -Width 400px -Id $BarCanvasID {

           }

       }

        script -src "https://cdnjs.cloudflare.com/ajax/libs/Chart.js/2.7.3/Chart.min.js" -type "text/javascript"

        script -content {


            $Data3 = @(4,1,6,12,17,25,18,17,22,30,35,44)
            $Labels = @("January","February","Mars","April","Mai","June","July","August","September","October","November","december")

            $dsb3 = New-PSHTMLChartBarDataSet -Data $data3 -label "2018" -BackgroundColor ([Color]::blue )

            New-PSHTMLChart -type bar -DataSet $dsb3 -title "Bar Chart Example" -Labels $Labels -CanvasID $BarCanvasID

        }

    }
}


$OutPath = "$Home\BarChart1.html"
$HTMLPage | out-file -FilePath $OutPath -Encoding utf8
start $outpath
```

Also I like the idea of inputting hashtables and outputting html. Somewhat similar to using Out-GridView which I use fairly often to present data.

**Comment by PrzemyslawKlys** [comment]
It makes sense in some cases. We can add PSHTML to required modules for PSWriteHTML and use it where it makes sense. There's really nothing stopping you to use a mix PSWriteHTML with PSHTML. The way it's built now without open/close tags you can simply do:

```
Import-Module PSWriteHTML -Force

$Time = Start-TimeLog

$ReportTitle = 'Test'

$ReportPath = "$PSScriptRoot\Example4.html"

$DomainAdminTable = Get-ADForest | Select-Object ForestMode, Name, RootDomain, SchemaMaster
$EnterpriseAdminTable = Get-ADuser -Filter * | Select-Object Name, Surname, Enabled, DisplayName
$Allusers = Get-AdUser -Filter *

$TabNames = 'Dashboard', 'Something'

$Report = New-HTML -TitleText $ReportTitle -HideLogos -AddAuthor -HideDate -UseCssLinks -UseStyleLinks -Verbose {
    New-HTMLTabHeader -TabNames $TabNames
    New-HTMLTab -TabName 'Dashboard' {
        h1 "Some PSHTML text"
        div { 

        }
        New-HTMLHeading -Heading h3 -HeadingText 'This is a test'
        New-HTMLContent -HeaderText "Groups" {
            New-HTMLHeading -Heading h3 -HeadingText 'This is a test'
            New-HTMLContent -BackgroundShade 1 -HeaderText 'Domain Administrators' -CanCollapse {
                Get-HTMLContentTable -DataTable $EnterpriseAdminTable -Verbose
            }
            New-HTMLContent -BackgroundShade 1 -HeaderText 'Domain Administrators' -CanCollapse {
                Get-HTMLContentDataTable -DataTable $EnterpriseAdminTable -Verbose
            }
        }
    }
}
Save-HTML -HTML $Report -FilePath $ReportPath -ShowHTML
Stop-TimeLog -Time $Time -Option OneLiner
```

So a mix should already be possible. The bigger issue will be with CSS I guess but that could be addressed by using PSHTML to apply CSS as well.

**Comment by Stephanevg** [comment]
Thanks for looking into PSHTML @spaelling 

>  I think PSHTML would require more work to achieve the same, but is also more "free"
Yeah, that is exactly the idea behind PSHTML, where I want to offer the flexibility to people to create their own creations.

like said on twitter, I do have a few abstractions already: 'Convertto-PSHTMLTable' or 'New-PSHTMLChart' are good examples, but my intention is to offer more to the end users over time, **but** still offering flexibility that one would expect with HTML.

> Also I like the idea of inputting hashtables and outputting html.

The hashtables are there to offer the possibility to add custom attributes to different HTML tags. Normally (I said, normally ;) ) all the supported ~~HTML5~~ attributes 'should' be available on each tag.

I do have a lot of things planned for PSHTML, and I am defintley looking for contributors and PR's (Free beer guaranteed for when we meet ;) )

**Comment by Stephanevg** [comment]
There is also [UniversalDashboard](https://ironmansoftware.com/products/powershell-universal-dashboard) from [Adam](https://github.com/adamdriscoll) which is **not** free, and is really advanced. but again, it offers a high level of abstraction, which you might not want to have all the time.

I guess it all end up on preference and use cases.

**Comment by PrzemyslawKlys** [comment]
To be honest it all boils down to getting some guy who knows HTML/CSS and JS really well. For me, it's a bit of try/catch scenario where I try what works. One could probably add/create what Adam did because most of it is probably open source JS (charts, highlighting and other stuff). And CSS should be done by guy who can tell the difference between colors ;-)

**Comment by spaelling** [comment]
> To be honest it all boils down to getting some guy who knows HTML/CSS and JS really well. For me, it's a bit of try/catch scenario where I try what works. One could probably add/create what Adam did because most of it is probably open source JS (charts, highlighting and other stuff). And CSS should be done by guy who can tell the difference between colors ;-)

I myself is fairly handicapped when it comes to html, css, and js. I can get stuff to work, but slowly.

**Comment by Stephanevg** [comment]
> And CSS should be done by guy who can tell the difference between colors ;-)
LOL!!

**Comment by spaelling** [comment]
> > Also I like the idea of inputting hashtables and outputting html.
> 
> The hashtables are there to offer the possibility to add custom attributes to different HTML tags. Normally (I said, normally ;) ) all the supported HTML5 attributes 'should' be available on each tag.
> 
> I do have a lot of things planned for PSHTML, and I am defintley looking for contributors and PR's (Free beer guaranteed for when we meet ;) )

The mention of hashtables was in regards to PSWriteHTML.

Wrt. contributing that would come naturally if `PSWriteHTML` leverages the work done in `PSHTML`. For me I just want the best tool for the job. If I have something to contribute then I usually do.
