### ISSUE TITLE
Creating a 2 column table

### ISSUE THREAD

**Issue by ParadoX-SobriuS** [EvotecIT/PSWriteHTML#82]
Hi,

I've just started with this module and I am having trouble finding all I want, don't know if it is due to the lack of documentation for the Get-Help command or me not being able to read it correctly :)

I've earlier used the Get-HTMLContentText -heading "my header" -detail "Detail Data" from the ReportHTML module and I am searching for a similar solution in your module but I am really not finding it, or just stupid...

I know this is not an issue at this point but I really would like to find a solution to this, either me re-building my code or an already existing function in your module.

Thanks in advance.

**Comment by PrzemyslawKlys** [comment]
Can you show an output you expect? 2 column table means one table with 2 columns and i am not sure if thats what you want?

**Comment by ParadoX-SobriuS** [comment]
Hi, thanks for the quick reply. Using the ReportHTML module the code is:
`$fileReport += Get-HTMLContentText -Heading "Supported Capabilites" -Detail "$($RootDSE.supportedCapabilities)"`
`$fileReport += Get-HTMLContentText -Heading "Supported Control" -Detail "$($RootDSE.supportedControl)"`
`$fileReport += Get-HTMLContentText -Heading "Supported LDAP Policies" -Detail "$($RootDSE.supportedLDAPPolicies)"`

Output would look something like the following:
![Annotation 2019-11-19 152912](https://user-images.githubusercontent.com/23219717/69155088-649ab000-0ae1-11ea-985b-f57e8f9b94ff.png)

I can with above code set the "Heading" in the code and use the variable-data for the Details. I am thinking that I might need to make this a PSCustomObject instead for it to work in a New-HTMLTable with your module.

**Comment by PrzemyslawKlys** [comment]
You can simply prepare your data:

```powershell
$RootDSE = Get-ADRootDSE
$TranslatedRootDSE = [ordered] @{ }
foreach ($Key in $RootDSE.PSObject.Properties.Name) {
    $TranslatedRootDSE["$Key"] = $RootDSE.$Key -join ','
}
```

And then use (ad-hoc usage):
```powershell
$TranslatedRootDSE | Out-HtmlView -DisableResponsiveTable
```

More structure, with more stuff in it. 

```powershell
New-HTML {
    New-HTMLSection -Invisible {
        New-HTMLSection -HeaderText 'Root DSE' {
            New-HTMLTable -DataTable $TranslatedRootDSE
        }
        New-HTMLSection -HeaderText 'Some other stuff' {
            New-HTMLTable -DataTable $TranslatedRootDSE
        }
    }
} -FilePath $PSScriptRoot\Test.html -ShowHTML
```

**Comment by PrzemyslawKlys** [comment]
And if you're into AD you shoud look into:
https://github.com/EvotecIT/PSWinDocumentation

And especially:

https://github.com/EvotecIT/PSWinDocumentation.AD project 

It has a lot of options already prepared and done: https://github.com/EvotecIT/PSWinDocumentation.AD/blob/master/Examples/Run-Manual-Dashimo.ps1

**Comment by PrzemyslawKlys** [comment]
For documentation on PSWriteHTML you have to refer to this one: https://evotec.xyz/emailimo-merged-into-pswritehtml-ie-support-and-no-dependencies/ and go to the bottom - there are links that show usage of PSWriteHTML with examples. You can also look for examples on GitHub

**Comment by ParadoX-SobriuS** [comment]
Awesome! Thank you.
I've tested the PSWinDocumentation.AD but the environment I am running in is so large that the module doesn't work properly and running it as a regular user has many failures. But that is a different scenario/discussion.
I'll check the links in the bottom for further learning!

Keep up the good work!
