### ISSUE TITLE
New-HTMLTab - Add TextTransform

### ISSUE THREAD

**Issue by xlrod** [EvotecIT/PSWriteHTML#83]
Hello again,

On the dashboard that I've been working on thanks to your module, I wanted to use capitalized text for my tabs instead of uppercase. I've added the `-TextTransform` parameter to the `New-HTMLTab` function on line 10694: `,[ValidateSet('uppercase', 'lowercase', 'capitalize')][string] $TextTransform`

Also added the if/else on line 10726:

    if($TextTransform){
        $StyleText.'text-transform' = "$TextTransform"
    }
    else{
        $StyleText.'text-transform' = "uppercase"
    }

`New-HTMLTab -Name "Main" -IconRegular map -TextTransform capitalize {}`

![tab](https://user-images.githubusercontent.com/48139416/69269432-00d6bc80-0b9f-11ea-8671-9d86a3d744f3.JPG)

![capitalize](https://user-images.githubusercontent.com/48139416/69269339-cff68780-0b9e-11ea-975a-d78a9eae219a.JPG)

Thanks again for your hard work!

**Comment by PrzemyslawKlys** [comment]
Would you be able to submit this as PR?

**Comment by PrzemyslawKlys** [comment]
added to 0.0.64
