### ISSUE TITLE
New-HTMLSection should allow for non-rounded corners and borders definition

### ISSUE THREAD

**Issue by PrzemyslawKlys** [EvotecIT/PSWriteHTML#94]

**Comment by xlrod** [comment]
We could add the `$BorderRadius` parameter with a set of options, similar to what `New-HTMLTabOptions` is using.
[ValidateSet('0px', '10px', '15px', '25px')][string] $BorderRadius = '0px'

**Comment by PrzemyslawKlys** [comment]
This should work, but maybe there are other types of customizations we could think of? I see a lot of cool dashboards projects on the web and would like to be able to have PSWriteHTML/Dashimo to deliver those as well. I'll put some ideas here: https://github.com/EvotecIT/PSWriteHTML/issues/97
