### ISSUE TITLE
New-HTMLTableCondition and IE11

### ISSUE THREAD

**Issue by opustecnica** [EvotecIT/PSWriteHTML#98]
When using the 'like' and 'contains' operators in ___New-HTMLTableCondition___ and viewing the output in ___IE11___, the unsupported (IE11) 'includes' JS method breaks DataTables.  

Simple fix below.

LIne 3529 of PSWriteHTML.psm1
```posh                    
switch ($Condition.Operator) {
    "contains" {
        # "if (data[$($ConditionHeaderNr)].includes('$($Condition.Value)')) {"
        "if (data[$($ConditionHeaderNr)].indexOf('$($Condition.Value)') >= 0 ) {"
    }
    "like" {
        # "if (data[$($ConditionHeaderNr)].includes('$($Condition.Value)')) {"
        "if (data[$($ConditionHeaderNr)].indexOf('$($Condition.Value)') >= 0 ) {"
    }
    default {
        "if (data[$ConditionHeaderNr] $($Condition.Operator) '$($Condition.Value)') {"
    }
}
```
This could be further simpified by using the '___-Regex___' parameter for the switch statement.
```posh
switch -Regex ($Condition.Operator) {
    "contains|like" {
        "if (data[$($ConditionHeaderNr)].indexOf('$($Condition.Value)') >= 0 ) {"
    }
    default {
        "if (data[$ConditionHeaderNr] $($Condition.Operator) '$($Condition.Value)') {"
    }
}
```

**Comment by PrzemyslawKlys** [comment]
Would you submit a PR for this?

**Comment by PrzemyslawKlys** [comment]
It's located in here:

https://github.com/EvotecIT/PSWriteHTML/blob/eb2f5cb1c429849eb5694f9f0799c70db672d15f/Private/Tables/New-TableConditionalFormatting.ps1#L34-L55

**Comment by opustecnica** [comment]
On travel at the moment.  Will complete ASAP.  THX

**Comment by opustecnica** [comment]
Przemysław,

The PR was executed.  Please let me know if more is needed.

THX

**Comment by PrzemyslawKlys** [comment]
Hi,

I noticed. Thank you - Added my comment to PR https://github.com/EvotecIT/PSWriteHTML/pull/100

**Comment by PrzemyslawKlys** [comment]
I think we can safely close this as this was already taken care of. If not please reopen.
