### ISSUE TITLE
New-HTML -FavIcon

### ISSUE THREAD

**Issue by xlrod** [EvotecIT/PSWriteHTML#99]
Hello, 

I've added the `-FavIcon` parameter to `New-HTML` to allow for favicons for the dashboards.

![image](https://user-images.githubusercontent.com/48139416/71634874-8c575a80-2bed-11ea-898f-88a7447c3299.png)

![image](https://user-images.githubusercontent.com/48139416/71634784-063b1400-2bed-11ea-9803-828c102fe32a.png)

    $Table = Get-Process | Select-Object -First 5

    New-HTML -TitleText "Test-Dashboard" -FavIcon "$PSScriptRoot\138544-interaction-assets\png\file-2.png" -FilePath "$PSScriptRoot\Test-Dashboard.html" {
        New-HTMLTable -DataTable $Table
    }

Is there any type of validation I should add aside from an if statement with a `Test-Path`?

    if(Test-Path -Path $FavIcon){
        New-HTMLTag -Tag 'link' -Attributes @{rel = 'icon'; href = "$FavIcon"; type = 'image/x-icon'}
    }

I was thinking of doing the `Test-Path` with `-Filter` for allowed favicon formats.

**Comment by PrzemyslawKlys** [comment]
Hello,

Well, it needs to support:
- standard "filesystem" files which then needs to be converted to binary format
- https:// link

I wonder how to give people a choice to convert https links to binary format as well. If at all should be considered. 

Otherwise, your implementation makes sense

**Comment by PrzemyslawKlys** [comment]
How is this going?

**Comment by xlrod** [comment]
I'm going to be testing your suggestions this week.
I saw you already had a function to convert an image to binary, so I will try that first.

**Comment by xlrod** [comment]
I've added a some of your functions/code to the validation.

The parameter `FavIcon` is still a string, that expects the path of the image, (Eg. "C:\users\xlrod\image\icon.png") and the check is as follows:

    $Extension = $FavIcon -replace ".*(?=\.)"
    if ($Extension -in @('.png', '.jpg', 'jpeg', '.svg', '.ico')) {
        if(Test-Path -Path $FavIcon){
            $FavIcon = Get-Item -Path $FavIcon
            $FavIconImageBinary = Convert-ImageToBinary -ImageFile $FavIcon
            New-HTMLTag -Tag 'link' -Attributes @{rel = 'icon'; href = "$FavIconImageBinary"; type = 'image/x-icon'}
        }
        else{
            Write-Warning -Message "The path to the FavIcon image could not be resolved."
        }
    }
    else{
        Write-Warning -Message "File extension `'$Extension`' is not supported as a FavIcon image."
    }

This results in this, if the image is valid.
![image](https://user-images.githubusercontent.com/48139416/72003821-2afc4080-3218-11ea-99fd-df8ab443ada8.png)

If the path has a valid extension, but could not be found.
![image](https://user-images.githubusercontent.com/48139416/72005574-e7a3d100-321b-11ea-9705-04b159360013.png)

If the path does not have a valid extension.
![image](https://user-images.githubusercontent.com/48139416/72005937-b081ef80-321c-11ea-94ce-2a55d8369b8e.png)

**Comment by PrzemyslawKlys** [comment]
what about linked .ico (https?)

**Comment by xlrod** [comment]
Will look into this.

**Comment by PrzemyslawKlys** [comment]
Btw you should consider using [Uri] instead of [string]. It acts as a string when working with paths but gives you lots of options.

```
[uri] $Test = 'https://evotec.xyz/myfile.txt'
[Uri] $Test1 = 'C:\Users\przemyslaw.klys\OneDrive - Evotec\Support\GitHub\PSSharedGoods\PSSharedGoods.psd1'

$Test | fl

$Test1 | fl
```

Also for extension:

```
[System.IO.Path]::GetExtension($Test)
```

System.IO.Path has lots of other useful options. 

![image](https://user-images.githubusercontent.com/15063294/72013496-48ec9400-325e-11ea-879c-0405dee90f1d.png)

**Comment by xlrod** [comment]
Nice! Would this work for the https links?
Changed the parameters to Uri `[Uri] $FavIcon` (works great!)
`[Uri]$FavIcon = "https://icolink.com/components/com_djclassifieds/images/item/1/1990_ico-amazonians-green-coin_thb.jpg"`

    $Extension = [System.IO.Path]::GetExtension($FavIcon)
    if ($Extension -in @('.png', '.jpg', 'jpeg', '.svg', '.ico')) {
        switch ($FavIcon.Scheme) {
            "file" {
                if (Test-Path -Path $FavIcon.OriginalString) {
                    $FavIcon = Get-Item -Path $FavIcon.OriginalString
                    $FavIconImageBinary = Convert-ImageToBinary -ImageFile $FavIcon
                    New-HTMLTag -Tag 'link' -Attributes @{rel = 'icon'; href = "$FavIconImageBinary"; type = 'image/x-icon' }
                }
                else {
                    Write-Warning -Message "The path to the FavIcon image could not be resolved."
                }
            }
            "https" {
                $FavIcon = $FavIcon.OriginalString
                New-HTMLTag -Tag 'link' -Attributes @{rel = 'icon'; href = "$FavIcon"; type = 'image/x-icon' }
            }
            default {
                Write-Warning -Message "The path to the FavIcon image could not be resolved."
            }
        }   
    }
    else {
        Write-Warning -Message "File extension `'$Extension`' is not supported as a FavIcon image.`nPlease use images with these extensions: '.png', '.jpg', 'jpeg', '.svg', '.ico'"
    }

![image](https://user-images.githubusercontent.com/48139416/72022616-e506a300-323e-11ea-8ccc-a567b5515640.png)

![image](https://user-images.githubusercontent.com/48139416/72022602-de782b80-323e-11ea-8075-4916631eec3e.png)

**Comment by PrzemyslawKlys** [comment]
It seems to work ;)
